### ISSUE TITLE
Bash variable conditional in import-release-team-keyring

### ISSUE THREAD

**Issue by squarism** [asdf-vm/asdf-nodejs#106]
I had to change https://github.com/asdf-vm/asdf-nodejs/blob/f7e82ef14a5e72a0cad68077d51dfc51b749ff19/bin/import-release-team-keyring#L24
to be

`if [ ${http_proxy} ]` otherwise I would get a 

```
import-release-team-keyring: line 24: [: -v: unary operator expected
```

Because mac has bash 3.2 seems like.  I'm not sure if my fix is entirely portable (so no PR) but the `-v` I think is for bash >= 4.2.  Maybe this was developed on box with a more up-to-date bash or something, thought I'd file this in case someone hits this.

**Comment by Stratus3D** [comment]
I think we need something like `if [ -n "$1" ]`. We just need to see if it is set to something and is not null.

**Comment by noraj** [comment]
This still fails on mac with bash 3.2 (2007) but asdf it not to blame, Apple is. The more suite solution is to `brew install bash` to have bash v5.0. Bash 3.2 will cause tons of compatibility issue anyway.

**Comment by augustobmoura** [comment]
This should very easy to solve actually. We are still officially supporting bash 3

**Comment by augustobmoura** [comment]
I will probably also give a cleanup of the scripts, there's a ton of things that could be better written in bash
