### ISSUE TITLE
README instructions for Homebrew are incorrect

### ISSUE THREAD

**Issue by d4rky-pl** [asdf-vm/asdf-nodejs#116]
The asdf installed from Homebrew uses the same `~/.asdf` directory.

I'm not sending a PR because someone should check first if this is a bug or a feature in the brew formula and I don't have time right now (sorry!)

**Comment by augustobmoura** [comment]
I think this might be related to a previous README version, but we don't have any homebrew instructions anymore, so I'm closing this
