### ISSUE TITLE
Default packages don't show up in npm

### ISSUE THREAD

**Issue by paulcretu** [asdf-vm/asdf-nodejs#126]
After installing with `$HOME/.default-npm-packages` present, the packages are installed and available, but they don't show up in `npm`:

```console
> npm ls -g --depth=0
.asdf/installs/nodejs/10.4.0/.npm/lib
└── (empty)
```

This is because the default packages get installed with the default prefix (just `ASDF_INSTALL_PATH`) instead of the `NPM_CONFIG_PREFIX` that gets set in `exec-env` (`$ASDF_INSTALL_PATH/.npm`).

For example, some binaries (npm + default packages) end up in `.asdf/installs/nodejs/11.11.0/bin`, while everything installed with npm later goes into `.asdf/installs/nodejs/11.11.0/.npm/bin`. This makes the default installed packages invisible to the shimmed `npm` once everything is installed, making it harder to do upgrades and manage the packages.

**Comment by paulcretu** [comment]
To fix the issue for myself, I use `asdf exec` to get the correct `npm` and set the right env. This requires:

- reshim before installing default packages
- run `npm install` with `ASDF_NODEJS_VERSION` set
- `asdf exec` shouldn't even be necessary if `asdf` `npm` shims are in the path, but include just in case

In the `install` script:

```diff
 install_default_npm_packages() {
   local default_npm_packages="${HOME}/.default-npm-packages"

   if [ ! -f $default_npm_packages ]; then return; fi

   for name in $(cat $default_npm_packages); do
     echo -ne "\nInstalling \e[33m${name}\e[39m npm package... "
-    PATH="$ASDF_INSTALL_PATH/bin:$PATH" npm install -g $name > /dev/null 2>&1
+    ASDF_NODEJS_VERSION="$ASDF_INSTALL_VERSION" asdf exec npm install -g $name > /dev/null 2>&1
     if [[ $? -eq 0 ]]; then
       echo -e "\e[32mSUCCESS\e[39m"
     else
       echo -e "\e[31mFAIL\e[39m"
     fi
   done
 }

 tmp_download_dir="$(mktemp -d -t 'asdf_nodejs_XXXXXX')"
 trap 'rm -rf "${tmp_download_dir}"' EXIT

 install_nodejs "$ASDF_INSTALL_TYPE" "$ASDF_INSTALL_VERSION" "$ASDF_INSTALL_PATH" "$tmp_download_dir"
+asdf reshim nodejs "$ASDF_INSTALL_VERSION"
 ASDF_SKIP_RESHIM=1 install_default_npm_packages
 asdf reshim nodejs "$ASDF_INSTALL_VERSION"
```
Another approach would be to simply set the `NPM_CONFIG_PREFIX` inline (or ideally it could be configured in just one place for both `install` and `exec-env`).

This is related to #67. In fact, by reshimming, the inlined `PATH` isn't necessary and it fixes that issue as well. Does this reshimming approach makes sense? I can gladly submit a PR.

**Comment by tonycoco** [comment]
Yeah, this is still an issue and is a real bummer when trying to figure out where the problem is with global package versions.
