### ISSUE TITLE
Can not install nodejs 10.15.3

### ISSUE THREAD

**Issue by quiqua** [asdf-vm/asdf-nodejs#129]
When running `asdf install nodejs 10.15.3` I'll get the following output:

```
asdf install nodejs 10.15.3
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3884    0  3884    0     0   6313      0 --:--:-- --:--:-- --:--:--  6305
gpg: Signature made Tue Mar  5 18:15:03 2019 CET
gpg:                using RSA key 4ED778F539E3634C779C87C6D7062848A1AB005C
gpg: Good signature from "Beth Griggs <Bethany.Griggs@uk.ibm.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 4ED7 78F5 39E3 634C 779C  87C6 D706 2848 A1AB 005C
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 15.6M  100 15.6M    0     0  6468k      0  0:00:02  0:00:02 --:--:-- 6469k
sha256sum or shasum is not available for use
Authenticity of package archive can not be assured. Exiting.
```

**Comment by Stratus3D** [comment]
Did you run the `import-release-team-keyring` script?

**Comment by lukekhamilton** [comment]
@Stratus3D can you provide more details about this script? I run the command as pre the READMD.md and there is no such file?? 

` bash /usr/local/opt/asdf/plugins/nodejs/bin/import-release-team-keyring
bash: /usr/local/opt/asdf/plugins/nodejs/bin/import-release-team-keyring: No such file or directory
`

**Comment by lukekhamilton** [comment]
What do you know. I just worked it out. :) I installed asdf via homebrew. However looks like that the plugins are all getting installed to my `~/.asdf/plugins/*` location.

**Comment by lukekhamilton** [comment]
Running the following fixed the issue logged above for me: 

`bash ~/.asdf/plugins/nodejs/bin/import-release-team-keyring`

**Comment by mistercorea** [comment]
that doesn't resolve the issue
```
gpg:                using RSA key 4ED778F539E3634C779C87C6D7062848A1AB005C
gpg: Can't check signature: No public key
Authenticity of checksum file can not be assured! Please be sure to check the README of asdf-nodejs in case you did not yet bootstrap trust. If you already did that then that is the point to become SUSPICIOUS! There must be a reason why this is failing. If you are installing an older NodeJS version you might need to import OpenPGP keys of previous release managers. Exiting.```

**Comment by Stratus3D** [comment]
Thanks @lukekhamilton, asdf was changed so everything is installed to `~/.asdf` by default, even when installing with brew.

**Comment by Stratus3D** [comment]
I'm going to close this issue as I do not think there are any other problems with asdf-nodejs that are causing this.

**Comment by mistercorea** [comment]
```asdf install nodejs 10.15.3
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3884    0  3884    0     0   8426      0 --:--:-- --:--:-- --:--:--  8443
gpg: Signature made Tue Mar  5 11:15:03 2019 CST
gpg:                using RSA key 4ED778F539E3634C779C87C6D7062848A1AB005C
gpg: Can't check signature: No public key
Authenticity of checksum file can not be assured! Please be sure to check the README of asdf-nodejs in case you did not yet bootstrap trust. If you already did that then that is the point to become SUSPICIOUS! There must be a reason why this is failing. If you are installing an older NodeJS version you might need to import OpenPGP keys of previous release managers. Exiting.```

**Comment by Stratus3D** [comment]
@mistercorea you've got a connectivity issue. GPG is complaining it can't reach the host.

**Comment by mistercorea** [comment]
gpg --keyserver ipv4.pool.sks-keyservers.net --recv-keys 4ED778F539E3634C779C87C6D7062848A1AB005C
gpg: key D7062848A1AB005C: "Beth Griggs <Bethany.Griggs@uk.ibm.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1

**Comment by mistercorea** [comment]
I think something is wrong there @Stratus3D .

**Comment by bplasmeijer** [comment]
same issue here; 10.15.3; I try to figure out what is going on...
gpg: keyring `C:/Users/ContainerAdministrator/AppData/Roaming/gnupg/secring.gpg' created
gpg: keyring `C:/Users/ContainerAdministrator/AppData/Roaming/gnupg/pubring.gpg' created
gpg: requesting key A1AB005C from hkp server ha.pool.sks-keyservers.net
gpg: C:/Users/ContainerAdministrator/AppData/Roaming/gnupg/trustdb.gpg: trustdb created
gpg: key A1AB005C: public key "Beth Griggs <Bethany.Griggs@uk.ibm.com>" imported
gpg: no ultimately trusted keys found
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
gpg: requesting key 5599653C from hkp server ha.pool.sks-keyservers.net
gpg: key 5599653C: public key "Shelley Vohr (security is major key) <shelley.vohr@gmail.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
gpg: requesting key DBE9B9C5 from hkp server ha.pool.sks-keyservers.net
gpg: key DBE9B9C5: public key "Colin Ihrig <cjihrig@gmail.com>" imported
gpg: no ultimately trusted keys found
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
gpg: requesting key 4C206CA9 from hkp server ha.pool.sks-keyservers.net
gpg: key 4C206CA9: public key "Evan Lucas <evanlucas@me.com>" imported
gpg: no ultimately trusted keys found
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
gpg: requesting key 821C587A from hkp server ha.pool.sks-keyservers.net
gpg: key 821C587A: public key "Gibson Fahnestock <gibfahn@gmail.com>" imported
gpg: no ultimately trusted keys found
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
gpg: requesting key 7EDE3FC1 from hkp server ha.pool.sks-keyservers.net
gpg: key 7EDE3FC1: public key "keybase.io/jasnell <jasnell@keybase.io>" imported
gpg: no ultimately trusted keys found
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
gpg: requesting key 4EB7990E from hkp server ha.pool.sks-keyservers.net
gpg: key 4EB7990E: public key "Jeremiah Senkpiel <fishrock123@rocketmail.com>" imported
gpg: no ultimately trusted keys found
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
gpg: requesting key 5AE15600 from hkp server ha.pool.sks-keyservers.net
gpg: key 5AE15600: public key "Michaël Zasso (Targos) <targos@protonmail.com>" imported
gpg: no ultimately trusted keys found
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
gpg: requesting key CC11F4C8 from hkp server ha.pool.sks-keyservers.net
gpg: key CC11F4C8: public key "Myles Borins <myles.borins@gmail.com>" imported
gpg: no ultimately trusted keys found
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
gpg: requesting key 7D83545D from hkp server ha.pool.sks-keyservers.net
gpg: key 7D83545D: public key "Rod Vagg <rod@vagg.org>" imported
gpg: no ultimately trusted keys found
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
gpg: requesting key EB3C1762 from hkp server ha.pool.sks-keyservers.net
gpg: key EB3C1762: public key "Ruben Bridgewater <ruben@bridgewater.de>" imported
gpg: no ultimately trusted keys found
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)

**Comment by podung** [comment]
I've got the same issue with 10.15.3 - and I've imported all the keys of previous release maintainers as well

**Comment by monting** [comment]
I had a similar issue. Seems to have been resolved by uninstalling the asdf nodejs plugin, and reinstalling again.

**Comment by nadnoslen** [comment]
Thanks @monting, I completely removed my nodejs using `asdf plugin-remove nodejs` and then added it again and installed the versions successfully.  Creepy.
