### ISSUE TITLE
Unable to install nodejs

### ISSUE THREAD

**Issue by vkk-steigend** [asdf-vm/asdf-nodejs#130]
I tried to install nodejs using asdf. Following steps were executed:

1. asdf plugin-add nodejs
2. ~/.asdf/plugins/nodejs/bin/import-release-team-keyring
3. asdf install nodejs 10.15.3

I am getting the following error:
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3884    0  3884    0     0  14438      0 --:--:-- --:--:-- --:--:-- 14438
gpg: Signature made Tue Mar  5 22:45:03 2019 IST
gpg:                using RSA key 4ED778F539E3634C779C87C6D7062848A1AB005C
gpg: Good signature from "Beth Griggs <Bethany.Griggs@uk.ibm.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 4ED7 78F5 39E3 634C 779C  87C6 D706 2848 A1AB 005C
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7039    0  7039    0     0   5595      0 --:--:--  0:00:01 --:--:--  5590
**Binaries were not found. Full version must be specified, not just major version.**

**Comment by vkk-steigend** [comment]
This issue is related to the issue #78

**Comment by jma26** [comment]
I came across this issue just now and upon deeper look into the install file with file pathway ~/.asdf/plugins/nodejs/bin. The download_file() has an invalid download_url with https://nodejs.org/dist/<version number>/node-<version number>-mingw64_nt-10.0-x64.tar.gz does not exist

**Comment by jma26** [comment]
I had to manually type out the correct link and this allowed me to install nodejs, hope this helps

**Comment by jamesking** [comment]
Having this issue as well.

**Comment by carusso** [comment]
I just installed asdf and the nodejs plugin and this problem still occurs.

**Comment by joaquinalcerro** [comment]
Hi, has this issue been resolved? Just installed asdf and unable to install nodejs versions.

Thanks in advance for your help.

Best regards

**Comment by joaquinalcerro** [comment]
@jma26 can you please provide a example to your work arround?

Thanks for your help.

**Comment by joaquinalcerro** [comment]
So digging a bit deeper, I found that one of my issues is that I am running FreeBsd 12.1 and none of the node packages are labled FreeBsd. As I can see in the asdf code, it searches the package to install based on the uname -m resulta and in my case returns FreeBsd.

I am trying to make it work manually but no having trouble with shasum. It claims: "no properly formatted SHA checksum lines found".

This is the output:
```
shasum: node-v12.6.0.tar.gz: no properly formatted SHA checksum lines found
shasum: node-v12.6.0-aix-ppc64.tar.gz: No such file or directory
node-v12.6.0-aix-ppc64.tar.gz: FAILED open or read
shasum: node-v12.6.0-darwin-x64.tar.gz: No such file or directory
node-v12.6.0-darwin-x64.tar.gz: FAILED open or read
shasum: node-v12.6.0-darwin-x64.tar.xz: No such file or directory
node-v12.6.0-darwin-x64.tar.xz: FAILED open or read
shasum: node-v12.6.0-headers.tar.gz: No such file or directory
node-v12.6.0-headers.tar.gz: FAILED open or read
shasum: node-v12.6.0-headers.tar.xz: No such file or directory
node-v12.6.0-headers.tar.xz: FAILED open or read
shasum: node-v12.6.0-linux-arm64.tar.gz: No such file or directory
node-v12.6.0-linux-arm64.tar.gz: FAILED open or read
shasum: node-v12.6.0-linux-arm64.tar.xz: No such file or directory
node-v12.6.0-linux-arm64.tar.xz: FAILED open or read
shasum: node-v12.6.0-linux-armv7l.tar.gz: No such file or directory
node-v12.6.0-linux-armv7l.tar.gz: FAILED open or read
shasum: node-v12.6.0-linux-armv7l.tar.xz: No such file or directory
node-v12.6.0-linux-armv7l.tar.xz: FAILED open or read
shasum: node-v12.6.0-linux-ppc64le.tar.gz: No such file or directory
node-v12.6.0-linux-ppc64le.tar.gz: FAILED open or read
shasum: node-v12.6.0-linux-ppc64le.tar.xz: No such file or directory
node-v12.6.0-linux-ppc64le.tar.xz: FAILED open or read
shasum: node-v12.6.0-linux-s390x.tar.gz: No such file or directory
node-v12.6.0-linux-s390x.tar.gz: FAILED open or read
shasum: node-v12.6.0-linux-s390x.tar.xz: No such file or directory
node-v12.6.0-linux-s390x.tar.xz: FAILED open or read
shasum: node-v12.6.0-linux-x64.tar.gz: No such file or directory
node-v12.6.0-linux-x64.tar.gz: FAILED open or read
shasum: node-v12.6.0-linux-x64.tar.xz: No such file or directory
node-v12.6.0-linux-x64.tar.xz: FAILED open or read
shasum: node-v12.6.0.pkg: No such file or directory
node-v12.6.0.pkg: FAILED open or read
shasum: node-v12.6.0-sunos-x64.tar.gz: No such file or directory
node-v12.6.0-sunos-x64.tar.gz: FAILED open or read
shasum: node-v12.6.0-sunos-x64.tar.xz: No such file or directory
node-v12.6.0-sunos-x64.tar.xz: FAILED open or read
**node-v12.6.0.tar.gz: OK**
shasum: node-v12.6.0.tar.xz: No such file or directory
node-v12.6.0.tar.xz: FAILED open or read
shasum: node-v12.6.0-win-x64.7z: No such file or directory
node-v12.6.0-win-x64.7z: FAILED open or read
shasum: node-v12.6.0-win-x64.zip: No such file or directory
node-v12.6.0-win-x64.zip: FAILED open or read
shasum: node-v12.6.0-win-x86.7z: No such file or directory
node-v12.6.0-win-x86.7z: FAILED open or read
shasum: node-v12.6.0-win-x86.zip: No such file or directory
node-v12.6.0-win-x86.zip: FAILED open or read
shasum: node-v12.6.0-x64.msi: No such file or directory
node-v12.6.0-x64.msi: FAILED open or read
shasum: node-v12.6.0-x86.msi: No such file or directory
node-v12.6.0-x86.msi: FAILED open or read
shasum: win-x64/node.exe: No such file or directory
win-x64/node.exe: FAILED open or read
shasum: win-x64/node.lib: No such file or directory
win-x64/node.lib: FAILED open or read
shasum: win-x64/node_pdb.7z: No such file or directory
win-x64/node_pdb.7z: FAILED open or read
shasum: win-x64/node_pdb.zip: No such file or directory
win-x64/node_pdb.zip: FAILED open or read
shasum: win-x86/node.exe: No such file or directory
win-x86/node.exe: FAILED open or read
shasum: win-x86/node.lib: No such file or directory
win-x86/node.lib: FAILED open or read
shasum: win-x86/node_pdb.7z: No such file or directory
win-x86/node_pdb.7z: FAILED open or read
shasum: win-x86/node_pdb.zip: No such file or directory
win-x86/node_pdb.zip: FAILED open or read
shasum: WARNING: 33 listed files could not be read
```

**Comment by aa7955** [comment]
Same issue on macOS. 

```
➜  ~ asdf install nodejs 12.16.3
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4029    0  4029    0     0  29625      0 --:--:-- --:--:-- --:--:-- 29625
Authenticity of checksum file can not be assured! Please be sure to check the README of asdf-nodejs in case you did not yet import the needed PGP keys. If you already did that then that is the point to become SUSPICIOUS! There must be a reason why this is failing. If you are installing an older NodeJS version you might need to import OpenPGP keys of previous release managers. Exiting.
```

**Comment by defp** [comment]
```
❯ asdf install nodejs 15.5.0
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3811    0  3811    0     0   9161      0 --:--:-- --:--:-- --:--:--  9161
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 10858    0 10858    0     0  24789      0 --:--:-- --:--:-- --:--:-- 24733
Binaries were not found. Full version must be specified, not just major version.
```

**Comment by andresavic** [comment]
I had the same issue on the Apple M1 Mac. Running `arch -x86_64 zsh` or `arch -x86_64 bash` is a great workaround.

**Comment by jonnyasmar** [comment]
If you're running into this with Terminal or Iterm, you can avoid having to run the `arch -x86_64 zsh/bash` commands by informing your machine to always run them with Rosetta.

For starters, if your machine has never prompted you to install Rosetta, you'll want to do it manually with the following command:

`softwareupdate --install-rosetta`

Next, you'll need to right click the iTerm or Terminal apps in your Applications directory and click "Get Info". In the menu that pops up, look for the check box "Open using Rosetta" and check it. Now they'll always use Rosetta to translate for Apple silicone.

**Comment by jersearls** [comment]
> If you're running into this with Terminal or Iterm, you can avoid having to run the `arch -x86_64 zsh/bash` commands by informing your machine to always run them with Rosetta.
> 
> For starters, if your machine has never prompted you to install Rosetta, you'll want to do it manually with the following command:
> 
> `softwareupdate --install-rosetta`
> 
> Next, you'll need to right click the iTerm or Terminal apps in your Applications directory and click "Get Info". In the menu that pops up, look for the check box "Open using Rosetta" and check it. Now they'll always use Rosetta to translate for Apple silicone.

THANK YOU. Haha couldn't figure this out and it totally fixed my issue. Anyone on an M1 ^^^^

**Comment by radiosilence** [comment]
Still no joy.

```
% arch -x86_64 asdf install nodejs 14.17.6
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3490    0  3490    0     0  39213      0 --:--:-- --:--:-- --:--:-- 39213
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 10156    0 10156    0     0   100k      0 --:--:-- --:--:-- --:--:--  100k
Binary not found for version 14.17.6
```

**Comment by augustobmoura** [comment]
> Still no joy on M1 macOS 11.4

Did you try installing in an x86 interactive shell, as @andresavic suggested? Try opening bash in x86 with `arch -x86_64 bash` and then running `asdf install`
 
> Seems to work for 16.x.x though, so i guess there's no lts binaries for M1?

There's no pre-compiled M1 [binaries for 14.17.6](https://nodejs.org/dist/v14.17.6/) (search for darwin-arm64, you can see that they are present in the [16.x branch](https://nodejs.org/dist/latest-v16.x/)). Even so, running the installation with `arch -x86_64` should install x86 binaries compatible with Rosetta

asdf-nodejs also gives the option for automatically compiling nodejs from source in M1, see #78 for workarounds. We are working on making it fallback to compilation if the pre-compiled binaries are not found

**Comment by usamaInvozone** [comment]
For future budies 
add your plugin first like i added few as below
asdf plugin-add erlang https://github.com/asdf-vm/asdf-erlang.git
asdf plugin-add elixir https://github.com/asdf-vm/asdf-elixir.git
asdf plugin-add nodejs https://github.com/asdf-vm/asdf-nodejs.git

**Comment by galihlprakoso** [comment]
For Apple M1, I'm using Rosseta terminal. https://www.youtube.com/watch?v=9W8rTTE1WEA
