### ISSUE TITLE
Add symlinks for latest and lts

### ISSUE THREAD

**Issue by watzon** [asdf-vm/asdf-nodejs#134]
It would be nice to be able to install `latest` or `lts` and have it fetch that version rather than having to specify a version explicitly.

**Comment by dboune** [comment]
This is one feature I miss from nvm, and would be thrilled at even better. I have a number of projects where the specific version isn't critical, but it has been useful in some cases to be able to pin to a particular lts release. As well, being able to install using such tags would be a boon.

Not having to worry about the specific tightly bound version for dozens of small projects with loose requirements would be a bit of help, and ensuring a latest version for install would be assistive.

#### Possible Use Cases

Latest installed version of a specific LTS release:
`asdf install nodejs lts/carbon`
`asdf local nodejs lts/carbon`

Latest installed LTS release:
`asdf install nodejs lts`
`asdf local nodejs lts`

Track the latest installed version:
`asdf install nodejs latest`
`asdf local nodejs latest`

**Related Tickets**:
[Feature] Implement flexible versions #127
Use package.json engines version? #60
add package.json to legacy files #120

**Comment by bencates** [comment]
This would also resolve a pain point with `legacy_version_file` support in projects that target an LTS in their `.nvmrc` file.

**Comment by selfish** [comment]
Is there an update on this?

**Comment by yujinyuz** [comment]
really missing this one while using nvm. hope it gets implemented soon!

**Comment by augustobmoura** [comment]
I will work on it this week, maybe we can get the pr by the end of the week. I plan to add support for lts aliases too (lts/boron, lts/argon etc.)

**Comment by augustobmoura** [comment]
I created the pull request #176

**Comment by blimmer** [comment]
I'm experiencing a problem trying to use the LTS aliases with this new feature.

```console
 asdf install nodejs lts/erbium
mkdir: /Users/blimmer/.asdf/installs/nodejs/lts: No such file or directory
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 10858    0 10858    0     0  95245      0 --:--:-- --:--:-- --:--:-- 95245
Checksum not found for version lts/erbium
```

I also tried `mkdir`-ing that directory it marked as missing, but that didn't fix the problem either.

```console
 mkdir /Users/blimmer/.asdf/installs/nodejs/lts
 asdf install nodejs lts/erbium
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 10858    0 10858    0     0  97819      0 --:--:-- --:--:-- --:--:-- 97819
Checksum not found for version lts/erbium
```

```console
 asdf --version
v0.8.0
 asdf plugin list --refs
java                         master f47ba04
nodejs                       master 1624799
ruby                         master 08d660f
```

Any ideas @Stratus3D or @augustobmoura ?

**Comment by dcalhoun** [comment]
> EDIT: oh, wait I see. the version is listed with a dash. that's a bit of a bummer, since [nvm uses slashes](https://github.com/nvm-sh/nvm#long-term-support).

Ah, yeah, that is a bummer. I was excited to use this new capability with my team's existing `.nvmrc` that contains `lts/*`. @blimmer maybe the next best step is for us to open a new issue?

**Comment by blimmer** [comment]
Sounds good to me - @dcalhoun do you want to open that up and tag me as a requester as well?

**Comment by dcalhoun** [comment]
@blimmer I created #193. Please feel free to add a 👍🏻 or provide additional context that could be helpful.
