### ISSUE TITLE
Making "import-release-team-keyring" default behavior?

### ISSUE THREAD

**Issue by southwolf** [asdf-vm/asdf-nodejs#138]
From user friendly perspective, is it a good idea to make the "import-release-team-keyring" step integrated in the plugin installation process, since it's only a harmless command importing some keys well known as _secure_ ones?

Every time I setup asdf node I would got this _no public key_ error message and it makes me feel stupid to take an extra step, shouldn't it be working out-of-box?

**Comment by Stratus3D** [comment]
I think this would be a nice feature to have, but I think we may need to keep the gpg keys imported for this nodejs plugin separate from the other gpg keys the user may have imported on their own. Right now I think keys get imported to the user's own keyring, and I think we should figure out how to have separate keyring for just this plugin.

**Comment by vadave** [comment]
PR #209 included automatically importing the keys as default behavior.

**Comment by Stratus3D** [comment]
Since the nodejs GPG keys are stored on a separate nodejs keyring, and the keys are automatically imported before installing, I am closing this ticket.
