### ISSUE TITLE
WARNING: This key is not certified with a trusted signature!

### ISSUE THREAD

**Issue by byteshiva** [asdf-vm/asdf-nodejs#146]
Can there be an explanation for the below warning.

**gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: A48C 2BEE 680E 8416 32CD  4E44 F074 96B3 EB3C 1762**

```asdf install nodejs 12.12.0
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4029    0  4029    0     0  18435      0 --:--:-- --:--:-- --:--:-- 18481
gpg: Signature made Sat 12 Oct 2019 03:28:08 AM IST
gpg:                using RSA key A48C2BEE680E841632CD4E44F07496B3EB3C1762
gpg: Good signature from "Ruben Bridgewater <ruben@bridgewater.de>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: A48C 2BEE 680E 8416 32CD  4E44 F074 96B3 EB3C 1762
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 20.6M  100 20.6M    0     0  1051k      0  0:00:20  0:00:20 --:--:-- 1780k
node-v12.12.0-linux-x64.tar.gz: OK

```

**Comment by LunaCodeGirl** [comment]
I'm seeing something similar today...

**Comment by Stratus3D** [comment]
Is this a problem? The warning probably isn't helpful, but the install should be successful even with this warning.

See https://serverfault.com/questions/569911/how-to-verify-an-imported-gpg-key for more info.

**Comment by byteshiva** [comment]
> warning probably isn't helpful

it did'nt work as expected, 

```
uname -a
Linux  5.3.0-25-generic #27-Ubuntu SMP Wed Dec 4 13:36:32 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

```
```
asdf install nodejs 13.5.0
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3658    0  3658    0     0   6650      0 --:--:-- --:--:-- --:--:--  6650
gpg: Signature made Thursday 19 December 2019 12:21:44 AM IST
gpg:                using RSA key 0EFFE1BCEFD9C84E3D098152933B01F40B5CA946
gpg: Can't check signature: No public key
Authenticity of checksum file can not be assured! Please be sure to check the README of asdf-nodejs in case you did not yet bootstrap trust. If you already did that then that is the point to become SUSPICIOUS! There must be a reason why this is failing. If you are installing an older NodeJS version you might need to import OpenPGP keys of previous release managers. Exiting.
```

**Comment by byteshiva** [comment]
> Is this a problem? The warning probably isn't helpful, but the install should be successful even with this warning.
> 
> See https://serverfault.com/questions/569911/how-to-verify-an-imported-gpg-key for more info.

The installation went good, but I'd like to avoid the warning by using the trusted key. Can I use my own key to download the nodejs current installation file.


```
➜ asdf install nodejs 13.5.0
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3658    0  3658    0     0   1257      0 --:--:--  0:00:02 --:--:--  1257
gpg: Signature made Thursday 19 December 2019 12:21:44 AM IST
gpg:                using RSA key 0EFFE1BCEFD9C84E3D098152933B01F40B5CA946
gpg: Good signature from "Myles Borins <myles.borins@gmail.com>" [unknown]
gpg:                 aka "Myles Borins <mborins@google.com>" [unknown]
gpg:                 aka "Myles Borins <mylesborins@google.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: C4F0 DFFF 4E8C 1A82 3640  9D08 E73B C641 CC11 F4C8
     Subkey fingerprint: 0EFF E1BC EFD9 C84E 3D09  8152 933B 01F4 0B5C A946
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 31.6M  100 31.6M    0     0   937k      0  0:00:34  0:00:34 --:--:--  800k
node-v13.5.0-linux-x64.tar.gz: OK

```

**Comment by byteshiva** [comment]
I'm going to use the below steps to create gpg keys, Can I use the below key to download the installable nodejs file.

https://help.github.com/en/github/authenticating-to-github/generating-a-new-gpg-key

**Comment by Stratus3D** [comment]
@byteshiva this warning is telling you that the key of the developer is signed the Node.JS release for Node 13.5.0 isn't a key you trusted yourself. As it says in that Stackoverflow question I linked to:

> A "trusted signature" is a signature from a key that you trust, either because (a) you have personally verified that it belongs to the person to whom it claims to belong, or (b) because it has been signed by a key that you trust, possibly through a series of intermediate keys.

If you don't want to go through the hassle of verifying that key (either by meeting the developer in person or contacting them through an existing secure channel) you can ignore the warning. It is up to you, but most people won't bother to verify keys on their own, so I'm inclined to hide this output.

**Comment by Stratus3D** [comment]
I merged a PR to hide the warning for this.
