### ISSUE TITLE
Unable to import keys with gpg2

### ISSUE THREAD

**Issue by manuraj17** [asdf-vm/asdf-nodejs#147]
I have gpg2 instead of gpg on my machine. When trying to execute this command `bash ~/.asdf/plugins/nodejs/bin/import-release-team-keyring`, it failed since I was having gpg2 executable and the script has gpg. 

Got it working by changing the script in my local to use `gpg2` instead of `gpg` in the line `    gpg2 --no-tty --keyserver "hkp://$server" $OPTIONS --display-charset utf-8 --recv-keys "$key"  && break`

Not sure if this is a good way.

Also, if there are people using `gpg2` should this script be updated?

**Comment by Stratus3D** [comment]
Good question @manuraj17. I am not aware of any differences between `gpg` and `gpg2` that would cause any problems in the `import-release-team-keyring` script. I think we could just add a conditional to the script to use `gpg` if it is present, and if not try `gpg2`.

This answer might be interesting to you: https://superuser.com/questions/655246/are-gnupg-1-and-gnupg-2-compatible-with-each-other

**Comment by Stratus3D** [comment]
What OS are you on?

**Comment by manuraj17** [comment]
@Stratus3D Sorry, missed the message. I am on Mojave 10.14.6. Don't think it would matter now but anyways :D.
