### ISSUE TITLE
default packages file location

### ISSUE THREAD

**Issue by quintrino** [asdf-vm/asdf-nodejs#152]
Is it possible to have asdf-nodejs check for the default packages based on the location of the asdf config files? 

I'm aware of this PR to add similar functionality to the Ruby Plugin (https://github.com/asdf-vm/asdf-ruby/issues/111) but it would be great to have this in Node as well.

**Comment by jsejcksn** [comment]
In the context of this request, is it too late to rename this file?

currently: `$HOME/.default-npm-packages`
suggested: `$HOME/.npm-default-packages`

Grouping npm-related files together in the home directory by `npm*` is very nice 😄

**Comment by augustobmoura** [comment]
This was implemented in #170 some time ago, sorry for not closing the issue earlier. Now we have the `ASDF_NPM_DEFAULT_PACKAGES_FILE` env variable for overriding the file location
