### ISSUE TITLE
Install hangs in non-interactive environments

### ISSUE THREAD

**Issue by ahawkins** [asdf-vm/asdf-nodejs#165]
We use leverage `asdf-nodejs` as part of an Ansible playbook to configure our team's local machine. Recently our CI runs started failing because of an interactive yes/no prompt. Here's the output:

```
File '/var/folders/pt/0xykrh9j62g34sc7znh47kbc0000gn/T/asdf_nodejs_XXXXXX.wDCahShg/authentic_SHASUMS256.txt' exists. Overwrite? (y/N) 
```

It seems that this temporary directory is cleaned up after each install (https://github.com/asdf-vm/asdf-nodejs/blob/master/bin/install#L284-L285), so I'm confused how this should happen. Is there some code path that may create this file twice resulting in this prompt?

**Comment by Jeiwan** [comment]
I'm having this as well:
```
$ asdf install nodejs 12.11.1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4029    0  4029    0     0  28778      0 --:--:-- --:--:-- --:--:-- 28778
File '/tmp/asdf_nodejs_Wf7Kpu/authentic_SHASUMS256.txt' exists. Overwrite? (y/N)
```
The temp folder doesn't exist before the command is run.

**Comment by danielporto** [comment]
Still having this problem.

**Comment by gabecook** [comment]
I'm also having this problem, but the pull request https://github.com/asdf-vm/asdf-nodejs/pull/187 fixes it.
