### ISSUE TITLE
cannot update npm completely

### ISSUE THREAD

**Issue by HonoluluHenk** [asdf-vm/asdf-nodejs#168]
MacOS catalina, fresh install of asdf-vm (bot git and homebrew) and nodejs plugin.
`❯ asdf --version`
v0.7.8-4a3e3d6
Nodejs plugin:
cd8dc32 (HEAD -> master, origin/master, origin/HEAD) HEAD@{0}: clone: from https://github.com/asdf-vm/asdf-nodejs.git

Steps to reproduce:
```bash
asdf install nodejs 12.13.1
asdf global nodejs 12.13.1
npm i -g npm
```

This currently seems to install npm@6.14.5
`npm --version`
6.14.5

*but*:
`npx npm --version`
still runs the old version: 6.12.1

What I noticed :
```
❯ ls -a ~/.asdf/installs/nodejs/12.13.1
.            ..           .npm         CHANGELOG.md LICENSE      README.md    bin          include      lib          share
```
There's a '.npm' directory.

Listing bin:
```
❯ ls -la ~/.asdf/installs/nodejs/12.13.1/bin
total 82616
drwxr-xr-x   5 foo  staff       160 19 Nov  2019 .
drwxr-xr-x  10 foo  staff       320  3 Jul 16:20 ..
-rwxr-xr-x   1 foo  staff  42297408 19 Nov  2019 node
lrwxr-xr-x   1 foo  staff        38 19 Nov  2019 npm -> ../lib/node_modules/npm/bin/npm-cli.js
lrwxr-xr-x   1 foo  staff        38 19 Nov  2019 npx -> ../lib/node_modules/npm/bin/npx-cli.js
```

Listing .npm/bin:
```
❯ ls -la ~/.asdf/installs/nodejs/12.13.1/.npm/bin
total 0
drwxr-xr-x  4 foo  staff  128  3 Jul 16:21 .
drwxr-xr-x  5 foo  staff  160  3 Jul 16:21 ..
lrwxr-xr-x  1 foo  staff   38  3 Jul 16:21 npm -> ../lib/node_modules/npm/bin/npm-cli.js
lrwxr-xr-x  1 foo  staff   38  3 Jul 16:21 npx -> ../lib/node_modules/npm/bin/npx-cli.js
```

So it seems there are two installations of npm:
```
❯ bin/npm --version
6.12.1
```

```
❯ .npm/bin/npm --version
6.14.5
```

I - and probably npx, too :) - was not expecting this for a global install.

FYI: after a fresh install of nodejs, the .npm/bin directory does not exist, only after the npm upgrade

Might be related to: #157

**Comment by augustobmoura** [comment]
I think is related to #56, the commit https://github.com/asdf-vm/asdf-nodejs/commit/7b6df2d0c664e4bfcf4d037321516fabc82d5356 specifically, that overrides the npm binary by the one in .bin

I think trying both in the bin and .bin (in that order) should fix this. I will try something about it

**Comment by augustobmoura** [comment]
@HonoluluHenk can you test the issue with the latest npm release? I could only reproduce with npm@6.x.x, I think it was a issue with the npx executable
