### ISSUE TITLE
default-npm-packages installs `undefined` when trailing newline is present

### ISSUE THREAD

**Issue by superhawk610** [asdf-vm/asdf-nodejs#172]
When `$HOME/.default-npm-packages` ends in a trailing newline (as many editors add automatically), the postinstall script attempts to run `npm install undefined` and you end up with `undefined@0.0.0` installed globally. It seems to be [harmless enough](https://www.npmjs.com/package/undefined), but this doesn't seem like intended behaviour.

```
➜  code asdf install nodejs 14.7.0
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3466    0  3466    0     0  37673      0 --:--:-- --:--:-- --:--:-- 37268
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 30.3M  100 30.3M    0     0  22.2M      0  0:00:01  0:00:01 --:--:-- 22.2M
node-v14.7.0-linux-armv7l.tar.gz: OK

Installing yarn npm package... SUCCESS

Installing  npm package... SUCCESS
```

Here's the relevant line in `install`: https://github.com/asdf-vm/asdf-nodejs/blob/master/bin/install#L267

**Comment by augustobmoura** [comment]
#291 fixed it. Thanks for reporting, and sorry for the long time with no response!
