### ISSUE TITLE
Some apps will try to use system nodejs if installed

### ISSUE THREAD

**Issue by ctsstc** [asdf-vm/asdf-nodejs#177]
It may be helpful to add to the readme something about uninstalling the system nodejs if it is recommended. For me I did not realize rails was using the system nodejs until it threw an error about node being too low. Uninstalling the system nodejs via `sudo apt remove nodejs` worked just fine afterwards - seems to be loading the asdf nodejs version now.

**Comment by augustobmoura** [comment]
I don't think there's a need or recommendation to remove the system installation both will work in the same system, also there are cases where a different system and user installation makes sense, like a multi user setup in a server, or apt dependencies. The user need to be aware of PATH ordering and hardcode paths independently of the plugin

**Comment by augustobmoura** [comment]
Closing because, PATH ordering issues should be resolved by each user
