### ISSUE TITLE
Cannot use npm after installing through asdf

### ISSUE THREAD

**Issue by danikgan** [asdf-vm/asdf-nodejs#178]
<img width="224" alt="CleanShot 2020-10-23 at 18 00 59@2x" src="https://user-images.githubusercontent.com/16155742/97026532-cbc6ad00-1559-11eb-8e0b-cf30c0fc88c2.png">

I've installed many things through asdf (python, java, Scala etc.), but when I try to install nodejs, I get that everything is installed. `asdf current` shows I have nodejs set correctly. However, I still cannot use `npm` -- my terminal or ZSH do not find it in the path.

What shall I do? Do you need more context to this issue?

**Comment by maxie7** [comment]
You need to add this 
`. $HOME/.asdf/asdf.sh`
to the end of your **.zshrc** file and reboot terminal (or just open another tab of your terminal

**Comment by augustobmoura** [comment]
@danikgan, does this issue still persist? I can't reproduce it on my side
