### ISSUE TITLE
Cannot install node 14.15.0

### ISSUE THREAD

**Issue by victordidenko** [asdf-vm/asdf-nodejs#179]
Looks like [Danielle Adams has changed his key](https://github.com/nodejs/node/#release-keys):

> Danielle Adams <adamzdanielle@gmail.com> 1C050899334244A8AF75E53792EF661D867B9DFA

```
gpg --keyserver ha.pool.sks-keyservers.net --recv-keys 1C050899334244A8AF75E53792EF661D867B9DFA
```

Fixes problem

**Comment by nazarhussain** [comment]
https://github.com/asdf-vm/asdf-nodejs/pull/180

**Comment by DylanAndrews** [comment]
Thanks! For others trying to fix this, heads up that running `gpg --keyserver ha.pool.sks-keyservers.net --recv-keys 1C050899334244A8AF75E53792EF661D867B9DFA` did not fix the issue for me. I had to run the command for all of the keys [here](https://github.com/nodejs/node/#release-keys).

**Comment by victordidenko** [comment]
@DylanAndrews hm, maybe that is because I executed
```
bash -c '${ASDF_DATA_DIR:=$HOME/.asdf}/plugins/nodejs/bin/import-release-team-keyring'
```
before :) it has updated some of the existing keys, but not enough to install 14.15.0

**Comment by DylanAndrews** [comment]
@victordidenko Strange. I actually did run `bash -c '${ASDF_DATA_DIR:=$HOME/.asdf}/plugins/nodejs/bin/import-release-team-keyring'` first and it still didn't work for me. Not sure why though. 🤷‍♂️

**Comment by Stratus3D** [comment]
I believe this has been fixed by #180 which has been merged. Please comment if updating the plugin (`asdf plugin-update nodejs`) and re-running the import scripts does not fix the problem.

**Comment by j0hnm4r5** [comment]
Running `asdf plugin-update nodejs` did not fix the problem for me.

---

To confirm, `asdf install nodejs 14.14.0` works fine, but `asdf install nodejs 14.15.0` responds with:

```
Authenticity of checksum file can not be assured! Please be sure to check the README of asdf-nodejs in case you did not yet import the needed PGP keys. If you already did that then that is the point to become SUSPICIOUS! There must be a reason why this is failing. If you are installing an older NodeJS version you might need to import OpenPGP keys of previous release managers. Exiting.
```

And this is after ensuring both the new and old release team keys have been added.

**Comment by bkaney** [comment]
> Running `asdf plugin-update nodejs` did not fix the problem for me.
> 
> To confirm, `asdf install nodejs 14.14.0` works fine, but `asdf install nodejs 14.15.0` responds with:
> 

I am still having this problem (using master branch as of today). Looking at my GPG Keychain, I see all the keys mentioned here (and in master) are imported correctly.

**Comment by nazarhussain** [comment]
@bkaney Did you tried this? 

```
bash -c '${ASDF_DATA_DIR:=$HOME/.asdf}/plugins/nodejs/bin/import-release-team-keyring'
```

https://github.com/asdf-vm/asdf-nodejs#install

**Comment by bkaney** [comment]
Yes, I did this and then verified all the items in that file were in my local GPG Keychain. I am going to ask a few others on my team to see if they have problems as well.

**Comment by bkaney** [comment]
Okay, it's a problem for just me, apparently...

**Comment by Couto** [comment]
> Okay, it's a problem for just me, apparently...

No it's not. I have the same problem. Tried to upgrade asdf from homebrew, and running the import-release-team-keyring script with no luck.

Currently on: asdf v0.8.0

**Comment by yofriadi** [comment]
Had the same problem here

**Comment by nazarhussain** [comment]
I just doubled checked the keys defined in the release key script are the same defined by [NodeJS team](https://github.com/nodejs/node#release-keys). 

https://github.com/asdf-vm/asdf-nodejs/blob/dd9f0bdb3536e3ef556e5b766d9c5375b8889620/bin/import-release-team-keyring#L8-L18

**Comment by bkaney** [comment]
Hmm. Well, I am glad it's not just me... I don't understand why it works for some. 

One variable is I have https://formulae.brew.sh/cask/gpg-suite installed where the others on my team (where they didn't have a problem) do not... no idea if this is at all related.

**Comment by dklotz** [comment]
I can confirm this is still a problem for me with current asdf-nodejs versions. Even after running `asdf plugin-update nodejs` I still get `Authenticity of checksum file can not be assured! ...`

**Comment by Stratus3D** [comment]
@dklotz did you run `bash -c '${ASDF_DATA_DIR:=$HOME/.asdf}/plugins/nodejs/bin/import-release-team-keyring'`?

**Comment by dklotz** [comment]
@Stratus3D I thought I did, but looking at my shell history I might have only ran it before i did the `asdf plugin-update nodejs`, so maybe this was a false positive. Sorry for the noise, if that's the case. I fixed it for myself in the end by manually importing all the keys mentioned by j0hnm4r5
