### ISSUE TITLE
Can't install LTS version 14.15.0

### ISSUE THREAD

**Issue by repeatdomiau** [asdf-vm/asdf-nodejs#181]
I'm trying to install node's LTS version 14.15.0 without success.

All other versions, newer or older installs ok, except the LTS one.

It gives me that error, but I have updated the PGP keys as described on the project readme:

`Authenticity of checksum file can not be assured! Please be sure to check the README of asdf-nodejs in case you did not yet import the needed PGP keys. If you already did that then that is the point to become SUSPICIOUS! There must be a reason why this is failing. If you are installing an older NodeJS version you might need to import OpenPGP keys of previous release managers. Exiting.`

Do I have to do something differently or is there a problem with the plugin or node's repository?

**Comment by jonchoukroun** [comment]
I solved this by 1) ensuring I had the latest `asdf-nodejs` plugin, 2) importing the _current_ release team keyrings (not a previous version), and 3) calling install again:
```
asdf plugin-update nodejs
~/.asdf/plugins/nodejs/bin/import-release-team-keyring
asdf install nodejs 14.15.0
```
I wonder if executing step 2) as above (rather than with `bash -c` as in the docs) made a difference, since I'm running zsh.

**Comment by repeatdomiau** [comment]
It worked!

I believe you are right, running this: 
`~/.asdf/plugins/nodejs/bin/import-release-team-keyring`
instead of the `bash -c` from the docs seems to make the difference.

Thanks!
