### ISSUE TITLE
Invalid variable name

### ISSUE THREAD

**Issue by KasMA1990** [asdf-vm/asdf-nodejs#186]
I'm using asdf 0.8.0 and have installed the asdf-nodejs plugin and the yarn plugin. When I attempt to run e.g. `asdf install`, I get this error: 

    /home/kasper/.asdf/lib/utils.bash: line 234: ASDF_NODE.JS_VERSION: invalid variable name

I'm not sure if it's causing any trouble, since things appear to work.

OS: Ubuntu 20.04
Shell: GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)

**Comment by Stratus3D** [comment]
@KasMA1990 it looks like you may have included a dot in your plugin name. This results in an invalid variable name of `ASDF_NODE.JS_VERSION`. We should fix this so names with dots are either valid or dots are converted to another character.

**Comment by KasMA1990** [comment]
Indeed, I was installing the plugin with this command: 

    asdf plugin add node.js https://github.com/asdf-vm/asdf-nodejs.git

But using

    asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git

instead fixes it.

Another option would be to validate the name, and tell the user not to use dots.

**Comment by Kaylebor** [comment]
I am having a similar issue, with a slightly different error message:

```/Users/ender/.asdf/lib/utils.bash: line 234: ASDF_.._VERSION: invalid variable name```

This only seems to happen when trying to run any Ruby command (version 3.0.2). It did not happen last week.

**Comment by augustobmoura** [comment]
This is an issue from [`asdf-core`](https://github.com/asdf-vm/asdf), we should get some warnings going on invalid plugin names

**Comment by Stratus3D** [comment]
This has been fixed by https://github.com/asdf-vm/asdf/pull/1010. The `.` character is no longer permitted in plugin names and an error is printed if you try to use it. So you'll need to use `nodejs` for the name of this plugin.

Thanks for all your work on the issue tracker @augustobmoura !
