### ISSUE TITLE
Unable to import gpg keys for node on macOS

### ISSUE THREAD

**Issue by eng618** [asdf-vm/asdf-nodejs#192]
Just set up a new dev Mac and trying to install node, when trying to add the gpg keys I'm getting the following errors.

```
bash -c '${ASDF_DATA_DIR:=$HOME/.asdf}/plugins/nodejs/bin/import-release-team-keyring'

gpg: keybox '/Users/engarcia/.gnupg/asdf-nodejs.gpg' created
gpg: keyserver receive failed: Network is unreachable
gpg: keyserver receive failed: No keyserver available
...
gpg: keyserver receive failed: Network is unreachable
gpg: keyserver receive failed: No keyserver available
```

**Comment by ruprict** [comment]
I had this issue today and created the file `~/.gnupg/dirmngr.conf` and added the following line:

```
standard-resolver
```

And it fixed it for me. Not sure if this needs to be in the docs for asdf-nodejs (or other asdf tools)

**Comment by ENG618** [comment]
@ruprict i ended up doing the same thing and it worked for me as well. Forgot to come back here and post an update.

**Comment by augustobmoura** [comment]
What's the reasoning behind standard-resolver? It's something general from GnuPG or something related to asdf-nodejs?

**Comment by augustobmoura** [comment]
Can you guys send the OSes that showed the problem? Because other similar problems showed up almost at the same time I suspect is a update of some distribution that introduced a incompatible default config, we might want to add this fix to the README

**Comment by ammarnajjar** [comment]
for what it's worth, the solution suggested here (https://github.com/asdf-vm/asdf-nodejs/issues/192#issuecomment-786698681) did not work for me on its own:

```bash
$ echo "standard-resolver" >  ~/.gnupg/dirmngr.conf
```

I had to additionally do:

```bash
sudo pkill dirmngr
```

now keys are found and imported.

I am on:
- macOS Big Sur v11.2.3
- gpg (GnuPG) 2.2.27
- asdf v0.8.0-c6145d0

**Comment by ruprict** [comment]
> Also: can you guys send the OSes that have shown the problem? Because other similar problems showed up almost at the same time I suspect is a update of some distribution that introduced a incompatible default config, we might want to add this fix to the README

I would've been on Mac OS X Catalina 10.15 when I was having the issue.

**Comment by ENG618** [comment]
I'm on MacOS Big Sur 11.2.3

**Comment by otherguy** [comment]
Had to do the same on Big Sur 11.2.1 (20D74)

**Comment by philihp** [comment]
Some of the SKS keyservers in the pool are at times not very reliable. I ran one, once, and the software tends to need to be restarted every few hours, which may have happened here, and hitting the pool again should give people a different server.

```
gpg: keyserver receive failed: Network is unreachable
gpg: keyserver receive failed: No keyserver available
```

Would the project be open to a PR which updates repo to include the keys with it, and the import keyring script import them directly? I'm happy to contribute this if it would be considered; it would remove the reliance on a keyserver.

**Comment by augustobmoura** [comment]
@philihp I don't know if this is related to the keyservers reliability because only now this error is showing up, and only to a narrow number of users. I don't know if we are comfortable with keeping the keys in the project for now, but we will keep this idea in mind

**Comment by Jikodis** [comment]
Can confirm this issue is happening on MacOS Big Sur 11.3.1 (20E241). The `standard-resolver` in dirmngr.conf fixed the issue as well. Interesting to note is that two of my fellow devs were running MacOS Catalina and did not get this error. One of them tried the same same installation process between Big Sur and Catalina, and that provided extra verification that it was indeed a Big Sur specific issue.

I would not have found this Github suggested solution were it not for a fellow dev sending it my way. Searching the error message online brings up a myriad of suggested resolutions that send the dev down a rabbit hole of trying many different potential resolutions that end up not working. Adding this to the readme, docs somewhere, part of the installation, or fixing it in the code base for MacOS Big Sur would save others a lot of trouble.

**Comment by ssunday** [comment]
I was also having this issue on MacOS Big Sur 11.4 (Intel) and the `standard-resolver` did fix it after a few attempts. 

Agree with @Jikodis 💯  that this should be added to the docs or fixed.

**Comment by joshuataylor** [comment]
I believe that this is caused by the keyservers being dead, and removing the dead ones should fix it. https://github.com/asdf-vm/asdf-nodejs/pull/240

**Comment by joschi** [comment]
https://github.com/asdf-vm/asdf-nodejs/issues/192#issuecomment-797448073 solved my issue (using 95a2091f7b64497c002dc709b267f5d03f302498 of `asdf-nodejs`).

```
# asdf info
OS:
Darwin my.machine.example.com 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64

SHELL:
zsh 5.8 (x86_64-apple-darwin20.0)

ASDF VERSION:
v0.8.1

ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=/usr/local/Cellar/asdf/0.8.1_1/libexec

ASDF INSTALLED PLUGINS:
nodejs                       git@github.com:asdf-vm/asdf-nodejs.git
```

**Comment by maco** [comment]
Fetching the keys from Ubuntu's keyserver instead is what worked for me: https://github.com/nodejs/node/issues/39114#issuecomment-906626966

**Comment by MPV** [comment]
Upgrading to the latest `asdf-nodejs` solved this for me today:

```shell
$ asdf install nodejs lts
Installing alias lts as 16.14.0
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4035    0  4035    0     0  28255      0 --:--:-- --:--:-- --:--:-- 30111
gpg: keyserver receive failed: Try again later
^C
gpg: signal Interrupt caught ... exiting

received sigint, cleaning upCould not install version 16.14.0

received sigint, cleaning up%
```
```shell
$ asdf plugin update nodejs
Updating nodejs to master
From https://github.com/asdf-vm/asdf-nodejs
   cb61e3d..ed34355  master     -> master
   cb61e3d..ed34355  master     -> origin/master
Already on 'master'
Your branch is up to date with 'origin/master'.
```
```shell
$ asdf install nodejs lts
Installing alias lts as 16.14.0
Cloning node-build...
node-build: definition not found: 16.14.0
Could not install version 16.14.0
```

**Comment by augustobmoura** [comment]
Yes, asdf-nodejs doesn't rely on keyservers anymore

**Comment by obianaghag** [comment]
This worked for my linux Ubuntu also. Thanks!

**Comment by AndreVirtimo** [comment]
I faced this issue today on my MacBook (M2) with macOS 14.4.1. I have installed gnupg (2.4.5) via homebrew.

This fixed it for me:

> for what it's worth, the solution suggested here ([#192 (comment)](https://github.com/asdf-vm/asdf-nodejs/issues/192#issuecomment-786698681)) did not work for me on its own:
> 
> ```shell
> $ echo "standard-resolver" >  ~/.gnupg/dirmngr.conf
> ```
> 
> I had to additionally do:
> 
> ```shell
> sudo pkill dirmngr
> ```
> 
> now keys are found and imported.
> 
> I am on:
> 
> * macOS Big Sur v11.2.3
> * gpg (GnuPG) 2.2.27
> * asdf v0.8.0-c6145d0
