### ISSUE TITLE
Support slash-based aliases for LTS

### ISSUE THREAD

**Issue by dcalhoun** [asdf-vm/asdf-nodejs#193]
Support for aliases was added in #176, which is great! However, the support [appears to use a dash-based naming convention](https://github.com/asdf-vm/asdf-nodejs/issues/134#issuecomment-764712355), which diverges from nvm's slash-based naming convention.

If possible, it'd be helpful to align to (or at least support) the slash-based naming convention. Doing so would allow...

- [ ] Existing `.nvmrc` files leveraging [LTS aliases](https://github.com/nvm-sh/nvm#long-term-support). E.g. `lts/*`. (#194)
- [ ] Installing LTS aliases via the CLI. E.g. `asdf install nodejs lts/erbium`.

**Comment by augustobmoura** [comment]
The main problem is how the core asdf handles names, it can't use `/` because it needs to be a valid directory name (lts/erbium actually creates a lts dir with a erbium dir inside). I talked about it in https://github.com/asdf-vm/asdf-nodejs/pull/176#issuecomment-702815634, sorry if was not clear in the original comment is a bit hard to describe the problem. I made the suggestion https://github.com/asdf-vm/asdf/issues/352#issuecomment-703691304 in asdf core that should allow nvm style aliases. We can tinker about other ways though

**Comment by dcalhoun** [comment]
@augustobmoura ah, thank you for providing that context. I overlooked that helpful information. It does seem like supporting aliases containing slashes is a bit more involved and potentially related to asdf core.

**Comment by blimmer** [comment]
I wonder if when reading the legacy/.nvmrc file, we could do the conversion there? Then, `asdf` and `asdf-nodejs` could treat the value as `lts-erbium` for its purposes. Basically just a little adapter for their syntax.

Thoughts?

**Comment by augustobmoura** [comment]
Actually... There is a way of supporting .nvmrc files using [the binparse-legacy-file hook](https://asdf-vm.com/#/plugins-create?id=binparse-legacy-file), I didn't see that hook before. `asdf install nodejs lts/erbium` will still not work though

**Comment by augustobmoura** [comment]
I opened the #194 PR to add this translation at legacy file level, tested in my machine and it worked fine. Maybe we can leave the issue open for the `asdf install nodejs lts/erbium` issue. Running `asdf install nodejs`(without the version) in the directory with the .nvmrc file installs the correct version for the project

**Comment by augustobmoura** [comment]
We changed the way aliases work on #348, now you need to explicitly opt-in with dynamic ranges on legacy version files (`.tool-versions` and `.nvmrc`). The `.tool-versions` file doesn't support non-deterministic versions, and supporting it on `.tool-versions` is not a feature we are seeking to implement at the moment.

To enable it, you need to provide an `ASDF_NODEJS_LEGACY_FILE_DYNAMIC_STRATEGY` environment variable choosing between the `latest_available` and `latest_installed` strategies, you can read more about it in the [appropriate section](https://github.com/asdf-vm/asdf-nodejs#partial-and-codename-versions) on the README of the project. To make this choice permanent you can export said variable from your shell rc file like so:

```bash
export ASDF_NODEJS_LEGACY_FILE_DYNAMIC_STRATEGY=latest_installed
# OR
export ASDF_NODEJS_LEGACY_FILE_DYNAMIC_STRATEGY=latest_available
```

Please update the plugin by running `asdf plugin-update nodejs`. If a new issue arises with the new implementation please open a new issue.
