### ISSUE TITLE
Can't import release team keys: No keyserver availabile

### ISSUE THREAD

**Issue by mmorava** [asdf-vm/asdf-nodejs#201]
Hi everyone, I've found a couple of old issue similar to this one, tried all of the previous answers but non of them helped. Whatever I try I am unable to import nodejs team keys. It looks like keyservers which are used to fetch keys are constantly not reachable.

I tried updating asdf, updating nodejs plugin, manually using gpg to import from specific servers. Nothing of that worked so I tried the same but by using different internet connection I even tried it all while connected to VPN but nothing helped.

System I'm using is MacOS BigSur, ZSH

Here is the screenshot of what I did

![image](https://user-images.githubusercontent.com/2305417/106865968-2c729380-66cc-11eb-9737-b7226a6ecf15.png)

As the last resort i went to some of the keyserver websites and tried to use their UI to fetch the keys but it also failed

![image](https://user-images.githubusercontent.com/2305417/106866782-292bd780-66cd-11eb-96ff-04c2e01d1dff.png)

![image](https://user-images.githubusercontent.com/2305417/106866809-32b53f80-66cd-11eb-979b-6cb3c83dfdcd.png)

Does anyone know why this is happening and how to ensure that at least 1 keyserver is always available?

**Possible solution:**

Finally I had a look at what the install script does and found out that NODEJS_CHECK_SIGNATURES is being use for the script to decide should it verify authenticity or not.

That means it should be possible to install nodejs without importing keyring if we run

```bash
NODEJS_CHECK_SIGNATURES=no asdf install nodejs VERSION
```

**Comment by augustobmoura** [comment]
Can you check if is related to #192?

**Comment by mmorava** [comment]
@augustobmoura [this](https://github.com/asdf-vm/asdf-nodejs/issues/192#issuecomment-797448073) answer from that thread helped. I need to create that file + kill dirmngr process in order to make it work.

After doing those steps keys have been imported

**Comment by augustobmoura** [comment]
I will close this issue then, and keep all discussion in #192
