### ISSUE TITLE
TAC: Command not found

### ISSUE THREAD

**Issue by riggtravis** [asdf-vm/asdf-nodejs#202]
Hi, I just cloned from master and am not able to install node.js. I'm about to start looking over the code of the list-all script to see where this TAC command I'm missing is coming from and what I should be doing about it. Just wanted to write up this issue in case anyone else ran into it before I found a solution or in case someone more knowledgable than me can sort it out before I can

```shell
.asdf/plugins/nodejs/bin/list-all: line 14: tac: command not found
```

**Comment by riggtravis** [comment]
I'm dumb. There was an issue with my core-utils install that I'm gonna have to set out on my own to resolve

**Comment by Chralu** [comment]
Hi,

I actually encounter the same error because I didn't installed `core-utils`.

Maybe nodejs plugin should work without `tac` command ?

**Comment by riggtravis** [comment]
> Hi,
> 
> I actually encounter the same error because I didn't installed `core-utils`.
> 
> Maybe nodejs plugin should work without `tac` command ?

I think I'd be more inclined to say leave dependence on `tac` and add a check that gracefully handle's the `tac` command being missing and log a message to stderr that says something like "Hey there friend. You're going to need to install `core-utils`"
