### ISSUE TITLE
Consider using ASDF_DATA_DIR for keyrings

### ISSUE THREAD

**Issue by mook-as** [asdf-vm/asdf-nodejs#205]
Hi there! First, thanks for building / maintaining this.

I'm using homebrew on a mac, and therefore expect that homebrew will update asdf at some point.  Currently, my `ASDF_DIR` is a symlink to `${HOMEBREW_PREFIX}/Cellar/asdf/0.8.0`; this should mean that once asdf gets updated the symlink will point elsewhere (because it won't be 0.8.0 anymore).

Currently, the install script defaults to a dedicated GPG keyring (yay), as per:
https://github.com/asdf-vm/asdf-nodejs/blob/5a46614ec24177146541543d3ec6327e136ae80f/bin/install#L240-L242

However, that defaults to pointing to something in `${ASDF_DIR}`; would it be possible to switch to [`${ASDF_DATA_DIR}`](https://asdf-vm.com/#/core-configuration?id=environment-variables) instead? On a default asdf install, that should be the same thing, but on a more customized setup that can point to persistent storage.  (I'm trying out `~/Library/Application Support` to see how well it works.)  Logically it also seems like a better place (next to the plugin itself).

If you'd prefer, I could send it a fairly trivial PR for approval, too.

**Comment by augustobmoura** [comment]
One problem that may arise is that the people that already have a `ASDF_DATA_DIR` setted will need to reconfigure the keyring directory and reimport the already imported keys. We could try to find a `$ASDF_DATA_DIR/keyrings/nodejs` but it shouldn't take precedence over the `ASDF_DIR` one, for compatibility purposes. Feel free to open a PR

**Comment by seivan** [comment]
@augustobmoura That compatibility will break as soon as new asdf is released.

**Comment by augustobmoura** [comment]
This issue was invalidated because we stopped using keyrings in favor of node-build checksums
