### ISSUE TITLE
Broken pipe error

### ISSUE THREAD

**Issue by lifeiscontent** [asdf-vm/asdf-nodejs#217]
when running `asdf install nodejs 14.15.4` I get this error:

```
/Users/lifeiscontent/.asdf/plugins/nodejs/bin/../lib/utils.sh: line 62: printf: write error: Broken pipe
```

**Comment by augustobmoura** [comment]
I cannot reproduce this error, `asdf install nodejs 14.15.4` is working as usual in my setup

Can you send the bash versions, OS, and interactive shell that you are using? Also can you send the full output of the command? Usually broken pipe means a error with another command that the printf is piping to

**Comment by augustobmoura** [comment]
Looking at the code, could you also send your `awk` implementation and version?

**Comment by lifeiscontent** [comment]
@augustobmoura I've installed `gawk` via `brew install gawk` this is the version info from it:

```
GNU Awk 5.1.0, API: 3.0 (GNU MPFR 4.1.0, GNU MP 6.2.1)
```

**Comment by lifeiscontent** [comment]
based off the function I'm seeing, I'm not sure if this is helpful but using shellcheck there is a warning:

https://github.com/koalaman/shellcheck/wiki/SC2155

seems to be an issue with `filter_version_candidates` or somewhere around that.

I'm using default zsh from latest osx (11.2.3)

zsh 5.8 (x86_64-apple-darwin20.0)

```sh
resolve_version_query() {
  local version_query="$1"

  local canon_version="$(
    # Find the first candidate which the alias match, then print it version
    print_index_tab |
      filter_version_candidates |
      awk -F'\t' -v "alias=$version_query" '$1 == alias { print $2; exit }'
  )"

  if [ -z "$canon_version" ]; then
    echo "$version_query"
  else
    echo "$canon_version"
  fi
}
```

**Comment by Debetux** [comment]
I have the same issue on a new MacBook M1, using zsh & bash :
 
```
➜  ~ zsh --version
zsh 5.8 (arm-apple-darwin20.2.0)
➜  ~ bash --version
GNU bash, version 3.2.57(1)-release (arm64-apple-darwin20)
Copyright (C) 2007 Free Software Foundation, Inc.
➜  ~ awk --version
GNU Awk 5.1.0, API: 3.0 (GNU MPFR 4.1.0, GNU MP 6.2.1)
Copyright (C) 1989, 1991-2020 Free Software Foundation.

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see http://www.gnu.org/licenses/.
➜  ~ sw_vers
ProductName:	macOS
ProductVersion:	11.2.3
BuildVersion:	20D91
➜  ~ asdf install nodejs 14.15.4
/Users/xxxx/.asdf/plugins/nodejs/bin/../lib/utils.sh: line 62: printf: write error: Broken pipe
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3490    0  3490    0     0  37127      0 --:--:-- --:--:-- --:--:-- 37127
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 10860    0 10860    0     0   123k      0 --:--:-- --:--:-- --:--:--  123k
Binary not found for version 14.15.4
```

I'll try to dig a bit if I find some time.

**Comment by Debetux** [comment]
Seems to be related to #189.

I used this as a workaround and it worked :
```
arch -x86_64 asdf install nodejs 14.15.5
```

**Comment by lifeiscontent** [comment]
@Debetux I'm not currently using a Macbook with an M1 Chip so that is unrelated for my issue.

**Comment by augustobmoura** [comment]
@lifeiscontent can you send your bash version?

Also, @Debetux can you try to update your bash with brew and see if the error persists?

The default bash installation in macOS is severely outdated and we had other issues related to that in the past

**Comment by Debetux** [comment]
@augustobmoura Upgrading bash remove the error for me.

```
➜  ~ bash --version
GNU bash, version 5.1.4(1)-release (aarch64-apple-darwin20.2.0)
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
➜  ~ asdf install nodejs 15.12.0
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3835    0  3835    0     0  40368      0 --:--:-- --:--:-- --:--:-- 40368
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 10860    0 10860    0     0   119k      0 --:--:-- --:--:-- --:--:--  117k
Binary not found for version 15.12.0
```

**Comment by augustobmoura** [comment]
he issue is probably that the printf being run at this version of bash doesn't handle broken pipes correctly (it should be something that was patched later in 3.x but the version in the default macOS installation is still broken), there's a nice explanation in https://superuser.com/a/554896. The error is probably harmless and we can just pipe stderr to /dev/null if is bothering too much, we can also try to use other commands instead of printf, like echo or something else. @lifeiscontent can you confirm that even though the error is printed the installation completes successfully?

**Comment by lifeiscontent** [comment]
@augustobmoura I couldn't get the install to successfully complete without the changes I made in my referenced PR

**Comment by lifeiscontent** [comment]
As for the bash update, I'll try it later today when I'm home

**Comment by leejongyoung** [comment]
@Debetux Your solution works on the M1 MacBook

**Comment by lifeiscontent** [comment]
@augustobmoura I realized the installation didn't work because I didn't have GnuPG installed.

**Comment by augustobmoura** [comment]
@lifeiscontent can you check if the error is still occurring in the latest version of asdf-nodejs? I think #219 might have solved it

**Comment by jonatan-ivanov** [comment]
@lifeiscontent It does not seem so on M1 mac:
```
➜  ~ bash --version
GNU bash, version 3.2.57(1)-release (arm64-apple-darwin20)
➜  ~ awk --version   
GNU Awk 5.1.0, API: 3.0 (GNU MPFR 4.1.0, GNU MP 6.2.1)
➜  ~ asdf install nodejs 15.14.0 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3490    0  3490    0     0  35252      0 --:--:-- --:--:-- --:--:-- 35252
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 10855    0 10855    0     0  91218      0 --:--:-- --:--:-- --:--:-- 91218
Binary not found for version 15.14.0
```

**Comment by jonatan-ivanov** [comment]
I'm getting the same issue if I update bash (`brew install bash`) to 5.1.4 (latest).

**Comment by augustobmoura** [comment]
Weird, trying on bash5 on docker doesn't bring this error, can you send the full output of the error @jonatan-ivanov? Maybe there is another error related to this one for macOS

**Comment by jritsema** [comment]
It looks like node v15 natively supports macos aarch64 (m1).  It would be nice if this plugin supported it.

**Comment by jritsema** [comment]
Oops, it looks like the latest version works.  I was able to install `16.2.0`.
