### ISSUE TITLE
Bug with Angular

### ISSUE THREAD

**Issue by d3v0m4r** [asdf-vm/asdf-nodejs#220]
Hi everyone
I install nodejs everything as the documentation says
but when installing angular cli with npm when wanting to use the ng command I get "command not found: ng"
if you could check it please
because with other tools like nvm something like this didn't happen
regards from Bolivia

**Comment by Codex-** [comment]
What happens if you use `npx ng`?

**Comment by d3v0m4r** [comment]
> What happens if you use `npx ng`?

thanks for answering
I don't know what happened but now I uninstalled and reinstalled and now it works fine
