### ISSUE TITLE
Problem with bower

### ISSUE THREAD

**Issue by d3v0m4r** [asdf-vm/asdf-nodejs#225]
when i install bower with:
npm install -g bower
when seeing the version of bower with:
bower --version
Its show:
command not found: bower
In ~/.asdf/shims bower not found
if you could check it please
regards

**Comment by augustobmoura** [comment]
Can you try running `asdf reshim nodejs` after the `npm install` we are currently experiencing some problems with auto reshimming in npm@7

**Comment by d3v0m4r** [comment]
> Can you try running `asdf reshim nodejs` after the `npm install`? we are currently experiencing some problems with auto reshimming in npm@7

This solve the problem, thanks :+1:
