### ISSUE TITLE
Best practices guide for setup of related tooling (npx, yarn, etc.) on macOS?

### ISSUE THREAD

**Issue by jlumbroso** [asdf-vm/asdf-nodejs#234]
Hello,

When learning how to configure `asdf` for Python/macOS, this article was extremely useful:

https://hackercodex.com/guide/python-development-environment-on-mac-osx/

What is important is that it doesn't just explain how to call `asdf install python xxxxx` but also explains how to configure the related tooling (`pip` and virtual environments).

I am wondering if there are any equivalent guides for Node.js: For instance, it seems that currently, `npx` does not play nicely with `asdf` as noted in issue #141. This article is a good start, but only focuses on installation of `node`, not the package managers like `npx` or `yarn`:

https://blog.natterstefan.me/how-to-use-multiple-node-version-with-asdf

**Comment by augustobmoura** [comment]
npx should work out of the box, I think #141 was an issue with npm itself that might be solved in the latest releases, but I will look into it deeper. I also don't see any issues with Yarn at the moment. In any case, they don't work automagically should be understood as an issue within this project.

I don't think there's anything that is not already documented in the README. Do you have any specific questions that I can answer and then put on the README?

If you are talking about explaining how to use the tools (npm, yarn, or npx), I think you are much better served in the official documentation for them.

**Comment by Stratus3D** [comment]
@jlumbroso are you looking for a guide on using asdf for nodejs development with the tools you mentioned? (npx, yarn, etc...)? If so, the best solution is to write one yourself. I am not sure we would be suited to creating a guide since we are maintainers and not representative of the average nodejs/npx/yarn user. If you do decide to write a guide we'd be happy to include it or reference it some way in our existing docs.

**Comment by augustobmoura** [comment]
I will close this because it is not explicitly related to the project. In my opinion, `asdf-nodejs` usage is already well explained in the README, and within the `asdf-core` documentation. Other tools like `npm`, `node` and `yarn` are explained in their official documentation
