### ISSUE TITLE
Can't install nodejs 8.x.x on mac m1

### ISSUE THREAD

**Issue by chessl** [asdf-vm/asdf-nodejs#236]
I was able to successfully install nodejs 16.x.x but any `arch -x86_64 asdf install nodejs 8.x.x` gave me `Binary not found for version 8.x.x`. Tried both `~/.asdf/plugins/nodejs/bin/import-previous-release-team-keyring` and `~/.asdf/plugins/nodejs/bin/import-release-team-keyring` but didn't help.

<img width="566" alt="screenshot" src="https://user-images.githubusercontent.com/4500005/120774384-d0722b80-c554-11eb-906b-139f095059b6.png">

**Comment by chessl** [comment]
In fact, any version other than 16.x.x return the same error.

**Comment by a4z** [comment]
There is already this ticket addressing that. https://github.com/asdf-vm/asdf-nodejs/issues/189

Let's hope that will be solved for some version, now where at least a version 16 is available to download,
hopefully there will also be a 14 LTS soon to download, and then, that this gets added to the plugin

**Comment by chessl** [comment]
Actually it turned out to be a compatibility issue with `coreutils` in my case, I'm guessing `gnu-uname` gave the wrong arch or os info.
