### ISSUE TITLE
CLI output about GnuPG is vage

### ISSUE THREAD

**Issue by glenpike** [asdf-vm/asdf-nodejs#239]
Trying to install a version of Node and I get the output: `You should install GnuPG to verify the authenticity of the downloaded archives`

This needs to be more explicit that install won't work withoutu GnuPG setup if the default plugin settings are used.

Suggest replace 'should' with 'must' and/or add a note about configuration

**Comment by Stratus3D** [comment]
This has already been fixed by https://github.com/asdf-vm/asdf-nodejs/pull/230. Please update to the latest version for the fix. `asdf plugin-update nodejs`
