### ISSUE TITLE
How can I use with PM2?

### ISSUE THREAD

**Issue by LorhanSohaky** [asdf-vm/asdf-nodejs#242]
I tried run `pm2 start ecosystem.config.js` and the output it's 

```sh
[PM2][ERROR] Error: Interpreter node@12.16.0 is NOT AVAILABLE in PATH. (type 'which node@12.16.0' to double check.)
[PM2][ERROR] NVM is not available in PATH
[PM2][ERROR] Fallback to node in PATH
[PM2][ERROR] Install NVM:
$ curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
``

**Comment by Stratus3D** [comment]
Did you run `asdf reshim` after installing everything?

**Comment by LorhanSohaky** [comment]
Yes!

**Comment by Stratus3D** [comment]
Can you provide the steps you took to setup everything prior to encountering this issue?

> [PM2][ERROR] Error: Interpreter node@12.16.0 is NOT AVAILABLE in PATH. (type 'which node@12.16.0' to double check.)

It looks like this program isn't finding node on your path. This either means the asdf shim directory is not getting added to your path, or no nodejs version is set for the directory that this program is running from.

**Comment by LorhanSohaky** [comment]
1. I install https://aur.archlinux.org/packages/asdf-vm
2. asdf plugin add nodejs
3. Node installation
```sh
whereis node
node: /usr/bin/node /usr/include/node /home/my_user/.asdf/shims/node /usr/share/man/man1/node.1.gz
```
4. Node version
```sh
node --version
v12.22.1
```
5. Install pm2
6. Create `ecosystem.config.js` file
```js
module.exports = {
  apps: [
    {
      name: 'admin',
      script: 'out/admin-main.js',
      watch: ['out/admin-main.js'],
      env: {
        NODE_ENV: 'development',
      },
      env_production: {
        NODE_ENV: 'production',
      },
      interpreter: 'node@12.22.1',
    },
  ],
}
```
7. `pm2 start ecosystem.config.js`

**Comment by augustobmoura** [comment]
It seems like the [`interpreter` field should be the absolute path of the executable file](https://pm2.keymetrics.io/docs/usage/application-declaration/#general) (or command name, I assume).

For overriding the node version being used (instead of using the global one), you can use the [asdf-core env variable `ASDF_NODEJS_VERSION`](https://asdf-vm.com/#/core-manage-versions?id=set-current-version), or execute configure pm2 to start in a directory with a valid `.tool-versions` file (the `cwd` field in the pm2 configuration file).

Try using this configuration:
``` js
module.exports = {
  apps: [
    {
      name: 'admin',
      script: 'out/admin-main.js',
      watch: ['out/admin-main.js'],
      env: {
        NODE_ENV: 'development',
        ASDF_NODEJS_VERSION: '12.22.1',
      },
      env_production: {
        NODE_ENV: 'production',
      },
      interpreter: 'node',
    },
  ],
}
```

**Comment by LorhanSohaky** [comment]
Thanks!!! That work for me

**Comment by Kochiyama** [comment]
I was having the same problem, but just when I wanted to use pm2 installed with node v20.0.0 (for example) inside a project that was using another version.

The workarround was creating an alias on zsh to match pm2 to the real binary file.

~/.zshrc
```bash
...
alias pm2="~/.asdf/installs/nodejs/20.6.1/bin/pm2"
...
```

Now I can use pm2 inside any project with any version of node being used.
