### ISSUE TITLE
Do not set NPM_CONFIG_PREFIX

### ISSUE THREAD

**Issue by mpern** [asdf-vm/asdf-nodejs#245]
Maybe it's just me, but I would prefer if the asdf-managed node.js does not change the default location for global node modules.

It took me a while to figure out why `yarn` and `npm` couldn't find the same global packages. It's because of the `NPM_CONFIG_PREFIX` injected by asdf-nodejs.

I propose to use the output of `npm root -g` instead of injecting non-standard defaults.

**Comment by mpern** [comment]
Related to #224, #22

**Comment by augustobmoura** [comment]
There's #228 for this exact problem. I'm kinda busy these last months, but I will try to make it spin again. My greatest concern is that removing the `.bin` prefix might break something in an unpredictable way

You (or anyone else interested) are free to try the branch and send any feedback.
