### ISSUE TITLE
NPM reshim broken

### ISSUE THREAD

**Issue by lopenchi** [asdf-vm/asdf-nodejs#248]
The commits uploaded on Jul 19, 2021 have introduced a bug for **npm**

![image](https://user-images.githubusercontent.com/12633126/126566312-44a79987-00d3-46d8-ad84-dabb7988d716.png)

The NPM executable is not working properly, when NPM commands are executed, it seems like the command is not doing anything. 
Analyzing the shim exec command, it was discovered that it creates a loop, calling itself :loop:

**Comment by augustobmoura** [comment]
Can you edit the file at `asdf which npm` and edit line 3 from `set -eu` to `set -eux`? Like this:
![image](https://user-images.githubusercontent.com/5845160/126566870-2e1a406d-2881-445e-b7b7-8addd4aaf09b.png)

And then run `npm --version | head -n 50` and send what was printed on the terminal?

**Comment by augustobmoura** [comment]
Also, please send your OS information, bash and interactive shell version

**Comment by lopenchi** [comment]
Result of the command `npm --version | head -n 50`: 

![Screenshot from 2021-07-21 17-34-08](https://user-images.githubusercontent.com/12633126/126568524-3ac408fc-6f58-430e-9f85-b7ab7f03984d.png)

[terminal result.txt](https://github.com/asdf-vm/asdf-nodejs/files/6859132/terminal.result.txt)

**Comment by lopenchi** [comment]
> Also, please send your OS information, bash and interactive shell version

- Docker: image: debian:9
- bash: 4.4.12(1)
- GNU bash, version 4.4.12(1)-release (x86_64-pc-linux-gnu)

**Comment by augustobmoura** [comment]
Ok, I think I got it, but it will probably need a bit more debugging. `asdf-core` should have removed `/root/.asdf/shims` from `$PATH` (specifically at this line here https://github.com/asdf-vm/asdf/blob/ccf76dd7e60de8a3de03cd3574f570dc1f9dbc55/lib/utils.bash#L750)

But I don't think this is happening in your case. Can you edit your `/root/.asdf/lib/utils.bash` file and add `set -x` at the start of the `run_within_env` function (line 746), and add `set +x` at the end of the function, then run `npm --version | head -n 50` again?

It should look like this:
![image](https://user-images.githubusercontent.com/5845160/126569556-d793cb28-5124-476a-966b-546248b37547.png)

**Comment by lopenchi** [comment]
[terminal result2.txt](https://github.com/asdf-vm/asdf-nodejs/files/6859180/terminal.result2.txt)

**Comment by augustobmoura** [comment]
It's possible for you to send me a reproducible Dockerfile with the issue? I think I might need to debug it more

**Comment by lopenchi** [comment]
@augustobmoura the error happens in circle ci machine. Does it work for you if I send you the config.yml ?

**Comment by augustobmoura** [comment]
Probably yes
Also, check if you are using the latest version for asdf-core v0.8.1

**Comment by lopenchi** [comment]
[config.txt](https://github.com/asdf-vm/asdf-nodejs/files/6859233/config.txt)
This file extension must be .yml  but i cant upload these type of files. 

>Also, check if you are using the latest version for asdf-core v0.8.1
Yes, we are using last version

**Comment by augustobmoura** [comment]
Can you send me the contents of this script file? `./bin/asdf-install`

**Comment by lopenchi** [comment]
```
#!/usr/bin/env bash
PHP_CONFIGURE_OPTIONS="
	--with-pdo-pgsql \
	--with-openssl \
	--with-curl \
	--with-zlib \
    --with-zip \
	--with-readline \
	--with-gettext \
	--with-jpeg-dir=/usr/lib/x86_64-linux-gnu/libjpeg.so.62 \
	--with-png-dir=/usr/lib/x86_64-linux-gnu/libpng.so
" asdf install

```

**Comment by augustobmoura** [comment]
Can you point me to which step `npm` fails in the yaml?

**Comment by lopenchi** [comment]
```
 run:
          name: Installing Node.js dependencies
          command: npm install
```

**Comment by augustobmoura** [comment]
I couldn't reproduce the issue just by trying to mimic Travis in a docker container. Can you change this `npm install` step to `which npm; asdf which npm; asdf list nodejs` and send me the output?

**Comment by lopenchi** [comment]
Results: 
![image](https://user-images.githubusercontent.com/12633126/126575684-d1b3897a-6cf0-44a1-a4b4-e8952eccb0a5.png)


Just to let you know 
- If I run `~/.asdf/installs/nodejs/14.15.4/bin/npm --version` it works
- If I run `npm --version` error

**Comment by augustobmoura** [comment]
`~/.asdf/installs/nodejs/14.15.4/bin/npm --version` should work but it doesn't auto reshim on npm global installs

So, last sanity checks (probably)

You can revert those `set -x` and `set +x` that we put on code. Just running `git reset HEAD --hard` at `~/.asdf` and `~/.asdf/plugins/nodejs` should work

Then I want to you to add `echo exec: "$PATH" && export PATH` to `~/.asdf/lib/commands/command-exec.bash` after line 28, just before `exec "$executable_path"`, like this:

![image](https://user-images.githubusercontent.com/5845160/126577788-04972d2a-6b95-44f2-b8de-0e65543ea140.png)

Then add `echo shim: "$PATH"` at the start of `~/.asdf/plugins/nodejs/shims/npm`, like this:

![image](https://user-images.githubusercontent.com/5845160/126578214-7878b7a8-2c53-48cb-a9fc-664da8ef17cd.png)

Finally, run `npm --version | head -n 10` now and send me the output

**Comment by lopenchi** [comment]
[terminal result3.txt](https://github.com/asdf-vm/asdf-nodejs/files/6859506/terminal.result3.txt)

**Comment by augustobmoura** [comment]
I think this is a problem with Circle CI and the BASH_ENV variable. It's probably resetting the PATH variable every time bash is called. Can you send the output of `cat $BASH_ENV`?

**Comment by lopenchi** [comment]
`export PATH=~/.asdf/shims:~/.asdf/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
`

**Comment by augustobmoura** [comment]
Yeah, there's it

In the Circle CI config PATH is being expanded on the command run, instead of everytime $BASH_ENV is run.

Try changing the double quotes in the `Setting up PATH variable` step for single quotes and swapping the PATH order. Also add some quotations for the variable expansion inside the single quotes

``` diff
   install_tools:
     description: "Install asdf, plugins and composer"
     steps:
       - run:
           name: Setting up PATH variable
-          command: echo "export PATH=~/.asdf/shims:~/.asdf/bin:$PATH" >> $BASH_ENV
+          command: echo 'export PATH="$PATH:~/.asdf/shims:~/.asdf/bin"' >> $BASH_ENV
       - run:
           name: Installing asdf plugins
```

Check if this solves the issue please

**Comment by lopenchi** [comment]
Thanks @augustobmoura for your help! That change solved the issue

**Comment by augustobmoura** [comment]
Also, while we are at it, I would advise removing the line `~/.asdf/plugins/nodejs/bin/import-release-team-keyring` from the Circle CI config. It's not really necessary since #209, and I plan to move the file in the future. Having the absolute path hardcoded will make it easy to break

**Comment by augustobmoura** [comment]
I will also try to make a PR to prevent this recursion behavior in the future, at least break early instead of running undefinately
