### ISSUE TITLE
Error installing the lts version

### ISSUE THREAD

**Issue by gui1612** [asdf-vm/asdf-nodejs#249]
### Describe the Bug

The lts alias doesn't seem to be redirecting to the right path. I can proceed with installing `nodejs latest` and also typing manually the lts version (`asdf install nodejs 14.17.3`), however when I try to install lts from the alias I get the error:
`Installing alias lts as 14.17.3`
`bash: /home/$USER/.asdf/plugins/../bin/install: No such file or directory`
`Could not install version 14.17.3`

You can check the error in [here](https://i.stack.imgur.com/h65Qs.png).

### Steps to Reproduce

1. ``asdf plugin-add nodejs``
2. ``asdf install nodejs lts``

### Expected Behaviour

This should start the install process

### Actual Behaviour

`Installing alias lts as 14.17.3`
`bash: /home/$USER/.asdf/plugins/../bin/install: No such file or directory`
`Could not install version 14.17.3`

### Environment

```shell
OS:
Linux pcgui 5.13.4-arch1-1 #1 SMP PREEMPT Tue, 20 Jul 2021 16:58:51 +0000 x86_64 GNU/Linux

SHELL:
zsh 5.8 (x86_64-pc-linux-gnu)

ASDF VERSION:
v0.8.1-a1ef92a

ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=/home/gui1612/.asdf

ASDF INSTALLED PLUGINS:
nodejs                       https://github.com/asdf-vm/asdf-nodejs.git
```

**Comment by Stratus3D** [comment]
@gui1612 thank you for reporting. I was able to reproduce this on my machine and it's definitely a bug. I also noticed that `asdf list-all nodejs` doesn't return all nodejs versions. Both these issues will need to be fixed. I'll try to look into this later today. FYI @augustobmoura

**Comment by augustobmoura** [comment]
It seems like `plugin_name` is returning `..` in some cases, might be the change from `dirname $0` to `dirname ${BASH_SOURCE[0]}`

**Comment by gui1612** [comment]
> @gui1612 thank you for reporting. I was able to reproduce this on my machine and it's definitely a bug. I also noticed that `asdf list-all nodejs` doesn't return all nodejs versions. Both these issues will need to be fixed. I'll try to look into this later today. FYI @augustobmoura

The first issue seems to be solved. 
Related to that one where ``asdf list-all nodejs``  doesn't return all nodejs versions it doesn't seem to be directly related to the plugin itself, but to ``${ASDF_DIR}/lib/commands/command-list-all.bash``

**Comment by gui1612** [comment]
In the version I was using, simply doing this would also solve fix that list-all bug:
```diff
- versions=$(bash "${plugin_path}/bin/list-all")
+ versions=$(cd "${plugin_path}/bin/"; bash ./list-all)
```
As you can check in [here](https://imgur.com/a/ZqovyT3)
I've noticed, however, that the source code has been changed in some newer commits.

**Comment by Stratus3D** [comment]
> > @gui1612 thank you for reporting. I was able to reproduce this on my machine and it's definitely a bug. I also noticed that `asdf list-all nodejs` doesn't return all nodejs versions. Both these issues will need to be fixed. I'll try to look into this later today. FYI @augustobmoura
> 
> The first issue seems to be solved.
> Related to that one where `asdf list-all nodejs` doesn't return all nodejs versions it doesn't seem to be directly related to the plugin itself, but to `${ASDF_DIR}/lib/commands/command-list-all.bash` (it is still not working with the latest version)

It specifically caused by the plugin's `list-all` callback because I can invoke it directly and get incorrect output:

```
$ ./bin/list-all
lts-fermium lts 15.0.0 15.0.1 15.1.0 15.2.0 15.2.1 15.3.0 15.4.0 15.5.0 15.5.1 15.6.0 15.7.0 15.8.0 15.9.0 15.10.0 15.11.0 15.12.0 15.13.0 15.14.0 16.0.0 16.1.0 16.2.0 16.3.0 16.4.0 16.4.1 16.4.2 16.5.0
```

@augustobmoura not sure when this issue was introduced but we need to get this fixed. Do you want me to create a separate ticket for this? I don't see any other issues reporting it.

**Comment by gui1612** [comment]
> > > @gui1612 thank you for reporting. I was able to reproduce this on my machine and it's definitely a bug. I also noticed that `asdf list-all nodejs` doesn't return all nodejs versions. Both these issues will need to be fixed. I'll try to look into this later today. FYI @augustobmoura
> > 
> > 
> > The first issue seems to be solved.
> > Related to that one where `asdf list-all nodejs` doesn't return all nodejs versions it doesn't seem to be directly related to the plugin itself, but to `${ASDF_DIR}/lib/commands/command-list-all.bash` (it is still not working with the latest version)
> 
> It is caused by this plugin's `list-all` callback because I can invoke it directly and get incorrect output:
> 
> ```
> $ ./bin/list-all
> lts-fermium lts 15.0.0 15.0.1 15.1.0 15.2.0 15.2.1 15.3.0 15.4.0 15.5.0 15.5.1 15.6.0 15.7.0 15.8.0 15.9.0 15.10.0 15.11.0 15.12.0 15.13.0 15.14.0 16.0.0 16.1.0 16.2.0 16.3.0 16.4.0 16.4.1 16.4.2 16.5.0
> ```
> 
> @augustobmoura not sure when this issue was introduced but we need to get this fixed. Do you want me to create a separate ticket for this? I don't see any other issues reporting it.

That's weird, since doing exactly the same thing I get the expected output:

```
❯ ./bin/list-all
0.1.14 0.1.15 0.1.16 0.1.17 0.1.18 0.1.19 0.1.20 0.1.21 0.1.22 0.1.23 0.1.24 0.1.25 0.1.26 0.1.27 0.1.28 0.1.29 0.1.30 0.1.31 0.1.32 0.1.33 0.1.90 0.1.91 0.1.92 0.1.93 0.1.94 0.1.95 0.1.96 0.1.97 0.1.98 0.1.99 0.1.100 0.1.101 0.1.102 0.1.103 0.1.104 0.2.0 0.2.1 0.2.2 0.2.3 0.2.4 0.2.5 0.2.6 0.3.0 0.3.1 0.3.2 0.3.3 0.3.4 0.3.5 0.3.6 0.3.7 0.3.8 0.4.0 0.4.1 0.4.2 0.4.3 0.4.4 0.4.5 0.4.6 0.4.7 0.4.8 0.4.9 0.4.10 0.4.11 0.4.12 0.5.0 0.5.1 0.5.2 0.5.3 0.5.4 0.5.5 0.5.6 0.5.7 0.5.8 0.5.9 0.5.10 0.6.0 0.6.1 0.6.2 0.6.3 0.6.4 0.6.5 0.6.6 0.6.7 0.6.8 0.6.9 0.6.10 0.6.11 0.6.12 0.6.13 0.6.14 0.6.15 0.6.16 0.6.17 0.6.18 0.6.19 0.6.20 0.6.21 0.7.0 0.7.1 0.7.2 0.7.3 0.7.4 0.7.5 0.7.6 0.7.7 0.7.8 0.7.9 0.7.10 0.7.11 0.7.12 0.8.0 0.8.1 0.8.2 0.8.3 0.8.4 0.8.5 0.8.6 0.8.7 0.8.8 0.8.9 0.8.10 0.8.11 0.8.12 0.8.13 0.8.14 0.8.15 0.8.16 0.8.17 0.8.18 0.8.19 0.8.20 0.8.21 0.8.22 0.8.23 0.8.24 0.8.25 0.8.26 0.8.27 0.8.28 0.9.0 0.9.1 0.9.2 0.9.3 0.9.4 0.9.5 0.9.6 0.9.7 0.9.8 0.9.9 0.9.10 0.9.11 0.9.12 0.10.0 0.10.1 0.10.2 0.10.3 0.10.4 0.10.5 0.10.6 0.10.7 0.10.8 0.10.9 0.10.10 0.10.11 0.10.12 0.10.13 0.10.14 0.10.15 0.10.16 0.10.17 0.10.18 0.10.19 0.10.20 0.10.21 0.10.22 0.10.23 0.10.24 0.10.25 0.10.26 0.10.27 0.10.28 0.10.29 0.10.30 0.10.31 0.10.32 0.10.33 0.10.34 0.10.35 0.10.36 0.10.37 0.10.38 0.10.39 0.10.40 0.10.41 0.10.42 0.10.43 0.10.44 0.10.45 0.10.46 0.10.47 0.10.48 0.11.0 0.11.1 0.11.2 0.11.3 0.11.4 0.11.5 0.11.6 0.11.7 0.11.8 0.11.9 0.11.10 0.11.11 0.11.12 0.11.13 0.11.14 0.11.15 0.11.16 0.12.0 0.12.1 0.12.2 0.12.3 0.12.4 0.12.5 0.12.6 0.12.7 0.12.8 0.12.9 0.12.10 0.12.11 0.12.12 0.12.13 0.12.14 0.12.15 0.12.16 0.12.17 0.12.18 4.0.0 4.1.0 4.1.1 4.1.2 4.2.0 4.2.1 4.2.2 4.2.3 4.2.4 4.2.5 4.2.6 4.3.0 4.3.1 4.3.2 4.4.0 4.4.1 4.4.2 4.4.3 4.4.4 4.4.5 4.4.6 4.4.7 4.5.0 4.6.0 4.6.1 4.6.2 4.7.0 4.7.1 4.7.2 4.7.3 4.8.0 4.8.1 4.8.2 4.8.3 4.8.4 4.8.5 4.8.6 4.8.7 4.9.0 4.9.1 lts-argon 5.0.0 5.1.0 5.1.1 5.2.0 5.3.0 5.4.0 5.4.1 5.5.0 5.6.0 5.7.0 5.7.1 5.8.0 5.9.0 5.9.1 5.10.0 5.10.1 5.11.0 5.11.1 5.12.0 6.0.0 6.1.0 6.2.0 6.2.1 6.2.2 6.3.0 6.3.1 6.4.0 6.5.0 6.6.0 6.7.0 6.8.0 6.8.1 6.9.0 6.9.1 6.9.2 6.9.3 6.9.4 6.9.5 6.10.0 6.10.1 6.10.2 6.10.3 6.11.0 6.11.1 6.11.2 6.11.3 6.11.4 6.11.5 6.12.0 6.12.1 6.12.2 6.12.3 6.13.0 6.13.1 6.14.0 6.14.1 6.14.2 6.14.3 6.14.4 6.15.0 6.15.1 6.16.0 6.17.0 6.17.1 lts-boron 7.0.0 7.1.0 7.2.0 7.2.1 7.3.0 7.4.0 7.5.0 7.6.0 7.7.0 7.7.1 7.7.2 7.7.3 7.7.4 7.8.0 7.9.0 7.10.0 7.10.1 8.0.0 8.1.0 8.1.1 8.1.2 8.1.3 8.1.4 8.2.0 8.2.1 8.3.0 8.4.0 8.5.0 8.6.0 8.7.0 8.8.0 8.8.1 8.9.0 8.9.1 8.9.2 8.9.3 8.9.4 8.10.0 8.11.0 8.11.1 8.11.2 8.11.3 8.11.4 8.12.0 8.13.0 8.14.0 8.14.1 8.15.0 8.15.1 8.16.0 8.16.1 8.16.2 8.17.0 lts-carbon 9.0.0 9.1.0 9.2.0 9.2.1 9.3.0 9.4.0 9.5.0 9.6.0 9.6.1 9.7.0 9.7.1 9.8.0 9.9.0 9.10.0 9.10.1 9.11.0 9.11.1 9.11.2 10.0.0 10.1.0 10.2.0 10.2.1 10.3.0 10.4.0 10.4.1 10.5.0 10.6.0 10.7.0 10.8.0 10.9.0 10.10.0 10.11.0 10.12.0 10.13.0 10.14.0 10.14.1 10.14.2 10.15.0 10.15.1 10.15.2 10.15.3 10.16.0 10.16.1 10.16.2 10.16.3 10.17.0 10.18.0 10.18.1 10.19.0 10.20.0 10.20.1 10.21.0 10.22.0 10.22.1 10.23.0 10.23.1 10.23.2 10.23.3 10.24.0 10.24.1 lts-dubnium 11.0.0 11.1.0 11.2.0 11.3.0 11.4.0 11.5.0 11.6.0 11.7.0 11.8.0 11.9.0 11.10.0 11.10.1 11.11.0 11.12.0 11.13.0 11.14.0 11.15.0 12.0.0 12.1.0 12.2.0 12.3.0 12.3.1 12.4.0 12.5.0 12.6.0 12.7.0 12.8.0 12.8.1 12.9.0 12.9.1 12.10.0 12.11.0 12.11.1 12.12.0 12.13.0 12.13.1 12.14.0 12.14.1 12.15.0 12.16.0 12.16.1 12.16.2 12.16.3 12.17.0 12.18.0 12.18.1 12.18.2 12.18.3 12.18.4 12.19.0 12.19.1 12.20.0 12.20.1 12.20.2 12.21.0 12.22.0 12.22.1 12.22.2 12.22.3 lts-erbium 13.0.0 13.0.1 13.1.0 13.2.0 13.3.0 13.4.0 13.5.0 13.6.0 13.7.0 13.8.0 13.9.0 13.10.0 13.10.1 13.11.0 13.12.0 13.13.0 13.14.0 14.0.0 14.1.0 14.2.0 14.3.0 14.4.0 14.5.0 14.6.0 14.7.0 14.8.0 14.9.0 14.10.0 14.10.1 14.11.0 14.12.0 14.13.0 14.13.1 14.14.0 14.15.0 14.15.1 14.15.2 14.15.3 14.15.4 14.15.5 14.16.0 14.16.1 14.17.0 14.17.1 14.17.2 14.17.3 lts-fermium lts 15.0.0 15.0.1 15.1.0 15.2.0 15.2.1 15.3.0 15.4.0 15.5.0 15.5.1 15.6.0 15.7.0 15.8.0 15.9.0 15.10.0 15.11.0 15.12.0 15.13.0 15.14.0 16.0.0 16.1.0 16.2.0 16.3.0 16.4.0 16.4.1 16.4.2 16.5.0
```

**Comment by augustobmoura** [comment]
This is probably a cached faulty result, @Stratus3D try deleting `$ASDF_DIR/tmp/nodejs/cache` and then running the list-all again

**Comment by Stratus3D** [comment]
```
$ rm -rf ~/.asdf/tmp/nodejs/      
$ ./bin/list-all            
lts-fermium lts 15.0.0 15.0.1 15.1.0 15.2.0 15.2.1 15.3.0 15.4.0 15.5.0 15.5.1 15.6.0 15.7.0 15.8.0 15.9.0 15.10.0 15.11.0 15.12.0 15.13.0 15.14.0 16.0.0 16.1.0 16.2.0 16.3.0 16.4.0 16.4.1 16.4.2 16.5.0
```

It doesn't seem to be related to the caching.
