### ISSUE TITLE
No npm executable found in CircleCI

### ISSUE THREAD

**Issue by mixedCase** [asdf-vm/asdf-nodejs#250]
Running npm in CircleCI fails with master (e2d0822f05fb61397080bda688b02812cc4ef04f atm). Pinning the plugin to commit ea133489c676e60300d4f9c35319d1f3405b13b2 makes it work again.

I'm using asdf v0.8.1, here's the output:

```
> #!/bin/bash -eo pipefail
> npm ci
/home/circleci/.asdf/lib/utils.bash: line 742: /usr/bin/sed: Argument list too long
No npm executable found for nodejs 14.15.5

Exited with code exit status 2
CircleCI received exit code 2
```

**Comment by augustobmoura** [comment]
Can you share the steps to reproduce this error? I couldn't reproduce it locally

Also, check if it has something to do with #248

**Comment by mixedCase** [comment]
Step 1
```
git clone https://github.com/asdf-vm/asdf.git ~/.asdf
cd ~/.asdf
git checkout "$(git describe --abbrev=0 --tags)"
echo 'source ~/.asdf/asdf.sh' >> $BASH_ENV
source ~/.asdf/asdf.sh
asdf version
```
Step 2
```
asdf plugin-add nodejs
# other plug-ins
```
Step 3
```
cd ~/repo
asdf install
```
Step 4
```
npm ci
```

I get the error in step 4.

Bears repeating that I'm pinning asdf to v0.8.1 in step 1, since it's the current latest tag.

I've successfuly worked around the issue by pinning the plug-in in step 2 to a known-good commit by adding:

```
cd ~/.asdf/plugins/nodejs
git checkout ea133489c676e60300d4f9c35319d1f3405b13b2
```

I didn't do a proper bisection, I merely picked that commit as my first guess since it's the last commit before some recent npm reshim work which I believe may be where the underlying issue lies.

FWIW the entire pipeline runs in [cimg/base:stable](https://hub.docker.com/r/cimg/base) (which is Ubuntu-based).

**Comment by augustobmoura** [comment]
`$BASH_ENV` is a CircleCI only feature. I did the steps on a cimg docker image (without the BASH_ENV step) and still couldn't reproduce the error

Can you share the contents of your `$BASH_ENV` file at step 4? Check if anything is overriding the PATH instead of adding to it, or any other

**Comment by mixedCase** [comment]
The only thing in BASH_ENV is `source ~/.asdf/asdf.sh`.
This is my PATH: 
```
/home/circleci/.asdf/shims:/home/circleci/.asdf/bin:/home/circleci/bin:/home/circleci/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

**Comment by relaxdiego** [comment]
We're also experiencing this problem in our repos. After doing a manual bisect, it looks like this was introduced in this commit: 4d9196d feat(shims): implement new wrapper strategy.

**Comment by augustobmoura** [comment]
@relaxdiego can you share and reproducible image of this error? You are also using CircleCI?

**Comment by relaxdiego** [comment]
@augustobmoura sure thing! Here's a minimal reproducer: https://github.com/relaxdiego/asdf-nodejs-bug-250 and here's the sample run: https://app.circleci.com/pipelines/github/relaxdiego/asdf-nodejs-bug-250/1/workflows/93f24af7-47c8-4619-9486-80b8d86542d1/jobs/1

**Comment by augustobmoura** [comment]
It should be working on master now

@relaxdiego, @mixedCase can you guys check if the issue is solved?

**Comment by relaxdiego** [comment]
Confirmed working as per [latest Circle CI run](https://app.circleci.com/pipelines/github/relaxdiego/asdf-nodejs-bug-250?branch=main).
