### ISSUE TITLE
Can't install nodejs, fresh install Mac OS 11.13.1

### ISSUE THREAD

**Issue by chrisdmacrae** [asdf-vm/asdf-nodejs#253]
I am using `asdf` `0.8.1` and `asdf-nodejs` latest as of Aug 9, 2021.

I am getting the error below when trying to run any of the following:

```
asdf install nodejs latest
asdf install nodejs 14.17.4
asdf install nodejs 16.6.1
```

```
node-v16.6.1-darwin-x64.tar.gz: OK
Unknown command: `asdf reshim nodejs 16.6.1`
/usr/local/Cellar/asdf/0.8.1_1/libexec/bin/asdf: line 82: /Users/REDACTED/.asdf/lib/commands/command-help.bash: No such file or directory
version 16.6.1 is not installed for nodejs
```

`asdf reshim nodejs 16.6.1` called outside of the install returns no errors.

I can install any other library (i.e, ruby, golang) with asdf.

**Comment by thestephenmarshall** [comment]
Confirmed the same issue using the latest as well just now.

**Comment by augustobmoura** [comment]
Check if is related to the new version of the homebrew recipe (https://github.com/asdf-vm/asdf/pull/1020), the [docs from `asdf-core` have been updated](https://asdf-vm.com/guide/getting-started.html) to reflect the new way of importing it.

Basically you will need to change `. "$(brew --prefix asdf)/asdf.sh"` to `. "$(brew --prefix asdf)/libexec/asdf.sh"` in your `.bash_profile`, `.bashrc`, `.zshrc`

**Comment by thestephenmarshall** [comment]
In fact, it was! Thank you!

**Comment by augustobmoura** [comment]
@christhekeele, just confirm if it's also your case, and then we can close the issue

**Comment by christhekeele** [comment]
@augustobmoura I suspect you meant to tag @chrisdmacrae  🙂

**Comment by augustobmoura** [comment]
Yeah, sorry haha
Github mentions autocomplete failed on me

**Comment by chrisdmacrae** [comment]
That fixed it gents and ladies. Closing.

**Comment by adamsiem** [comment]
> Unknown command: `asdf reshim nodejs 16.6.1`

Using ZSH / Oh My ZSH? Add 'asdf' to your list of plugins in ~/.zshrc
