### ISSUE TITLE
Need install cases for SunOS (Solaris)

### ISSUE THREAD

**Issue by mehayden** [asdf-vm/asdf-nodejs#26]
The SunOS operating_system and cpu_type is not detected in the functions:
	os_based_configure_options(),
	get_download_file_path(),
	get_download_url()
	
A match on substring "SunOS" from "uname -a" could be used to detect the operating system and "isainfo-b" could be used to get "64" or "32" to match on.
	
Also, it appears the operating_system variable is never initialized in get_download_file_path().

Here is a diff of a version which worked for me against master 2/16/17, although some refactoring  to remove duplicate code seems warranted if more architectures are to be added:

```
$ diff install.ORIG install
67a68,77
>
>   elif [[ "$operating_system" =~ "SunOS" ]]; then
>     # reset cpu_type based on isainfo
>     local bits=$(isainfo -b)
>     if [[ "$bits" =~ "64" ]]; then
>       local cpu_type="x64"
>     else
>       local cpu_type="x86"
>     fi
>
90a101
>   local operating_system=$(uname -a)
101a113,123
>
>     elif [[ "$operating_system" =~ "SunOS" ]]; then
>       # reset cpu_type based on isainfo
>       local bits=$(isainfo -b)
>       if [[ "$bits" =~ "64" ]]; then
>         cpu_type="x64"
>       else
>         cpu_type="x86"
>       fi
>       local pkg_name="node-v${version}-sunos-${cpu_type}"
>
126a149,159
>
>     elif [[ "$operating_system" =~ "SunOS" ]]; then
>       # reset cpu_type based on isainfo
>       local bits=$(isainfo -b)
>       if [[ "$bits" =~ "64" ]]; then
>         cpu_type="x64"
>       else
>         cpu_type="x86"
>       fi
>       echo "http://nodejs.org/dist/v${version}/node-v${version}-sunos-${cpu_type}.tar.gz"
>
```

**Comment by ypid** [comment]
The mentioned refactoring has been proposed in #25.

**Comment by HashNuke** [comment]
@mehayden Please let us know if we can close this issue.

**Comment by mehayden** [comment]
@HashNuke The latest install script does not check for string `SunOS` nor `Solaris` in `uname -a` output to determine operating system, nor use `isainfo -b` to determine number of bits. So I don't believe it has been addressed. BTW, `uname -m` returns `i86pc` on this system which doesn't seem useful on this system and won't match either the expected outputs in the script.

**Comment by ypid** [comment]
@mehayden But I guess it would not be to difficult now to add support for such platforms if one needs them … :wink:

**Comment by Stratus3D** [comment]
@mehayden is this still an issue? If so do you know enough to create a PR? I'd like to get this issue resolved if it hasn't already been.
