### ISSUE TITLE
gpg keyserver receive failed Server indicated a failure

### ISSUE THREAD

**Issue by andresdotsh** [asdf-vm/asdf-nodejs#261]
I'm trying to install nodejs on a (intel) macbook pro with macos big sur 11.6.

```
asdf install nodejs 14.18.0
```

But I'm getting this error:

```
gpg: keyserver receive failed: Server indicated a failure
```

Is there any solution?
I tried reinstalling the nodejs plugin but nothing changed.
😞

**Comment by augustobmoura** [comment]
Duplicate of #241
