### ISSUE TITLE
Maintainer needed?

### ISSUE THREAD

**Issue by ypid** [asdf-vm/asdf-nodejs#27]
Is this plugin currently actively maintained? When I look at the [open pull requests](https://github.com/asdf-vm/asdf-nodejs/pulls) ([one of them is really critical](https://github.com/asdf-vm/asdf-nodejs/pull/16)) it does not seem that way. But I don’t want to complain and rather offer my help. Can I help in any way to maintain this and get it up to speed again?

**Comment by HashNuke** [comment]
@ypid Sorry that PR went unnoticed. Checked and merged.

**Comment by ypid** [comment]
Thanks for your feedback. Then I will help with that. I looked over all PR while working on #25. Most of them are incorperated in #25 and I just reviewed and approved #24.
