### ISSUE TITLE
How to upgrade LTS release to newest patch/minor version

### ISSUE THREAD

**Issue by codethief** [asdf-vm/asdf-nodejs#273]
For a project I set the node version through .tool-versions like so:

```
nodejs lts-fermium
```

Afterwards, I ran `asdf install` upon which asdf-nodejs installed v14.17.2 and linked `lts-fermium` to it. This is reflected by

```shell
$ cd ~/.asdf/installs/nodejs/ 
$ ls -l lts-fermium
lrwxrwxrwx 1 user user 41 Jul  1 19:54 lts-fermium -> /home/user/.asdf/installs/nodejs/14.17.2
``` 

Since then, various new versions of Node 14 have been released. How do I upgrade lts-fermium, though, and make it point to the newest version (v14.18.2)?

I have tried:

```shell
$ asdf install nodejs lts-fermium
nodejs lts-fermium is already installed
$ asdf install nodejs latest:lts-fermium
nodejs lts-fermium is already installed
```

Do I really need to uninstall lts-fermium first and then re-install it again?

**Comment by augustobmoura** [comment]
`lts` aliases shouldn't be used on `.tool-versions` files, it's a bug that makes it work that way. And yes, the short answer is that `lts`es need to be uninstalled and reinstalled as of now. They will not be downloaded twice, the version behind the tag will not be uninstalled.

**Comment by codethief** [comment]
> lts aliases shouldn't be used on .tool-versions files, it's a bug that makes it work that way.

Is this documented somewhere? Or is there a bug ticket that I can follow?
