### ISSUE TITLE
Unknown command: `asdf reshim nodejs 17.2.0`

### ISSUE THREAD

**Issue by dbenton9** [asdf-vm/asdf-nodejs#275]
So I just got a new mac and am trying to get my tools setup. I've got `homebrew`, `asdf`, `ruby` and `postgres`.

When I try to install node I do:
```
asdf add plugin nodejs
asdf install nodejs 17.2.0
```
and I get this error when I try to do the install

```
Trying to update node-build... ok
Downloading node-v17.2.0-darwin-arm64.tar.gz...
-> https://nodejs.org/dist/v17.2.0/node-v17.2.0-darwin-arm64.tar.gz
Installing node-v17.2.0-darwin-arm64...
Installed node-v17.2.0-darwin-arm64 to /Users/davidbenton/.asdf/installs/nodejs/17.2.0

Unknown command: `asdf reshim nodejs 17.2.0`
/opt/homebrew/Cellar/asdf/0.9.0/libexec/bin/asdf: line 82: /Users/davidbenton/.asdf/lib/commands/command-help.bash: No such file or directory
```

That file directory doesn't exist but I'm not sure if I need to redirect asdf-node to the right file path or if this something that needs to be fixed.

**Comment by augustobmoura** [comment]
Should be the same issue as #253, ping me if not so to re-open the issue

**Comment by dbenton9** [comment]
@augustobmoura That did the trick, thank you so much!
