### ISSUE TITLE
Broken build process after recent update

### ISSUE THREAD

**Issue by GeoffreyEmerson** [asdf-vm/asdf-nodejs#276]
Something about a recent change has broken our team's build process. Here's the relevant output:

```
$ asdf plugin update nodejs
Updating nodejs...
From https://github.com/asdf-vm/asdf-nodejs
   ea13348..0237452  master     -> master
   ea13348..0237452  master     -> origin/master
Already on 'master'
Your branch is up to date with 'origin/master'.
$ asdf install
Cloning node-build...
/root/.asdf/plugins/nodejs/bin/install: line 52: ASDF_DOWNLOAD_PATH: unbound variable
```

I can see there were some changes in PR #272. 

Can anybody tell me what is the proper usage of the new version? Or is this a problem with our setup?

**Comment by vivekprahlad** [comment]
Hi Geoffrey,

It's quite likely that your build process is using an old version of asdf. This plugin works fine with asdf v. 0.8.0, but it won't work with older versions (I've seen the same error message as the one above with v. 0.6.2, for example). Hope this helps!

**Comment by Stratus3D** [comment]
@vivekprahlad is correct. Your new version of asdf-nodejs expects `ASDF_DOWNLOAD_PATH`, but only asdf 0.8.0 and later set that variable. This plugin is not backwards compatible with old asdf versions, so I suggest you either upgrade asdf to 0.8.0 or newer or download asdf-nodejs.
