### ISSUE TITLE
Add command to update global package install

### ISSUE THREAD

**Issue by Marthym** [asdf-vm/asdf-nodejs#282]
Hi,

I don't find command that allow install a newly inserted global package after installing node.

If I add a package in `~/.default-npm-packages` after installing all the node version I need, how can I update all versions with the new package ?

I must reinstall all node versions ?

Thanks

**Comment by augustobmoura** [comment]
We should keep this package simple. With one-liners, updating (or running anything) in multiple versions is easily accessible. Like so:

``` bash
# Updating a single package in all versions
asdf list nodejs | xargs -I@ env ASDF_NODEJS_VERSION="@" npm install -g $pkg

# Updating all packages in all versions
asdf list nodejs | xargs -I@ env ASDF_NODEJS_VERSION="@" npm upgrade -g

# Will also can easily parallelize it with the -P xargs option
asdf list nodejs | xargs -I@ -P4 env ASDF_NODEJS_VERSION="@" npm upgrade -g
```

If it's a very common operation you can always create an alias or function with this code
