### ISSUE TITLE
[macOS M1] printf: write error: Broken pipe

### ISSUE THREAD

**Issue by sukinoverse** [asdf-vm/asdf-nodejs#300]
I've got followig error while install nodejs

```
asdf install nodejs 16.15.0  
/Users/sukino/.asdf/plugins/nodejs/bin/../lib/utils.sh: line 82: printf: write error: Broken pipe
Trying to update node-build... ok
Downloading node-v16.15.0-darwin-arm64.tar.gz...
-> https://nodejs.org/dist/v16.15.0/node-v16.15.0-darwin-arm64.tar.gz
Installing node-v16.15.0-darwin-arm64...
Installed node-v16.15.0-darwin-arm64 to /Users/sukino/.asdf/installs/nodejs/16.15.0
```

NodeJS in installed correctly and usable.
So, It would be nice if that error message does not exist.

Probably related to https://github.com/asdf-vm/asdf-nodejs/issues/217

**System info**
asdf v0.10.0
macOS Monterey 12.3.1

---

**Screenshot**
<img width="1004" alt="Screen Shot 2565-05-02 at 21 22 48" src="https://user-images.githubusercontent.com/9070844/166250495-8a404cb4-eb9e-45c3-a30b-9eb56aeeae82.png">

**Comment by augustobmoura** [comment]
@metebyte on #301 
> ### Describe the Bug
> Getting the error mentioned on the title when installing a version of a plugin.
> 
> ### Steps to Reproduce
> 1. asdf install nodejs [tag || version number]
> 
> ### Expected Behaviour
> Not to get those `printf` errors.
> 
> ### Actual Behaviour
> ```
> ❯ asdf install nodejs lts
> /Users/metebyte/.asdf/plugins/nodejs/bin/../lib/utils.sh: line 77: printf: write error: Broken pipe
> Installing alias lts as 16.15.0
> /Users/metebyte/.asdf/plugins/nodejs/bin/../lib/utils.sh: line 82: printf: write error: Broken pipe
> Trying to update node-build... ok
> Downloading node-v16.15.0-darwin-x64.tar.gz...
> -> https://nodejs.org/dist/v16.15.0/node-v16.15.0-darwin-x64.tar.gz
> Installing node-v16.15.0-darwin-x64...
> Installed node-v16.15.0-darwin-x64 to /Users/metebyte/.asdf/installs/nodejs/16.15.0
> 
> Linking "lts" to "16.15.0"
> ```
> 
> ### Environment
> ```shell
> OS:
> Darwin MacByte.local 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64 x86_64
> 
> SHELL:
> zsh 5.8 (x86_64-apple-darwin21.0)
> 
> ASDF VERSION:
> v0.10.0-a9caa5b
> 
> ASDF ENVIRONMENT VARIABLES:
> ASDF_DIR=/Users/metebyte/.local/share/zinit/plugins/asdf-vm---asdf
> 
> ASDF INSTALLED PLUGINS:
> nodejs                       https://github.com/asdf-vm/asdf-nodejs.git master b2d06a7
> ```
> 
> ### asdf plugins affected (if relevant)
> ```
> nodejs                       https://github.com/asdf-vm/asdf-nodejs.git master b2d06a7
> ```

**Comment by masaaki-horie** [comment]
Here is workaround.  The `printf` command is different between GNU/Linux and macOS.
`brew install coreutils`: Install GNU printf
vim /Users/<username>/.asdf/plugins/nodejs/bin/../lib/utils.sh +82
change `printf` to `gprintf`

System Info: 
asdf v0.10.0
macOS 12.3.1 Monterey

**Comment by muescha** [comment]
### Error:

The error is still in `v0.10.1`:

```shell
muescha@MacBook% asdf install nodejs 18.2.0
/Users/muescha/.asdf/plugins/nodejs/bin/../lib/utils.sh: line 82: printf: write error: Broken pipe
Trying to update node-build... ok
Downloading node-v18.2.0-darwin-arm64.tar.gz...
-> https://nodejs.org/dist/v18.2.0/node-v18.2.0-darwin-arm64.tar.gz
Installing node-v18.2.0-darwin-arm64...
Installed node-v18.2.0-darwin-arm64 to /Users/muescha/.asdf/installs/nodejs/18.2.0
```

the error is in:

```shell
    printf "%s\t%s\n" "$version" "$version"
```

### Environment

asdf v0.10.1
macOS 12.1 Monterey

**Comment by heydonovan** [comment]
This issue was corrected using a more recent version of bash with `brew install coreutils`:

```
$ asdf --version
v0.10.1-f8109e0

$ /bin/bash --version
GNU bash, version 3.2.57(1)-release (arm64-apple-darwin21)

$ /opt/homebrew/bin/bash --version
GNU bash, version 5.1.16(1)-release (aarch64-apple-darwin21.1.0)
```

Make sure the newer bash is in your $PATH aka typing `bash --version` actually shows a modern release.

**Comment by augustobmoura** [comment]
Can someone check if it's fixed on master?
Just update asdf by running `asdf update nodejs` and try installing a new version

**Comment by stevehuangc7s** [comment]
> Can someone check if it's fixed on master? Just update asdf by running `asdf update nodejs` and try installing a new version

I just tried to re-install the latest nodejs version after running `asdf plugin update nodejs` and the "broken pipe" warning disappeared.

Thanks for the fix!

**Comment by hyperupcall** [comment]
Since this issue popped again, I'll add the detail that this is no longer an issue since https://github.com/asdf-vm/asdf-nodejs/commit/c406dac170e766b473f87340ff4b48b86d59d861#diff-f9746898bdf5ee311b5c55bc0b6d8c64901f52940c591089b3bfbda5f5b26c8a, if anyone else stumbles upon this. A more detailed explanation can be found [here](https://github.com/asdf-vm/asdf/issues/1478#issuecomment-1631564624).
