### ISSUE TITLE
bug: utils.sh line XX: printf: write error: Broken pipe

### ISSUE THREAD

**Issue by metebyte** [asdf-vm/asdf-nodejs#301]
### Describe the Bug

Getting the error mentioned on the title when installing a version of a plugin.

### Steps to Reproduce

1. asdf install nodejs [tag || version number]

### Expected Behaviour

Not to get those ```printf``` errors.

### Actual Behaviour

```
❯ asdf install nodejs lts
/Users/metebyte/.asdf/plugins/nodejs/bin/../lib/utils.sh: line 77: printf: write error: Broken pipe
Installing alias lts as 16.15.0
/Users/metebyte/.asdf/plugins/nodejs/bin/../lib/utils.sh: line 82: printf: write error: Broken pipe
Trying to update node-build... ok
Downloading node-v16.15.0-darwin-x64.tar.gz...
-> https://nodejs.org/dist/v16.15.0/node-v16.15.0-darwin-x64.tar.gz
Installing node-v16.15.0-darwin-x64...
Installed node-v16.15.0-darwin-x64 to /Users/metebyte/.asdf/installs/nodejs/16.15.0

Linking "lts" to "16.15.0"
```

### Environment

```shell
OS:
Darwin MacByte.local 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64 x86_64

SHELL:
zsh 5.8 (x86_64-apple-darwin21.0)

ASDF VERSION:
v0.10.0-a9caa5b

ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=/Users/metebyte/.local/share/zinit/plugins/asdf-vm---asdf

ASDF INSTALLED PLUGINS:
nodejs                       https://github.com/asdf-vm/asdf-nodejs.git master b2d06a7
```

### asdf plugins affected (if relevant)

```
nodejs                       https://github.com/asdf-vm/asdf-nodejs.git master b2d06a7
```

**Comment by Stratus3D** [comment]
@augustobmoura any idea what is going on here?

**Comment by augustobmoura** [comment]
Kinda of, we had a similar error before, it's inoffensive aside from the error message, the version is installed still. It was fixed on #265 last time. I made some changes for the alias resolving code and I think it's back

**Comment by metebyte** [comment]
Thanks for your reply. Yes the plugin installed successfully. Since I've switched from Antibody to Zinit and installed Asdf with Zinit. I was kinda in need of create an issue about this odd output.

**Comment by augustobmoura** [comment]
I will close this and keep the discussion on #300, as it was reported first, I will also quote your report on there
