### ISSUE TITLE
`node` does not know where to find global packages

### ISSUE THREAD

**Issue by sneko** [asdf-vm/asdf-nodejs#309]
Hi,

I tried installing a global package with:
```
npm install -g re2
```

But when running a basic script with `node test.js`:
```js
var RE2 = require("re2");

// with default flags
var re = new RE2("a(b*)");
var result = re.exec("abbc");
console.log(result[0]); // "abb"
console.log(result[1]); // "bb"
```

I get this error:
```
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 're2'
Require stack:
```

After investigating a bit it seems my directory for global packages is:
```
npm root -g
/Users/sneko/.asdf/installs/nodejs/16.15.0/.npm/lib/node_modules
```

So to make the script working I have to do:
```
export NODE_PATH=/Users/sneko/.asdf/installs/nodejs/16.15.0/.npm/lib/node_modules
```

Why this is not the default behavior? Did I miss something at the setup?

Since my Node version can change depending on the directory, it means the `NODE_PATH` should be set at each asdf nodejs version change:
```
export NODE_PATH=$(npm root -g)
```

cc @augustobmoura

**Comment by augustobmoura** [comment]
This is the correct behavior and is not related to `asdf-nodejs` per se. Global packages are not available in node scripts by default. The same situation happens in the official docker images.

In fact, `node` by itself only cares about files in the current `node_modules` directory (overridable by the `NODE_PATH` var, as you find out), it doesn't have any deep integration with its package manager (`npm`). Global packages are only a concept inside `npm`.

**Comment by sneko** [comment]
@augustobmoura thank you for your answer.

Next time I will make a real npm package for temporary tests, will solve this kind of issue 👍
