### ISSUE TITLE
PM2: command not found

### ISSUE THREAD

**Issue by rafosolima** [asdf-vm/asdf-nodejs#316]
I have the node version and yarn:

````bash
asdf current
nodejs 16.14.0 /home/raphael/.tool-versions
yarn 1.22.19 /home/raphael/.tool-versions
````

I have already used the command:

````bash
asdf reshim
````

I can run the commands in my terminal, but when I use the execSync command importing from lib child_process the following message appears: 

````bash
/bin/sh: line 1: pm2: command not found
Error: Command failed: pm2 start ecosystem.config.js
/bin/sh: line 1: pm2: command not found
````

I use wsl2 + arch linux (terminal)

Can anyone help me?

**Comment by augustobmoura** [comment]
How are you using `pm2` in your project? If using it at all
`pm2` has some known issues when handling asdf shims

**Comment by rafosolima** [comment]
@augustobmoura So I solved this problem with an article I read, telling me to add the following line to .bashrc:
```bash
export PATH="$(yarn global bin):$PATH"
```
