### ISSUE TITLE
Node LTS not updated

### ISSUE THREAD

**Issue by hendursaga** [asdf-vm/asdf-nodejs#321]
[Node.JS's homepage](https://nodejs.org/en/) shows that `16.18.0` is the current LTS, but this plugin only goes up to `16.17.1`. And yes, I'm on the latest commit.

**Comment by midorizemi** [comment]
I have the same problem.

**Comment by Michsior14** [comment]
As a workaround you can run `asdf nodejs update-nodebuild` and then try to install it once again. Worked for me.

**Comment by hendursaga** [comment]
LTS is finally available without any workarounds!
