### ISSUE TITLE
Suggestion: Create major version number alias same as codename alias!

### ISSUE THREAD

**Issue by akkadaya** [asdf-vm/asdf-nodejs#327]
React-Native has `.node-version` with value `16` by default and `asdf` doesn't recognise that version. 

`asdf` should be able to install version `16` same as `lts-gallium` version which is a symlink to the latest 16 version.

as a workaround I use:
```shell
ln -s ${HOME}/.asdf/installs/nodejs/lts-gallium ${HOME}/.asdf/installs/nodejs/16
```

**Comment by chriszs** [comment]
There are a number of projects where this is a persistent compatibility issue for me. Glad to see a workaround, though.

**Comment by bradydoll** [comment]
Looks like it doesn't support version numbers like `16.2`, either.
[https://github.com/shadowspawn/node-version-usage#compatibility-testing](https://github.com/shadowspawn/node-version-usage#compatibility-testing)

**Comment by Albert-IV** [comment]
To add onto this, it would also be nice to have an alias like `lts-14` `lts-16` or `lts-18`.  I guess if there was a major version number alias it would be less helpful, but that is what my first guess is when I'm trying to swap to an older LTS version without the codename's on hand.

**Comment by ubmit** [comment]
@akkadaya this would be a good improvement!

**Comment by augustobmoura** [comment]
We changed the way aliases work on #348, now you need to explicitly opt-in with dynamic ranges on legacy version files (`.tool-versions` and `.nvmrc`). The `.tool-versions` file doesn't support non-deterministic versions, and supporting it on `.tool-versions` is not a feature we are seeking to implement at the moment.

To enable it, you need to provide an `ASDF_NODEJS_LEGACY_FILE_DYNAMIC_STRATEGY` environment variable choosing between the `latest_available` and `latest_installed` strategies, you can read more about it in the [appropriate section](https://github.com/asdf-vm/asdf-nodejs#partial-and-codename-versions) on the README of the project. To make this choice permanent you can export said variable from your shell rc file like so:

```bash
export ASDF_NODEJS_LEGACY_FILE_DYNAMIC_STRATEGY=latest_installed
# OR
export ASDF_NODEJS_LEGACY_FILE_DYNAMIC_STRATEGY=latest_available
```

Please update the plugin by running `asdf plugin-update nodejs`. If a new issue arises with the new implementation please open a new issue.
