### ISSUE TITLE
`asdf install nodejs lts` fails on first attempt

### ISSUE THREAD

**Issue by sargunv** [asdf-vm/asdf-nodejs#329]
When I first install this nodejs plugin and then attempt `asdf install nodejs lts`, I get the error:

```
Cloning node-build
node-build: definition not found: lts
```

Re-running the same command works.

I can then replicate the issue again by `asdf plugin remove nodejs` and starting over.

![image](https://user-images.githubusercontent.com/1320357/212568467-fe1dc9c0-71da-44e1-b1b5-0f5e70354a18.png)

**Comment by sargunv** [comment]
Looks to be the same issue as https://github.com/asdf-vm/asdf-nodejs/issues/319, which was closed b/c they were using the alias in `.tool-versions` instead of via `asdf install`.

I can replicate this issue with both methods.

**Comment by sargunv** [comment]
Figured it out: `resolve_version_query` in the `install` script requires `node-build` in order to resolve an alias, but `node-build` isn't installed/updated until after `resolve_version_query` is called.

Filing a PR to fix

**Comment by tenjaa** [comment]
Ran into this today. Are there any updates on merging this fix?

**Comment by augustobmoura** [comment]
We changed the way aliases work on #348, now you need to explicitly opt-in with dynamic ranges on legacy version files (`.tool-versions` and `.nvmrc`). The `.tool-versions` file doesn't support non-deterministic versions, and supporting it on `.tool-versions` is not a feature we are seeking to implement at the moment.

To enable it, you need to provide an `ASDF_NODEJS_LEGACY_FILE_DYNAMIC_STRATEGY` environment variable choosing between the `latest_available` and `latest_installed` strategies, you can read more about it in the [appropriate section](https://github.com/asdf-vm/asdf-nodejs#partial-and-codename-versions) on the README of the project. To make this choice permanent you can export said variable from your shell rc file like so:

```bash
export ASDF_NODEJS_LEGACY_FILE_DYNAMIC_STRATEGY=latest_installed
# OR
export ASDF_NODEJS_LEGACY_FILE_DYNAMIC_STRATEGY=latest_available
```

Please update the plugin by running `asdf plugin-update nodejs`. If a new issue arises with the new implementation please open a new issue.
