### ISSUE TITLE
Feature: provide best match install

### ISSUE THREAD

**Issue by blairham** [asdf-vm/asdf-nodejs#334]
It would be nice to do a "best match" install `latest:18.13` if you use a .node-version file with the contents `v18.13`. All the other NodeJS managers except this, the asdf-nodejs plugin is the only NodeJS manager that does not

**Comment by Stratus3D** [comment]
Closing as I believe this is a specific example of what was requested in https://github.com/asdf-vm/asdf-nodejs/issues/127. @blairham please follow that conversation.

Feel free to reopen if I've made a mistake here @augustobmoura .
