### ISSUE TITLE
`bin/list-aliases`

### ISSUE THREAD

**Issue by jdxcode** [asdf-vm/asdf-nodejs#335]
In [rtx](https://rtx.pub) I added the ability for plugins to define aliases such as the following:

```
#!/usr/bin/env bash

echo "lts 18.0.0"
echo "lts/hydrogen 18.0.0"
echo "lts/fermium 16.0.0"
```

These are different than the aliases in asdf-nodejs since they aren't install-time aliases, they'll always point to the most current release (or at least the most current version that's cached).

Of course, this isn't supported in asdf and it generally isn't something the team has been keen to adopt at the core level (See https://github.com/asdf-vm/asdf/issues/1024 for just one example of this). I suspect asdf wouldn't be willing to adopt `bin/list-aliases` for that reason. I think you should at least _consider_ it though because plugins already do this and having core support means we can resolve problems such as [#1024](https://github.com/asdf-vm/asdf/issues/1024) by not relying on symlinks for this behavior. This could also fix https://github.com/asdf-vm/asdf-nodejs/issues/193.

It may not be easy though. rtx was built from the very beginning to work with fuzzy versions such as `18` and `18.0` so it was trivial for me to add aliases since I was already needing to resolve versions correctly throughout the codebase—though admittedly I still see the occasional bug around this. (side note: this is functionality that I _needed_ from asdf, I probably wouldn't have written rtx if asdf had fuzzy versions in core.) Adding aliases to asdf may be unsurmountable though, and it may make performance issues much worse.

However I'm really posting this here to ask about asdf-nodejs in particular: would you be willing to consider a PR that adds `bin/list-aliases` even if that's an rtx-only script? Of course the file wouldn't be used by asdf so it wouldn't cause any user problems, but folks browsing the plugin might be a little confused about what the script is for. (I'd be willing to consider solving this problem directly by having it be `rtx-bin/list-aliases` or something)

I could fork asdf-nodejs into an rtx variant and regularly merge updates from here, but I would like to avoid that. I suppose this is kind of a bigger question about how asdf sees rtx and how would you like to think about compatibility issues such as this.

**Comment by augustobmoura** [comment]
Hi @jdxcode :wave: 

On a sidenote, I didn't know about rtx until now, looks like a really good idea! I feel really happy that more alternatives are bubbling up in the community!

Back to the question, I think that is a wider question that should probably be discussed with the asdf-core team, this is an official maintained after all. I personally don't have a problem if asdf could also benefit from it, that would also imply that `bin/list-aliases` would need to agree with an output interface.

Another problem that I can foresee would be of maintaining the said script, asdf strives to be a really simple tool and we avoid complex scripts, it might not be a big thing right now but would we wouldn't want it to grow in a monster in the future

**Comment by jdxcode** [comment]
yeah I realize what I'm asking for here is certainly not an easy question. Do you think I should pose this question over in asdf-vm/asdf?

**Comment by augustobmoura** [comment]
> yeah I realize what I'm asking for here is certainly not an easy question. Do you think I should pose this question over in asdf-vm/asdf?

Sorry for the delay. Your response got lost in all the notifications.

Yes, that decision should probably be taken on the asdf-core level. In fact, I'm in the process of revising aliases on this repository. The implementation that we have right is sub-optimal and a source of many bugs.

In the meantime, I would advise getting the aliases working on rtx side.

I also saw that rtx has its own implementation of this plugin on Rust, there are other reasons for the change, aside from missing the aliases? Performance or flexibility related?

**Comment by jdxcode** [comment]
right, I ended up deciding that I wanted to bring the logic for popular languages into the CLI itself rather than relying on plugins, so I don't actually have use for this anymore.

The main reason for doing that is actually mostly for security since it removes at least popular plugins as a potential vector.
