### ISSUE TITLE
GPG signature issue when downgrading node version

### ISSUE THREAD

**Issue by phtrivier** [asdf-vm/asdf-nodejs#35]
I've been using node 6.10.0 for a while (I had to import maintainers gpg signatures.)
I tried installing a previous version (6.2) but I keep getting the signature error : 

~~~
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6227    0  6227    0     0   7545      0 --:--:-- --:--:-- --:--:--  7547
gpg: no valid OpenPGP data found.
gpg: the signature could not be verified.
Please remember that the signature file (.sig or .asc)
should be the first file given on the command line.
Authenticity of checksum file can not be assured! Please be sure to check the README of asdf-nodejs in case you did not yet bootstrap trust. If you already did that then that is the point to become SUSPICIOUS! There must be a reason why this is failing. If you are installing an older NodeJS version you might need to import OpenPGP keys of previous release managers. Exiting.
~~~

I have a dedicated keyring, and I tried running both `import-release-team-keyring` and `import-previous-release-team-keyring` scripts.

Is there anything more to do ?

**Comment by lobo-tuerto** [comment]
I'm on Node 7.3.0, when trying to install 7.7.2 I get the gpg "No public key error".

**Comment by imdaveho** [comment]
having the same issue:

![image](https://cloud.githubusercontent.com/assets/13990019/24306421/e5a870c6-1096-11e7-9c78-45d2db004347.png)

**Comment by RobinClowers** [comment]
I'm also seeing this when installing node 6.10.0 on macOS 10.11.6. I made sure my brew and coreutils were up to date, and imported current and previous release team keys. It worked for me on another machine with a newer version of macOS, so I'm wondering if it's related to that somehow?

**Comment by rod-stuchi** [comment]
same issue:

![image](https://user-images.githubusercontent.com/19471811/26956750-8d840cf2-4c96-11e7-917f-d51cdd0271b1.png)

**Comment by evandrojr** [comment]
Same problem here, going back to nvm! bye!

**Comment by tysliu** [comment]
Go to https://github.com/nodejs/node then find and import "The full set of trusted release keys can be imported by running:"

**Comment by tedw** [comment]
FWIW, I was getting a `gpg: keyserver receive failed: No route to host` error using the code from the [NodeJS repo](https://github.com/nodejs/node#release-team), so I had to change the keyserver to `ipv4.pool.sks-keyservers.net`

```
gpg --keyserver ipv4.pool.sks-keyservers.net --recv-keys 94AE36675C464D64BAFA68DD7434390BDBE9B9C5
gpg --keyserver ipv4.pool.sks-keyservers.net --recv-keys FD3A5288F042B6850C66B31F09FE44734EB7990E
gpg --keyserver ipv4.pool.sks-keyservers.net --recv-keys 71DCFD284A79C3B38668286BC97EC7A07EDE3FC1
gpg --keyserver ipv4.pool.sks-keyservers.net --recv-keys DD8F2338BAE7501E3DD5AC78C273792F7D83545D
gpg --keyserver ipv4.pool.sks-keyservers.net --recv-keys C4F0DFFF4E8C1A8236409D08E73BC641CC11F4C8
gpg --keyserver ipv4.pool.sks-keyservers.net --recv-keys B9AE9905FFD7803F25714661B63B535A4C206CA9
gpg --keyserver ipv4.pool.sks-keyservers.net --recv-keys 56730D5401028683275BD23C23EFEFE93C4CFFFE
gpg --keyserver ipv4.pool.sks-keyservers.net --recv-keys 77984A986EBC2AA786BC0F66B01FBB92821C587A
```

h/t to [this Medium article](https://medium.com/@xiaoxiaohou/gpg-keyserver-receive-failed-no-route-to-host-9e47a0dd83f8) for showing how to list the available gpg servers:
```
$ gpg-connect-agent --dirmngr 'keyserver --hosttable'
```

**Comment by Stratus3D** [comment]
I think this has been fixed now. Can you all pull down the latest version and test it?

**Comment by jamescontent** [comment]
In case anyone comes across this later, you can resolve this issue (at least it resolved it for me on Debian) by running:

```bash
$ <YOUR_ASDF_INSTALL_DIR>/plugins/nodejs/bin/import-release-team-keyring
```

**Comment by jsatk** [comment]
@jamescontent thank you x 💯

**Comment by felipepatricio** [comment]
@jamescontent thanks,it  worked for me
