### ISSUE TITLE
Option to use the `engine` value inside of package.json

### ISSUE THREAD

**Issue by aleccool213** [asdf-vm/asdf-nodejs#350]
I see there is a legacy option for nvm files, what about `engines["node"]` inside of NPM projects package.json file? A lot of projects just have this set and nothing else. It is fully supported by NPM. If this is a good idea, I wouldn't mind making a PR to support it.

**Comment by jdxcode** [comment]
that field is for specifying compatible versions, it really shouldn't be used for this purpose IMO

**Comment by augustobmoura** [comment]
Agree with @jdxcode, aside from a differente semantic, engines allow much more than single versions, allowing full-fledge expressions (E.g.: `18 || 16 || 15.x`), which are not planned at the moment.

**Comment by aleccool213** [comment]
Good to know! Thanks for the quick feedback.
