### ISSUE TITLE
Cannot install nodejs lts

### ISSUE THREAD

**Issue by mimikun** [asdf-vm/asdf-nodejs#352]
```shell
❯ asdf install nodejs lts
Trying to update node-build... ok
node-build: definition not found: 18
```

cannot install nodejs lts.
Previously, it could be installed.

**Comment by Codex-** [comment]
Also encountering this:
```
➜  ~ asdf install x/.asdf/installs/nodejs/lts: No such file or directory
Trying to update node-build... ok
node-build: definition not found: 16
➜  ~ asdf install nodejs lts/hydrogen
mkdir: /Users/x/.asdf/installs/nodejs/lts: No such file or directory
Trying to update node-build... ok
node-build: definition not found: 18
```

**Comment by augustobmoura** [comment]
We changed [how codenames and partial versions work](https://github.com/asdf-vm/asdf-nodejs#partial-and-codename-versions), and `asdf install <codename>` will not work. You can still have codenames on legacy version files and they will be resolved correctly.

As an alternative, after updating asfd-nodejs to the latest version (`asdf plugin update nodejs`),  you can resolve the current `lts` version and install it with an oneliner:
```bash
# Resolves lts version
asdf nodejs resolve lts

# Resolve and install the latest lts version available for download
asdf install nodejs $(asdf nodejs resolve lts --latest-available)
```
If you prefer you can add this oneliner to your shell rc file and have it behind an alias

**Comment by brandoncc** [comment]
I get the same result:

```
$ asdf install nodejs $(asdf nodejs resolve lts --latest-available)
Cloning node-build...
node-build: definition not found: 18
```

**Comment by lougreenwood** [comment]
Hi, sorry for opening a closed thread....

I'm new to `asdf`, using the one-liner I can install the latest LTS, but how would this work for setting the version required in `.tool-versions`. I would have assumed that I could add `nodejs its` to `.tool-versions` and it would always track the latest LTS version dynamically.

Assuming this used to work with the code names / lts stuff that was mentioned [here](https://github.com/asdf-vm/asdf-nodejs/issues/352#issuecomment-1569477783), is this still possible now using the `resolve` sub-command interpolation strategy?

Thanks!

**Comment by lougreenwood** [comment]
Nevermind, seems that [`rtx`](https://rtx.pub) is backwards compatible with `asdf` and allows stuff like this out of the box
