### ISSUE TITLE
force compile not updating

### ISSUE THREAD

**Issue by M77ix** [asdf-vm/asdf-nodejs#355]
While trying to fix an install problem, I did `export ASDF_NODEJS_FORCE_COMPILE=true` and even after I switched back to `export ASDF_NODEJS_FORCE_COMPILE=false` it is still force compiling from source instead of taking the precompile binaries. Any idea how to resolve this issue??

**Comment by augustobmoura** [comment]
Which version are you trying to install, and which OS are you using? If no pre-compiled binaries are available it will fallback to building anyway

**Comment by M77ix** [comment]
I'm on Mac OS with an intel chip, I started downloading nodejs 18.16.0 but it sarted to force compile so I stopped it with ( control c ). After that I tried to install nodejs 16.13.0 and it is still doing force compile.

**Comment by M77ix** [comment]
I also did `export ASDF_NODEJS_VERBOSE_INSTALL=true` and after switching to false I'm still getting the verbose not sure why both of those command aren't working

**Comment by jdxcode** [comment]
it's because it checks for existence not value:

https://github.com/asdf-vm/asdf-nodejs/blob/4f8aa3d9ebeb626c6905f6456c5ded13b06b59ab/bin/install#L14

you need to clear that env var, not set it to "false"

**Comment by augustobmoura** [comment]
@jdxcode is correct, the variable needs to be unset or at least empty for it to count as a negative. @M77ix can you check if that solves the issue?

**Comment by augustobmoura** [comment]
I'm closing this a stale, if you still have the problem after setting the variable to empty please let me know
