### ISSUE TITLE
Force compile flag has a typo

### ISSUE THREAD

**Issue by bitboxer** [asdf-vm/asdf-nodejs#364]
I think the `-` after `ASDF_NODEJS_FORCE_COMPILE` is wrong. When I remove it, it forces compilation. With it, it does not:

https://github.com/asdf-vm/asdf-nodejs/blob/4f8aa3d9ebeb626c6905f6456c5ded13b06b59ab/bin/install#L14

**Comment by Stratus3D** [comment]
My guess is this should be:

`... [ "${ASDF_NODEJS_FORCE_COMPILE:-}" ]; ...`

The `${VAR:-}` is a common pattern when `VAR` may be undefined.

**Comment by augustobmoura** [comment]
Not a typo, the `${variable-word}` expansion means that word will be expanded if
and only if the variable is unset, the `${variable:-word}` syntax means that
word will be expanded if the variable is unset _or_ is an empty value.

On this case we only need to check for unset, as we are trying to avoid an error
of referencing unset variables
