### ISSUE TITLE
Ability to skip installing default npm packages

### ISSUE THREAD

**Issue by rubiin** [asdf-vm/asdf-nodejs#366]
when checking out an app that has a tools-version with a nodejs like XX, we need to install that version. But installing a nodejs version would automatically install all packages specified in `.default-npm.packages`. This is kind of troublesome if there are many packages and is not quite required when switching around nodejs versions just for trial sake

PROPOSAL:
It would be beneficial to provide users with the ability to skip the automatic installation of default npm packages during the setup process. This can be achieved by introducing a flag  that allows users to opt-out of installing these packages.
 Add a command-line flag (e.g., `--skip-default-packages`) to the setup script that users can use to skip the installation of default packages.

**Comment by jdxcode** [comment]
just set `ASDF_NPM_DEFAULT_PACKAGES_FILE=/noop`

**Comment by rubiin** [comment]
let me try

**Comment by rubiin** [comment]
I think the document should include this information as well. Should i make a pr?
