### ISSUE TITLE
`shasum` does not exist everywhere

### ISSUE THREAD

**Issue by rubencaro** [asdf-vm/asdf-nodejs#37]
Hi,

I just had problems installing nodejs when checking validity of files:
```bash
.asdf/plugins/nodejs/bin/install: line 210: shasum: command not found
```

On my system I had to change this:
```bash
210:  if ! shasum -a 256 --check <(grep "\s$archive_file_name$" "${authentic_checksum_file}"); then
```
to this:
```bash
210:  if ! sha256sum --check <(grep "\s$archive_file_name$" "${authentic_checksum_file}"); then
```

On some other systems `shasum` is called `sha1sum` too. Other just have neither, just plain `openssl`. I guess `shasum` is not as cross-platform as we all would like. There are many issues around about this (https://github.com/portainer/portainer/issues/507, https://github.com/lukas2511/dehydrated/issues/42, http://stackoverflow.com/questions/7500691/rvm-sha256sum-nor-shasum-found, etc... )

I think you may abstract the `shasum` command into a variable that is set up differently for each system, that way make it cross-platform-ish. O simply use `openssl sha -sha256`. That should work everywhere, I guess. 

Thanks

**Comment by Fs02** [comment]
I'm using manjaro deepin, and suddenly have the same problem

**Comment by rbudiharso** [comment]
Fresh install fedora 26 and I can confirm that I encounter the same problem

![screenshot from 2017-11-11 05-57-38](https://user-images.githubusercontent.com/43447/32682095-50783ef8-c6a5-11e7-9057-cf29c6d65599.png)

**Comment by rubencaro** [comment]
These days the problem is for line 211 instead of 210, but everything else stays the same.

**Comment by chintan-mishra** [comment]
The solution is to do the following:

```bash
asdf plugin-add nodejs

bash ~/.asdf/plugins/nodejs/bin/import-release-team-keyring

asdf install nodejs 10.9.0
```

Now the error will show up. It will have the line number and something related to `shasum`

Open the following file
`vi /home/cmishra/.asdf/plugins/nodejs/bin/install`

Now when in `vi` hit `Esc` and type the following `/shasum`.

In the line with the following statement 
`if ! shasum -a 256 --check <(grep "\s$archive_file_name$" "${authentic_checksum_file}"); then`
replace `shasum -a 256` with `sha256sum`.

This worked on my laptop Fedora KDE and my workstation Fedora GNOME. And would probably work in every distro.

**Comment by chintan-mishra** [comment]
Comment for maintainers:
Add a simple check to see if `shasum` is available or not will solve the issue.
```
if shasum is available
  #do things normally
else
  #use sha256 version
```

**Comment by Stratus3D** [comment]
I just merged PR #84. Can you all pull down the latest version of this plugin and let me know if that fixes the issue for you?

**Comment by Stratus3D** [comment]
Going to close this now. It's working for me in the scenarios I've tested.

**Comment by chintan-mishra** [comment]
Works fine for me. @Stratus3D
