### ISSUE TITLE
Unable to install 18.18.1

### ISSUE THREAD

**Issue by 1oglop1** [asdf-vm/asdf-nodejs#373]
Error: node-build: definition not found: 18.18.1

```
asdf list-all nodejs | grep '^18\.'
18.0.0
18.1.0
18.2.0
18.3.0
18.4.0
18.5.0
18.6.0
18.7.0
18.8.0
18.9.0
18.9.1
18.10.0
18.11.0
18.12.0
18.12.1
18.13.0
18.14.0
18.14.1
18.14.2
18.15.0
18.16.0
18.16.1
18.17.0
18.17.1
18.18.0
```

both versions are available here: 
* https://nodejs.org/dist/v18.18.0/
*  https://nodejs.org/dist/v18.18.1/

**Comment by eread** [comment]
@1oglop1 https://github.com/nodenv/node-build/pull/831 is merged, so this issue can be closed.
