### ISSUE TITLE
import-release-team-keyring not found

### ISSUE THREAD

**Issue by vs-pp** [asdf-vm/asdf-nodejs#374]
[nerves_hub_web](https://github.com/nerves-hub/nerves_hub_web) and even few other tuotrials refer to this script ```~/.asdf/plugins/nodejs/bin/import-release-team-keyring``` to install nodejs

I see that ~/.asdf/plugins/nodejs/ is coming from https://github.com/asdf-vm/asdf-nodejs.git and there is no ```import-release-team-keyring``` in
https://github.com/asdf-vm/asdf-nodejs/tree/master/bin

        ```
        venkat@XPS-8930:~/work/pp/zola/aloha_w2/nerves_hub_web$ git -C ~/.asdf/plugins/nodejs/ remote -v
        origin  https://github.com/asdf-vm/asdf-nodejs.git (fetch)
        origin  https://github.com/asdf-vm/asdf-nodejs.git (push)
        venkat@XPS-8930:~/work/pp/zola/aloha_w2/nerves_hub_web$ git -C ~/.asdf/plugins/nodejs/ branch
        * master
        ```

What would be the procedure to get this script.

**Comment by augustobmoura** [comment]
We don't use that script anymore. The guide that you read is outdated. You check integrity based on pre-computed hashing now, automatically provided by node-build
