### ISSUE TITLE
NodeJS 18.18.2 is not in the list!

### ISSUE THREAD

**Issue by akkadaya** [asdf-vm/asdf-nodejs#375]
I can't install [NodeJS 18.18.2](https://nodejs.org/dist/v18.18.2/) because it is not found
```sh
$ asdf install nodejs 18.18.2
Trying to update node-build... ok
node-build: definition not found: 18.18.2
```

How are new versions added?

**Comment by notnmeyer** [comment]
https://github.com/asdf-vm/asdf-nodejs/blob/master/README.md#manually-updating-node-build-definitions did the trick for me

**Comment by akkadaya** [comment]
thank you @notnmeyer. It was fixed by itself, I guess it just needed more time to fetch the new data
