### ISSUE TITLE
Can't install 21.0.0

### ISSUE THREAD

**Issue by boojum** [asdf-vm/asdf-nodejs#376]
```sh
asdf version
v0.13.1-0586b37

asdf plugin list --all
nodejs
```

I'm unable to install 21.0.0:
```sh
asdf install nodejs 21.0.0
Trying to update node-build... ok
node-build: definition not found: 21.0.0
```
Manually running `asdf nodejs update-nodebuild` doesn't help but `asdf nodejs nodebuild --definitions` doesn't seem to list v21.

Also, setting `ASDF_NODEJS_FORCE_COMPILE` doesn't seem to help.

**Comment by denis-manokhin** [comment]
The same issue with `20.9.0` version

```
$ asdf install nodejs 20.9.0
Trying to update node-build... ok
node-build: definition not found: 20.9.0
```

```
$ asdf version
v0.13.1-0586b37
```

**Comment by denis-manokhin** [comment]
Ok. It's because there is no 20.9.0 version in [node-build](https://github.com/nodenv/node-build) package.

**Comment by J3m5** [comment]
20.9.0 and 21.1.0 are coming https://github.com/nodenv/node-build/pull/837

**Comment by augustobmoura** [comment]
Closed as https://github.com/nodenv/node-build/pull/837 have been merged
