### ISSUE TITLE
gpg: keyserver receive failed: No route to host

### ISSUE THREAD

**Issue by jechol** [asdf-vm/asdf-nodejs#38]
`import-release-team-keyring ` failed with `gpg: keyserver receive failed: No route to host`

```shell
~/.asdf/plugins/nodejs ((b8683508…)|✔) ./bin/import-release-team-keyring 
gpg: keyserver receive failed: No route to host
```

I will open PR for this.

**Comment by jechol** [comment]
FYI, I live in South Korea. I'm not sure it happens only in Korea.

**Comment by 4ndv** [comment]
Same problem in Russia, manually added `ipv4.` to keyservers and it helped

**Comment by jtzero** [comment]
In case anyone else has the same problem I had to use this format
`gpg --keyserver hkp://ipv4.pool.sks-keyservers.net:80`

**Comment by nickveys** [comment]
Still running into this from time to time, but switching the address:

> pool.sks-keyservers.net

to

> pgp.mit.edu

Works every time for me so far, hope this helps someone in the future!

**Comment by mrdavidjcole** [comment]
@nickveys hello from the future. This helped. Thanks!

**Comment by Stratus3D** [comment]
Maybe this should be configurable?

**Comment by gpyzy** [comment]
@jtzero Thanks! It works now!

**Comment by tacnoman** [comment]
Same problem in Brazil :/

```sh
$ gpg --keyserver pool.sks-keyservers.net --recv-keys 94AE36675C464D64BAFA68DD7434390BDBE9B9C5
gpg: keyserver receive failed: No route to host
```
