### ISSUE TITLE
How to install Nodejs latest LTS version?

### ISSUE THREAD

**Issue by aliahadmd** [asdf-vm/asdf-nodejs#382]
It seems there have no LTS version to install but If i run this command `asdf nodejs resolve lts --latest-available `its available!

**Comment by augustobmoura** [comment]
You can't install `lts` versions directly, resolving `lts` only works for legacy file versions.
```bash
# This will NOT work
asdf install nodejs lts
```

If you need to install a version you can write your own script:
```bash
asdf nodejs install "$(asdf nodejs resolve lts --latest-available)"
```
