### ISSUE TITLE
Is it possible to show the LTS version in the list of versions right after installing the plugin?

### ISSUE THREAD

**Issue by supertgo** [asdf-vm/asdf-nodejs#386]
I know that there are some commands to install the LTS version and to show what's the current LTS version, but, is there a way to highlight the current LTS on the list of versions right after installing the plugin?

**Comment by augustobmoura** [comment]
> I know that there are some commands to install the LTS version and to show what's the current LTS version, but, is there a way to highlight the current LTS on the list of versions right after installing the plugin?

Not currently, we only show versions installable from `.tool-version` files. `lts` resolution is ony used for legacy version files
