### ISSUE TITLE
Cannot install node 21.7.x

### ISSUE THREAD

**Issue by marques-l-GILD** [asdf-vm/asdf-nodejs#387]
Looks like the `node-build` defs are outdated:

```console
$ asdf install nodejs 21.7.1
Trying to update node-build... ok
node-build: definition not found: 21.7.1
```

**Comment by bai** [comment]
There's an issue upstream that is waiting for this PR apparently: https://github.com/nodenv/node-build/pull/853

**Comment by stannum-l** [comment]
The upstream repo seems to have an outdated secret that prevents proper merging of the build. I implemented a workaround by cloning and rebuild the node build.

```
rm -rf ~/.asdf/plugins/nodejs/.node-build. # remove the local node-build
export ASDF_NODEJS_NODEBUILD_REPOSITORY=https://github.com/stannum-l/node-build.git
asdf list all nodejs
```

This is just a workaround; please use the official node-build repo whenever the issue is resolved.
