### ISSUE TITLE
nodejs 20.15.1 is not available

### ISSUE THREAD

**Issue by SergeyKhval** [asdf-vm/asdf-nodejs#394]
Can't install nodejs 20.15.1 with asdf, 20.15.0 is the only available version
![image](https://github.com/asdf-vm/asdf-nodejs/assets/16866432/c4db2ffe-3840-4120-9ebd-410eb2de78de)

however it's available for download 
![image](https://github.com/asdf-vm/asdf-nodejs/assets/16866432/9a0ec558-d8fa-4d8e-b6b3-878344fb7dd8)

**Comment by smaboshe** [comment]
Thank you for creating this issue. I am experiencing the problem:

```
% asdf install nodejs 20.15.1
Trying to update node-build... ok
node-build: definition not found: 20.15.1
```

I would like to install node 20.15.1 because it is a [security release](https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V20.md#2024-07-08-version-20151-iron-lts-rafaelgss).

**Comment by SergeyKhval** [comment]
it works now, closing
