### ISSUE TITLE
node-build: definition not found: 22.12.0

### ISSUE THREAD

**Issue by stefanonepanedap** [asdf-vm/asdf-nodejs#405]
When trying to update to the latest available version of nodejs v22 I get the following message:

```bash
$> asdf install nodejs 22.12.0
$> Trying to update node-build... ok
$> node-build: definition not found: 22.12.0
```

Is there anything my side that I can do?

I tried to update node-build using `asdf nodejs update-nodebuild `, but still keep receiving the same error.

Thank you all for your brilliant work, I really enjoy using asdf ❤️

**Comment by Stratus3D** [comment]
@stefanonepanedap did you see if that version was listed in the output of `asdf list all nodejs` at the time you tried to install it?

**Comment by stefanonepanedap** [comment]
It has been fixed now.
