### ISSUE TITLE
GPG error when importing release team keys

### ISSUE THREAD

**Issue by belaustegui** [asdf-vm/asdf-nodejs#43]
I am installing the NodeJS asdf plugin. After adding the plugin I proceed to import the release team OpenPGP keys to my keyring using the command specified in the README:

```
# Imports Node.js release team's OpenPGP keys to main keyring
bash ~/.asdf/plugins/nodejs/bin/import-release-team-keyring
```

Instead of importing the keys, I get the following error:
```
gpg: keyserver receive failed: No keyserver available
```

**Comment by phraemer** [comment]
Same here on macOS.
Interestingly, it worked fine on a Debian 8 VM on the same Mac.

**Comment by belaustegui** [comment]
The command is working again. It looks like the cause was a temporary error in the keyserver.
I'm closing this issue.

**Comment by dikaio** [comment]
I'm getting the same error on the most recent MacOS High Sierra update.

`bash ~/.asdf/plugins/nodejs/bin/import-release-team-keyring`
`gpg: keyserver receive failed: Server indicated a failure`
