### ISSUE TITLE
Only import release team keys when not already imported

### ISSUE THREAD

**Issue by dbernheisel** [asdf-vm/asdf-nodejs#45]
This is not really an issue, but I have had some local development issues when not connected to the internet and still need to run my project setup script that uses `asdf` and `asdf-nodejs`.

Currently, I have asdf and the nodejs binaries downloaded and cached, and my project that uses asdf to manage tool versions has a setup script that runs `asdf install` and also runs this plugin's `import-release-team-keyring` script, but that always hits the internet, and sometimes keyservers are unreliable even when I am connected so it stops my setup script needlessly since it exits with an error.

I've opened a pull request #44 if you're interested and think it's helpful for others.

**Comment by Stratus3D** [comment]
Closing since this has been addressed by #88 and a couple other PRs.
