### ISSUE TITLE
NPM postinstall hooks not run with npm 5.3.0

### ISSUE THREAD

**Issue by Jwashton** [asdf-vm/asdf-nodejs#47]
As tested on two Ubuntu boxes and a Mac:

```bash
$ npm --version
5.3.0
$ npm install -g create-elm-app
# ... runs but doesn't call the postinstall hooks to create the shim
$ asdf global nodejs 8.1.2
$ npm --version
5.2.0
$ npm install -g create-elm-app
# ... runs and creates the shim as expected.
```

**Comment by 4ndv** [comment]
Same problem with npm 5.1.0 and 5.2.0:

```shell
▲ ~ npm i -g coffeescript
/Users/noir/.asdf/installs/nodejs/8.1.2/.npm/bin/coffee -> /Users/noir/.asdf/installs/nodejs/8.1.2/.npm/lib/node_modules/coffeescript/bin/coffee
/Users/noir/.asdf/installs/nodejs/8.1.2/.npm/bin/cake -> /Users/noir/.asdf/installs/nodejs/8.1.2/.npm/lib/node_modules/coffeescript/bin/cake
+ coffeescript@1.12.7
updated 1 package in 1.352s
▲ ~ coffee
zsh: command not found: coffee
```

But with 5.0.4 everything is ok

**Comment by caleb** [comment]
I'm running nodejs 8.2.1 and doing npm global installs don't shim for me either.

I fixed this by manually shimming: `asdf shim nodejs .npm/bin/ember` for example.

**Comment by ccblaisdell** [comment]
I had this issue and I wasn't entirely sure how to use @caleb 's fix. Based on what he provided I came up with the following:
```
~ ➜ asdf shim nodejs ~/.asdf/installs/nodejs/8.5.0/.npm/bin/ttab
~ ➜ asdf reshim nodejs 8.5.0
```

It didn't work after the first command, but it did after the second. I'm not entirely sure the first command was necessary, so ymmv.

**Comment by RobinClowers** [comment]
Yeah, same problem on macos. This is pretty annoying, any idea how we can fix this?

**Comment by caleb** [comment]
I think the shims work in the newest version of this plugin... It doesn't use a post install hook anymore, so try upgrading to the newest version of the plugin: `asdf plugin-update --all`

This seems to have worked for me.

**Comment by zainfathoni** [comment]
I just upgraded the plugin to the newest version, but I still need to execute `asdf reshim nodejs` everytime I install npm package globally.

**Comment by caleb** [comment]
@zainfathoni You are right, the automatic shimming is broken for me too.

**Comment by zainfathoni** [comment]
Thanks for the suggestion @caleb, I will try it out later. 😄

**Comment by zainfathoni** [comment]
Hi @caleb , I already installed a new version of nodejs and tried to install `vue-cli` globally, but it still didn't shimmed correctly. So I still had to execute `asdf reshim nodejs 8.7.0` again to make `vue` command available globally.

```
$ asdf install nodejs 8.7.0
$ asdf global nodejs 8.7.0
$ npm install -g vue-cli
```

Is it necessary to reinstall the `asdf-nodejs` plugin to make it works?

**Comment by caleb** [comment]
You just have to make sure your NodeJS asdf plug in is the latest version before installing NodeJS.

It has been working for me. So maybe your asdf plug in is not up to date

**Comment by sevenseacat** [comment]
I'm needing to manually re-shim after globally installing libraries too. I just set up asdf and asdf-js today, and still seeing the behaviour.

**Comment by willbchang** [comment]
It still happens
```bash
➜  ~ node -v
v15.0.1
➜  ~ npm -v
7.0.3

➜  ~ which node
/Users/Will/.asdf/shims/node
➜  ~ which npm
/Users/Will/.asdf/shims/npm

➜  ~ npm i -g pnpm
added 1 package, and audited 1 package in 8s
➜  ~ pnpm
fish: Unknown command: pnpm
➜  ~ asdf reshim nodejs 

➜  ~ pnpm -v
5.10.2
➜  ~ which pnpm
/Users/Will/.asdf/shims/pnpm
```

**Comment by vaibhavsingh97** [comment]
As @willbchang said, it still happening for me too :(

**Comment by augustobmoura** [comment]
This issue is solved on master now. The problem was on the npm side, it didn't fully support npm `.hooks` in these specific versions. I added a new mechanism for auto-reshimming that doesn't rely on `node_modules/.hooks`
