### ISSUE TITLE
Install fails on Arm architectures.

### ISSUE THREAD

**Issue by paulanthonywilson** [asdf-vm/asdf-nodejs#55]
This is explained and solved, at least in my experience, by @petermm 's PR https://github.com/asdf-vm/asdf-nodejs/pull/41 . 

I'm adding this as in issue as I ran into the same issue yesterday, but just checked in issues rather than here. This presents as:

```
shasum: /dev/fd/63: no properly formatted SHA256 checksum lines found
Authenticity of package archive can not be assured. Exiting.
```

**Comment by mclark-newvistas** [comment]
Is this resolved now that #41 has been merged?

**Comment by petermm** [comment]
afaik yes - bug (and fix) was pretty simple.

**Comment by Stratus3D** [comment]
I'm not sure what the status of this is, but it looks like it's been resolved. Please reopen if there is still an issue with this.
