### ISSUE TITLE
gpg: keyserver receive failed: Connection refused

### ISSUE THREAD

**Issue by anhari** [asdf-vm/asdf-nodejs#58]
Getting this error when attempting:

```
# Imports Node.js release team's OpenPGP keys to main keyring
bash ~/.asdf/plugins/nodejs/bin/import-release-team-keyring
```

**Comment by thiagogabriel** [comment]
@anhari It was not working for me 1 hour ago, but I tested again and it is working now. The change I did was to disable ipv6 on my router, but I enabled again to and it keeps working.

**Comment by tuvistavie** [comment]
Thanks for reporting.
Yes, we really need to make this script more robust.
I think we should at least try a few keyservers instead of a single one.
If anyone wants to take care of this, help is welcome.

workaround proposed in another project:
https://github.com/nodejs/docker-node/issues/340#issuecomment-321669029

**Comment by dbernheisel** [comment]
@tuvistavie there are a couple PRs to check that solves this if you have some time.

**Comment by tuvistavie** [comment]
@dbernheisel Thanks for the reminder, I just merged the PR which tries multiple servers.
Let's leave this opened for now and see how it goes.

**Comment by caleb** [comment]
Just to echo the router trouble... I have a Netgear R7800 and if I use my router's DNS servers I cannot fetch GPG keys.

I just set a Raspberry PI up as a DNS server as a workaround. I did not try disabling IPV6, but that might be something else to test.

**Comment by tobyhinloopen** [comment]
```
$ bash ~/.asdf/plugins/nodejs/bin/import-release-team-keyring
gpg: keyserver receive failed: No data
```

Am I doing it wrong?

**Comment by dbernheisel** [comment]
@tobyhinloopen works for me. I did ensure I was on the latest version by running `asdf plugin-update --all`
I also wouldn't doubt if there was some internet issue that was causing the two keyservers the script checks to not be available.

**Comment by caleb** [comment]
@tobyhinloopen Do you by any chance have a Netgear router?

I have the Nighthawk R7800, and if I use the built in DNS server I cannot connect to the key servers to grab keys. I have to use a different DNS server (I just use 8.8.8.8 and 8.8.4.4).

**Comment by joshproehl** [comment]
For what it's worth, I was having issues with import-release-team-keyring, getting "no data", and "general error" errors.

I used the script from #44 and was apparently able to correctly pull the required keys, as I can now use `asdf install nodejs ...` successfully, with the caveat that it threw the following warning:

> gpg: Signature made Tue 12 Jun 2018 04:26:36 PM PDT
> gpg:                using RSA key B9AE9905FFD7803F25714661B63B535A4C206CA9
> gpg: Good signature from "Evan Lucas <evanlucas@me.com>" [unknown]
> gpg:                 aka "Evan Lucas <evanlucas@keybase.io>" [unknown]
> gpg: WARNING: This key is not certified with a trusted signature!
> gpg:          There is no indication that the signature belongs to the owner.
> Primary key fingerprint: B9AE 9905 FFD7 803F 2571  4661 B63B 535A 4C20 6CA9
