### ISSUE TITLE
npx doesn't work

### ISSUE THREAD

**Issue by rbudiharso** [asdf-vm/asdf-nodejs#59]
I have installed node 8.7.0, both `node -v` and `npm -v` works, but npx is not.

<img width="386" alt="screen shot 2017-10-22 at 17 15 01" src="https://user-images.githubusercontent.com/43447/31860924-d765f1de-b74c-11e7-8b18-6a069d0bca07.png">

OS Mac OS High Sierra
asdf version 0.4.0

**Comment by Stratus3D** [comment]
Is the package installed for that version of Node.JS?
