### ISSUE TITLE
Missing RSA key ID 821C587A from the release team, keyserver changed

### ISSUE THREAD

**Issue by pmontrasio** [asdf-vm/asdf-nodejs#65]
I added a [comment](https://github.com/asdf-vm/asdf-nodejs/issues/40#issuecomment-343732518) to Issue #40 about the missing key with id 821C587A.

The cause is that there is a new Node release team member with that key.
Furthermore they changed keyserver from `ipv4.pool.sks-keyservers.net` to `pool.sks-keyservers.net`.

A quick fix is to download the missing key with 

```
gpg --keyserver pool.sks-keyservers.net --recv-keys 77984A986EBC2AA786BC0F66B01FBB92821C587A
```

but `~/.asdf/plugins/nodejs/bin/import-release-team-keyring` should be updated with the commands at https://github.com/nodejs/node#release-team

**Comment by hubertlepicki** [comment]
I have got the same issue.

**Comment by hubertlepicki** [comment]
The fix is to update nodejs plugin, or all plugins:

asdf update-plugin --all

and then re-import the pgp keys:
bash ~/.asdf/plugins/nodejs/bin/import-release-team-keyring

**Comment by PaoloLaurenti** [comment]
The workaround works fine. Only a little clarification.
The command is not `asdf update-plugin --all` but it's `asdf plugin-update --all` .

**Comment by wangbus** [comment]
Why does this say: "WARNING: This key is not certified with a trusted signature!"

```
% asdf install nodejs 8.9.2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4553    0  4553    0     0   8913      0 --:--:-- --:--:-- --:--:--  8927
gpg: Signature made Tue Dec  5 14:19:10 2017 PST
gpg:                using RSA key 77984A986EBC2AA786BC0F66B01FBB92821C587A
gpg: Good signature from "Gibson Fahnestock <gibfahn@gmail.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 7798 4A98 6EBC 2AA7 86BC  0F66 B01F BB92 821C 587A
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 15.2M  100 15.2M    0     0  2786k      0  0:00:05  0:00:05 --:--:-- 3172k
node-v8.9.2-darwin-x64.tar.gz: OK
```

**Comment by drusepth** [comment]
The workaround above does not work for me. 

```
$ gpg --list-keys | tail -n 6

pub   rsa4096 2016-10-07 [SC]
      77984A986EBC2AA786BC0F66B01FBB92821C587A
uid           [ unknown] Gibson Fahnestock <gibfahn@gmail.com>
sub   rsa4096 2016-10-07 [E]

$ asdf install nodejs 8.9.2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4553    0  4553    0     0  28324      0 --:--:-- --:--:-- --:--:-- 28456
gpg: Signature made Tue Dec  5 16:19:10 2017 CST
gpg:                using RSA key 77984A986EBC2AA786BC0F66B01FBB92821C587A
gpg: Can't check signature: No public key
Authenticity of checksum file can not be assured! Please be sure to check the README of asdf-nodejs in case you did not yet bootstrap trust. If you already did that then that is the point to become SUSPICIOUS! There must be a reason why this is failing. If you are installing an older NodeJS version you might need to import OpenPGP keys of previous release managers. Exiting.
```

I've tried clearing all keys and reimporting (from both `ipv4.pool.` and `pool.`, separately of course), but no solutions seem to be working. I'm on the latest asdf-nodejs as well.

```
$ asdf plugin-update nodejs
Updating nodejs...
Already up-to-date.
```

**Comment by annieogrady** [comment]
@drusepth  - any resolution?

**Comment by changalberto** [comment]
@drusepth I got the same issue... can't find a solution yet... please let me know if anyone has found a fix. Thanks

**Comment by drusepth** [comment]
No fix has been found. I switched to using [n](https://github.com/tj/n) to manage my nodejs versions.

**Comment by RobinClowers** [comment]
I have no real idea why, but this fixed it for me:

```bash
rm -rf ~/.asdf/keyrings/nodejs
~/.asdf/plugins/nodejs/bin/import-release-team-keyring
```

**Comment by Stratus3D** [comment]
Can you all try the latest version? I think this has been fixed.

**Comment by wangbus** [comment]
@Stratus3D Just tried 8.11.3 & 10.7.0 and they both work flawlessly. Thanks!

**Comment by drusepth** [comment]
Seems to now be working for me as well. 👍

**Comment by Stratus3D** [comment]
We may eventually need to add a `purge-release-team-keyring` script to invoke `rm -rf ~/.asdf/keyrings/nodejs` if this becomes a problem again, but for now I don't think anything is needed.

**Comment by changalberto** [comment]
This worked for me:

`bash ~/.asdf/plugins/nodejs/bin/import-previous-release-team-keyring`
