### ISSUE TITLE
Is nodejs v9.7.1 suppose to install npm v5.7.1 ?

### ISSUE THREAD

**Issue by ipatch** [asdf-vm/asdf-nodejs#70]
Presently when I install nodejs 9.4.0, 9.5.0, or 9.7.1 npm v5.6.0 is installed.  If I run the below command,

```sh
npm i -g npm
```

npm 5.7.1 is installed to 

> $HOME/.asdf/installs/nodejs/9.7.1/.npm/bin/npx -> $HOME/.asdf/installs/nodejs/9.7.1/.npm/lib/node_modules/npm/bin/npx-cli.js
> $HOME/.asdf/installs/nodejs/9.7.1/.npm/bin/npm -> $HOME/.asdf/installs/nodejs/9.7.1/.npm/lib/node_modules/npm/bin/npm-cli.js
> + npm@5.7.1
> added 533 packages in 8.269s

I then run

```sh
asdf reshim nodejs 9.7.1
```
but when I run `npm -v`

I am still presented with
```sh
5.6.0
```

I'm running macOS 10.12.6 if that makes a difference, and I'm running asdf v0.4.2

cheers 🍻
Chris

**Comment by Stratus3D** [comment]
Can you confirm your Node.JS version is correct? If you run `node --version` it should output 9.7.1 if things are working correctly.

**Comment by ipatch** [comment]
@Stratus3D 

Apparently Node.js v9.7.1 shipped with npm v5.6.0 out of the box.

<img width="1017" alt="node-npm-versions" src="https://user-images.githubusercontent.com/613805/41925399-0fa9b6c8-7932-11e8-97be-f3dcc7a578c3.png">

On a side note, the last developed version of the 9.7.x series of Node.js appears to be v9.7.1 barring any major CVE announcements.

...well 💩 I went to record the issue, I was having when trying to upgrade `npm` but apparently it isn't an issue anymore,  I put together an asciicast of upgrading npm using the installed version of Node.js and it appears to be working now.

kudos 🍩

[![asciicast](https://asciinema.org/a/aw37aovWscEBkELN3s89F1gcq.png)](https://asciinema.org/a/aw37aovWscEBkELN3s89F1gcq)
