### ISSUE TITLE
`asdf which` points to the wrong location

### ISSUE THREAD

**Issue by alexlafroscia** [asdf-vm/asdf-nodejs#71]
If I try to run

```bash
asdf which nodejs
```

The printed location is (on my machine)

> /Users/alafroscia/.asdf/installs/nodejs/8.9.4/bin/nodejs

However, that's not actually a pointer to the executable; the executable is at

> /Users/alafroscia/.asdf/installs/nodejs/8.9.4/bin/node

This doesn't match other plugins, such as `ruby` and `python`, which return the path to the actual executable.

**Comment by faraazahmad** [comment]
I think this is why I get the following warning
```
npm WARN lifecycle The node binary used for scripts is /home/faraaz/.asdf/shims/node but npm is using /home/faraaz/.asdf/installs/nodejs/8.11.1/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
```

**Comment by mclark-newvistas** [comment]
`asdf which nodejs` also gives "Version not installed" when using system nodejs.

**Comment by cclark** [comment]
Have there been any updates on this? I'm seeing the same messages as @alexlafroscia except that the paths are `/usr/local/opt/asdf/installs/nodejs/10.9.0/bin/nodejs` which makes sense because `asdf` saw installed via Homebrew and not into my home directory. But it is the same fundamental result in that running `node --version` returns the system version because asdf thinks the binary should be called `nodejs` instead of `node`.

**Comment by jpickwell** [comment]
@faraazahmad, try the following command to make that warning go away:

    npm config set scripts-prepend-node-path true

**Comment by Stratus3D** [comment]
> If I try to run
> 
> ```shell
> asdf which nodejs
> ```
> 
> The printed location is (on my machine)
> 
> > /Users/alafroscia/.asdf/installs/nodejs/8.9.4/bin/nodejs
> 
> However, that's not actually a pointer to the executable; the executable is at
> 
> > /Users/alafroscia/.asdf/installs/nodejs/8.9.4/bin/node

If you wanted the path to the `node` executable, shouldn't you have run `asdf which node`? As far as I know there isn't actually a `nodejs` executable.

**Comment by mclark-newvistas** [comment]
@Stratus3D 
```shell
~$ asdf which node
No such plugin: node
~$ asdf which nodejs
Version not installed
~$ cd project
~/project$ asdf which node
No such plugin: node
~/project$ asdf which nodejs
~/.asdf/installs/nodejs/8.4.0/bin/nodejs
```

**Comment by jpickwell** [comment]
I'm using asdf v0.6.3 and I get this:

    $ asdf which node
    /Users/jpickwell/.asdf/installs/nodejs/8.15.0/bin/node

**Comment by Stratus3D** [comment]
This is what I see, and it's what I would expect. `which` is for locating binaries, `where` is for locating installed versions.

```
$ asdf which node
~/.asdf/installs/nodejs/8.11.4/bin/node

$ asdf where nodejs
~/.asdf/installs/nodejs/8.11.4
```

I don't see anything on this issue that indicates there is a problem.

**Comment by mclark-newvistas** [comment]
Good thought - updated to `v0.6.3` and updated all plugins, now shows:

```shell
~$ asdf --version
v0.6.3
~$ asdf which node
~/.asdf/lib/commands/which.sh: line 31: [: -eq: unary operator expected
~$ asdf which nodejs
~/.asdf/lib/commands/which.sh: line 31: [: -eq: unary operator expected
~$ asdf where node
No such plugin: node
~$ asdf where nodejs
Version not installed
```

**Comment by alexlafroscia** [comment]
Yeah, looks like this was fixed somewhere along the way. I'm seeing this now

```bash
❯ asdf which node
/Users/alafroscia/.asdf/installs/nodejs/10.13.0/bin/node
```

which is what I'd expect.

**Comment by jsatk** [comment]
I just ran into this issue for the umpteenth time. Normally `asdf reshim` fixes it. It didn't this time. I had to full uninstall and reinstall both the plugin for node and the node version I wanted.

```
asdf plugin remove nodejs
asdf plugin install nodejs
asdf install # which installs the version specified in my ~/.tool-versions file.
```

This bug has been around for years.

**Comment by TranquilMarmot** [comment]
FYI to add a plugin, it is actually

```
asdf plugin-add nodejs
```
