### ISSUE TITLE
Unable to globally install serverless

### ISSUE THREAD

**Issue by axelson** [asdf-vm/asdf-nodejs#73]
Running with latest version of asdf-nodejs and nodejs 8.10.0

Running `npm install -g serverless` I get the following error:

    Jasons-MBP-2% npm install -g serverless
    /Users/jason/.asdf/installs/nodejs/8.10.0/.npm/bin/serverless -> /Users/jason/.asdf/installs/nodejs/8.10.0/.npm/lib/node_modules/serverless/bin/serverless
    /Users/jason/.asdf/installs/nodejs/8.10.0/.npm/bin/sls -> /Users/jason/.asdf/installs/nodejs/8.10.0/.npm/lib/node_modules/serverless/bin/serverless
    /Users/jason/.asdf/installs/nodejs/8.10.0/.npm/bin/slss -> /Users/jason/.asdf/installs/nodejs/8.10.0/.npm/lib/node_modules/serverless/bin/serverless
    npm WARN lifecycle The node binary used for scripts is /Users/jason/.asdf/shims/node but npm is using /Users/jason/.asdf/installs/nodejs/8.10.0/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
    
    > spawn-sync@1.0.15 postinstall /Users/jason/.asdf/installs/nodejs/8.10.0/.npm/lib/node_modules/serverless/node_modules/spawn-sync
    > node postinstall
    
    No version set for nodejs
    npm ERR! code ELIFECYCLE
    npm ERR! errno 255
    npm ERR! spawn-sync@1.0.15 postinstall: `node postinstall`
    npm ERR! Exit status 255
    npm ERR!
    npm ERR! Failed at the spawn-sync@1.0.15 postinstall script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
    
    npm ERR! A complete log of this run can be found in:
    npm ERR!     /Users/jason/.npm/_logs/2018-04-18T00_31_09_624Z-debug.log

From this log the important error seems to be `npm WARN lifecycle The node binary used for scripts is /Users/jason/.asdf/shims/node but npm is using /Users/jason/.asdf/installs/nodejs/8.10.0/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.` and `No version set for nodejs`

It seems that the error might be because serverless's [postInstall](https://github.com/serverless/serverless/blob/86298b6e0ea740f425b74f613b34cf9612ba12bc/scripts/postinstall.js#L30) is running commands like:

    execSync(`node "${tabtabCliPath}" install --name serverless --auto`);

Not sure how to rectify the issue

**Comment by rstacruz** [comment]
> npm WARN lifecycle The node binary used for scripts is /Users/jason/.asdf/shims/node but npm is using /Users/jason/.asdf/installs/nodejs/8.10.0/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

This issue should not be a big deal.

**Comment by rstacruz** [comment]
> No version set for nodejs

1. Can you try `asdf global nodejs 8.10.0` then try again?
2. Okay, so that probably won't work. Can you try `cd /tmp; asdf local nodejs 8.10.0` and then install it again?

If `2` works, then it's probably because serverless is building in `/tmp`, and asdf doesn't have a version of nodejs available for that path.

**Comment by axelson** [comment]
`1` worked for me, thanks!

```
Jasons-MBP-2% npm install -g serverless
/Users/jason/.asdf/installs/nodejs/8.10.0/.npm/bin/slss -> /Users/jason/.asdf/installs/nodejs/8.10.0/.npm/lib/node_modules/serverless/bin/serverless
/Users/jason/.asdf/installs/nodejs/8.10.0/.npm/bin/serverless -> /Users/jason/.asdf/installs/nodejs/8.10.0/.npm/lib/node_modules/serverless/bin/serverless
/Users/jason/.asdf/installs/nodejs/8.10.0/.npm/bin/sls -> /Users/jason/.asdf/installs/nodejs/8.10.0/.npm/lib/node_modules/serverless/bin/serverless
npm WARN lifecycle The node binary used for scripts is /Users/jason/.asdf/shims/node but npm is using /Users/jason/.asdf/installs/nodejs/8.10.0/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> spawn-sync@1.0.15 postinstall /Users/jason/.asdf/installs/nodejs/8.10.0/.npm/lib/node_modules/serverless/node_modules/spawn-sync
> node postinstall


> spawn-sync@1.0.15 postinstall /Users/jason/.asdf/installs/nodejs/8.10.0/.npm/lib/node_modules/serverless/node_modules/spawn-sync
> /Users/jason/.asdf/installs/nodejs/8.10.0/.npm/lib/node_modules/.hooks/postinstall

> serverless@1.27.3 postinstall /Users/jason/.asdf/installs/nodejs/8.10.0/.npm/lib/node_modules/serverless
> node ./scripts/postinstall.js


[tabtab] Adding source line to load /Users/jason/.asdf/installs/nodejs/8.10.0/.npm/lib/node_modules/serverless/node_modules/tabtab/.completions/serverless.zsh
in /Users/jason/.zshrc


[tabtab] Adding source line to load /Users/jason/.asdf/installs/nodejs/8.10.0/.npm/lib/node_modules/serverless/node_modules/tabtab/.completions/sls.zsh
in /Users/jason/.zshrc


> serverless@1.27.3 postinstall /Users/jason/.asdf/installs/nodejs/8.10.0/.npm/lib/node_modules/serverless
> /Users/jason/.asdf/installs/nodejs/8.10.0/.npm/lib/node_modules/.hooks/postinstall
+ serverless@1.27.3
added 310 packages in 18.453s
```

> To @HashNuke and other asdf folks: might I suggest falling back to $HOME/.tool-versions in the event that no .tool-versions is found? There are some npm packages that like to build in /tmp.

That sounds like a good idea to me. Also maybe setting a global version should be recommended more heavily, although if you have 2 different npm versions installed and you want to install a package globally it is annoying to have to switch your `asdf global` to match `asdf current`.

**Comment by Stratus3D** [comment]
> To @HashNuke and other asdf folks: might I suggest falling back to $HOME/.tool-versions in the event that no .tool-versions is found? There are some npm packages that like to build in /tmp.

This should be the case with the recent versions of asdf. I am going to close this issue. Please open a new issue if this problem isn't fully resolved.

**Comment by trishtzy** [comment]
Hi this issues `asdf: No version set for command serverless` persists for nodejs 12.15.0

**Comment by trishtzy** [comment]
Hi this issue `asdf: No version set for command serverless` persists for nodejs 12.15.0

```
$ serverless
asdf: No version set for command serverless
you might want to add one of the following in your .tool-versions file:

nodejs 8.10.0
nodejs 8.14.0
✘-126 ~/Documents/repository-name[master L|✚ 2] 
15:35 $ asdf current
nodejs         12.15.0  (set by /Users/username/.tool-versions)
```

I had to switch back to nodejs 8 for it to work.
