### ISSUE TITLE
[Question] Is asdf suitable for a production environment?

### ISSUE THREAD

**Issue by pachonk** [asdf-vm/asdf-nodejs#75]
I know the way certain version managers work make them not suitable for production environments, but is there any reason to not utilize asdf-vm in a prod env?

**Comment by jmgarnier** [comment]
Good question, I am wondering the same. The README does mention something in https://github.com/asdf-vm/asdf#docker-images

**Comment by mclark-newvistas** [comment]
@pachonk what is it about "certain version managers" that makes them not suitable for production environments? I'm curious for one, and I've poked around in the internals a bit, so I might be able to tell you if this does things similar to whichever have given you trouble in the past.

Other than checking for known issues, this seems small enough that I doubt it'd give many problems itself - though typically I've used this to match `dev` to whatever version production's package manager/etc happens to run. Maybe try it out on your staging servers?

**Comment by pachonk** [comment]
@mclark-newvistas So it actually turns out that deploys using rvm (from the ruby world) and such are prefixing the binary  with `\rvm ruby` and such since most servers run non-interactively the shimming/path changes don't function.
So no, this is not prod ready without having your deployment/services be aware and know how to find the path to ruby in terms of asdf

**Comment by Stratus3D** [comment]
Nothing inherently makes asdf unsuitable for production environments. But it was designed for local development, when multiple versions of the same language need to be used, and the developer needs to quickly switch between language versions. Most of the time production environments do not need multiple versions of the same language installed or running. But if it's needed it could be used. Just be aware the shims can take anywhere from a couple milliseconds to several hundred milliseconds to select the right version so there will be some overhead.
