### ISSUE TITLE
Should build from sources if the OS has no binaries available

### ISSUE THREAD

**Issue by ejpcmac** [asdf-vm/asdf-nodejs#78]
Reading quickly the install script, it seems that `asdf-nodejs` only installs from binaries when installing a given version. This causes `asdf install nodejs <version>` to fail on FreeBSD.

## Proposal

If the host OS or architecture has no precompiled binaries available, `asdf-nodejs` should fetch the given version archive and build it from sources.

**Comment by toriumi0118** [comment]
use `ref:v1.2.3` at the `<version>`.
[asdf mentioned like this.](https://github.com/asdf-vm/asdf#manage-versions)

When you install with `ref:`, the asdf-nodejs will try getting source code from github.
but github does not provide checksum file, so you need to ignore it with `NODEJS_CHECK_SIGNATURES='no' option.

[download from github](https://github.com/asdf-vm/asdf-nodejs/blob/master/bin/install#L131)
[ignore checksum](https://github.com/asdf-vm/asdf-nodejs/blob/master/bin/install#L156)

so in my case. I had to compile nodejs with `full-icu`.
I used it like this (it worked on fish shell).

```
env NODEJS_CONFIGURE_OPTIONS='--with-intl=full-icu --download=all' env NODEJS_CHECK_SIGNATURES='no' asdf install nodejs ref:v10.7.0
```

then you can get `ref:v10.7.0` version.

**Comment by wesleycoder** [comment]
There is any intent to fix this issue?
It has over a year and a half and it is still affecting users...

**Comment by desnudopenguino** [comment]
> There is any intent to fix this issue?
> It has over a year and a half and it is still affecting users...

yeah, i just jumped on the asdf train on OpenBSD. it works well for the other languages i use, but node is "broken". the error message is a bit misleading as well. "Binaries were not found. Full version must be specified, not just major version." it took a little reading to figure out the actual issue (the archive was not found for my OS). i'm willing to put in some time to work on it.  @toriumi0118 has a good solution, but that takes some digging to find it here in the issues. perhaps those pieces could be rolled into the script for non-supported OS's and/or a better error message implemented.

**Comment by Stratus3D** [comment]
I'm open to contributions for this. I don't think it would be terribly hard to improve things so we try to compile from source if an archive is not found for your distro. I'm happy to review any PRs for this, but as someone who doesn't use Node.JS every day implementing this feature on my own is not a priority.

**Comment by toothbrush** [comment]
Just to add a comment here, in my case it'd be really nice to have a "force compilation from source" flag, too.  The thing is that i'm using NixOS, which is exotic in many ways, but in my case the precompiled NodeJS binary for Linux doesn't work.  But the `ref:...` is probably an acceptable workaround.

**Comment by jaydorsey** [comment]
I stumbled across this while trying to get nodejs to install on an m1.

The ref syntax doesn't seem to work any more. The README reference linked above is replaced and the new docs only show a [latest](https://asdf-vm.com/#/core-manage-versions?id=install-latest-stable-version) syntax; so the below doesn't work

    asdf install nodejs ref:14.15.4

I don't have a solution but hopefully this helps someone who might have spent time trying this.

**Comment by smh** [comment]
@jaydorsey this should work:
```
asdf install nodejs ref:v14.15.4
```
Note the additional `v` in front of the version number. Specifically the following command worked for me:
```
env NODEJS_CONFIGURE_OPTIONS='--with-intl=full-icu --download=all' env NODEJS_CHECK_SIGNATURES='no' asdf install nodejs ref:v15.8.0
```

**Comment by jaydorsey** [comment]
> ```
> env NODEJS_CONFIGURE_OPTIONS='--with-intl=full-icu --download=all' env NODEJS_CHECK_SIGNATURES='no' asdf install nodejs ref:v15.8.0
> ```

This does seem to work (it's been ~45 minutes and still building!). This might be useful to spit out as an error/warning/info message when a binary can't be found. I noted it also has to be run exactly as you typed (with `env` which was something I didn't catch before)

If no one else grabs this, I might attempt a small PR. Displaying the above command when it can't find any binaries would have been useful enough.

**Comment by plicjo** [comment]
@jaydorsey oh snap. You dropped this 👑

**Comment by igor47** [comment]
on an M1 macbook, this worked for me:
```
NODEJS_CONFIGURE_OPTIONS='--with-intl=full-icu --download=all' NODEJS_CHECK_SIGNATURES="no" asdf install nodejs ref:v15.7.0
```

without the `NODEJS_CHECK_SIGNATURES="no"`, it failed silently (no output, but non-zero exit code). took maybe 10 minutes to build. afterwards, asdf doesn't realize that `15.7.0` is installed. i did:
```
cd ~/.asdf/installs/nodejs
ln -s ref-v15.7.0 15.7.0
```
so i can be compatible with existing `.nvmrc`/`.node_version` files

**Comment by pawelgalazka** [comment]
thx @igor47 this works for m1 with one exception, trick with `ln -s ref-v15.7.0 15.7.0` does not seem to work for me. I created symlink but I still get an error:

```
$ node -v
No preset version installed for command node
Please install a version by running one of the following:

asdf install nodejs 15.7.0

or add one of the following versions in your config file at /Users/myusername/.tool-versions
nodejs ref:v15.7.0
```

```
$ cat ~/.tool-versions 
nodejs 15.7.0
```

```
$ ls -l ~/.asdf/installs/nodejs
total 0
lrwxr-xr-x   1 myusername  staff    11 13 Aug 11:53 15.7.0 -> ref-v15.7.0
drwxr-xr-x  50 myusername  staff  1600 13 Aug 11:52 ref-v15.7.0
```

**Comment by abradburne** [comment]
@pawelgalazka A `asdf reshim` fixed that issue for me.

**Comment by pawelgalazka** [comment]
thx @abradburne that helped 🙏

**Comment by maxirby** [comment]
I installed from source (using this command above) node 14.8.1, but I cannot push asdf to use that.

Output: No version set for command node

any help?

**Comment by jaydorsey** [comment]
> I installed from source (using this command above) node 14.8.1, but I cannot push asdf to use that.
> 
> Output: No version set for command node
> 
> any help?

An `asdf reshim nodejs` usually resolves this for me. Ruby and a couple of the other plugins work fine without the reshim afaict.
