### ISSUE TITLE
Issue with `node-gyp rebuild`

### ISSUE THREAD

**Issue by adamyonk** [asdf-vm/asdf-nodejs#81]
I'm having this crazy problem where only this one module blows up when trying to do a `node-gyp rebuild`. It seems to be asdf-related, because if I switch over to nvm, I don't have this problem and everything installs fine. I can't for the life of me figure out what is different about this setup that would cause this. ¯\_(ツ)_/¯

```
❯ npm i keyboard-layout@2.0.12
npm WARN lifecycle The node binary used for scripts is /Users/adam/.asdf/shims/node but npm is using /Users/adam/.asdf/installs/nodejs/8.9.4/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> keyboard-layout@2.0.12 install /private/tmp/dummy/node_modules/keyboard-layout
> node-gyp rebuild

nodejs 0.11.13 not installed
npm WARN dummy@1.0.0 No description
npm WARN dummy@1.0.0 No repository field.

npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! keyboard-layout@2.0.12 install: `node-gyp rebuild`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the keyboard-layout@2.0.12 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/adam/.npm/_logs/2018-06-14T00_13_51_842Z-debug.log
```

```
❯ npm doctor
Check                               Value                        Recommendation
npm ping                            OK
npm -v                              v5.6.0                       Use npm v6.1.0
node -v                             v8.9.4                       Use node v8.11.3
npm config get registry             https://registry.npmjs.org/
which git                           /usr/local/bin/git
Perms check on cached files         ok
Perms check on global node_modules  ok
Perms check on local node_modules   ok
Verify cache contents               verified 2008 tarballs
```

<details>
<summary>Click to expand 2018-06-14T00_13_51_842Z-debug.log</summary>
<code><pre>0 info it worked if it ends with ok
1 verbose cli [ '/Users/adam/.asdf/installs/nodejs/8.9.4/bin/node',
1 verbose cli   '/Users/adam/.asdf/installs/nodejs/8.9.4/bin/npm',
1 verbose cli   'i',
1 verbose cli   'keyboard-layout@2.0.12' ]
2 info using npm@5.6.0
3 info using node@v8.9.4
4 verbose npm-session 647e1bf826b375d2
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://registry.npmjs.org/keyboard-layout 12ms (from cache)
8 silly pacote version manifest for keyboard-layout@2.0.12 fetched in 36ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly install loadAllDepsIntoIdealTree
13 silly resolveWithNewModule keyboard-layout@2.0.12 checking installable status
14 http fetch GET 200 https://registry.npmjs.org/nan 4ms (from cache)
15 http fetch GET 200 https://registry.npmjs.org/event-kit 6ms (from cache)
16 silly pacote range manifest for nan@^2.0.0 fetched in 6ms
17 silly resolveWithNewModule nan@2.10.0 checking installable status
18 silly pacote range manifest for event-kit@^1.0.0 fetched in 8ms
19 silly resolveWithNewModule event-kit@1.5.0 checking installable status
20 http fetch GET 200 https://registry.npmjs.org/grim 2ms (from cache)
21 silly pacote range manifest for grim@^1.2.1 fetched in 3ms
22 silly resolveWithNewModule grim@1.5.0 checking installable status
23 http fetch GET 200 https://registry.npmjs.org/emissary 1ms (from cache)
24 silly pacote range manifest for emissary@^1.2.0 fetched in 2ms
25 silly resolveWithNewModule emissary@1.3.3 checking installable status
26 http fetch GET 200 https://registry.npmjs.org/underscore-plus 12ms (from cache)
27 http fetch GET 200 https://registry.npmjs.org/mixto 10ms (from cache)
28 http fetch GET 200 https://registry.npmjs.org/property-accessors 10ms (from cache)
29 http fetch GET 200 https://registry.npmjs.org/es6-weak-map 11ms (from cache)
30 silly pacote range manifest for underscore-plus@1.x fetched in 14ms
31 silly resolveWithNewModule underscore-plus@1.6.8 checking installable status
32 silly pacote range manifest for mixto@1.x fetched in 13ms
33 silly resolveWithNewModule mixto@1.0.0 checking installable status
34 silly pacote range manifest for property-accessors@^1.1 fetched in 13ms
35 silly resolveWithNewModule property-accessors@1.1.3 checking installable status
36 silly pacote range manifest for es6-weak-map@^0.1.2 fetched in 13ms
37 silly resolveWithNewModule es6-weak-map@0.1.4 checking installable status
38 http fetch GET 200 https://registry.npmjs.org/d 3ms (from cache)
39 http fetch GET 200 https://registry.npmjs.org/es6-iterator 3ms (from cache)
40 http fetch GET 200 https://registry.npmjs.org/es6-symbol 3ms (from cache)
41 silly pacote range manifest for d@~0.1.1 fetched in 4ms
42 silly resolveWithNewModule d@0.1.1 checking installable status
43 silly pacote range manifest for es6-iterator@~0.1.3 fetched in 4ms
44 silly resolveWithNewModule es6-iterator@0.1.3 checking installable status
45 silly pacote range manifest for es6-symbol@~2.0.1 fetched in 5ms
46 silly resolveWithNewModule es6-symbol@2.0.1 checking installable status
47 http fetch GET 200 https://registry.npmjs.org/underscore 2ms (from cache)
48 silly pacote range manifest for underscore@~1.8.3 fetched in 3ms
49 silly resolveWithNewModule underscore@1.8.3 checking installable status
50 silly currentTree dummy@1.0.0
50 silly currentTree ├─┬ es5-ext@0.10.45
50 silly currentTree │ ├── d@1.0.0
50 silly currentTree │ ├── es6-iterator@2.0.3
50 silly currentTree │ └── es6-symbol@3.1.1
50 silly currentTree └── next-tick@1.0.0
51 silly idealTree dummy@1.0.0
51 silly idealTree ├── d@0.1.1
51 silly idealTree ├── emissary@1.3.3
51 silly idealTree ├─┬ es5-ext@0.10.45
51 silly idealTree │ ├── d@1.0.0
51 silly idealTree │ ├── es6-iterator@2.0.3
51 silly idealTree │ └── es6-symbol@3.1.1
51 silly idealTree ├── es6-iterator@0.1.3
51 silly idealTree ├── es6-symbol@2.0.1
51 silly idealTree ├── es6-weak-map@0.1.4
51 silly idealTree ├── event-kit@1.5.0
51 silly idealTree ├── grim@1.5.0
51 silly idealTree ├── keyboard-layout@2.0.12
51 silly idealTree ├── mixto@1.0.0
51 silly idealTree ├── nan@2.10.0
51 silly idealTree ├── next-tick@1.0.0
51 silly idealTree ├── property-accessors@1.1.3
51 silly idealTree ├── underscore-plus@1.6.8
51 silly idealTree └── underscore@1.8.3
52 silly install generateActionsToTake
53 silly diffTrees action count 13
54 silly diffTrees add d@0.1.1
55 silly diffTrees add es6-symbol@2.0.1
56 silly diffTrees add es6-iterator@0.1.3
57 silly diffTrees add es6-weak-map@0.1.4
58 silly diffTrees add mixto@1.0.0
59 silly diffTrees add property-accessors@1.1.3
60 silly diffTrees add underscore@1.8.3
61 silly diffTrees add underscore-plus@1.6.8
62 silly diffTrees add emissary@1.3.3
63 silly diffTrees add grim@1.5.0
64 silly diffTrees add event-kit@1.5.0
65 silly diffTrees add nan@2.10.0
66 silly diffTrees add keyboard-layout@2.0.12
67 silly decomposeActions action count 104
68 silly decomposeActions fetch d@0.1.1
69 silly decomposeActions extract d@0.1.1
70 silly decomposeActions preinstall d@0.1.1
71 silly decomposeActions build d@0.1.1
72 silly decomposeActions install d@0.1.1
73 silly decomposeActions postinstall d@0.1.1
74 silly decomposeActions finalize d@0.1.1
75 silly decomposeActions refresh-package-json d@0.1.1
76 silly decomposeActions fetch es6-symbol@2.0.1
77 silly decomposeActions extract es6-symbol@2.0.1
78 silly decomposeActions preinstall es6-symbol@2.0.1
79 silly decomposeActions build es6-symbol@2.0.1
80 silly decomposeActions install es6-symbol@2.0.1
81 silly decomposeActions postinstall es6-symbol@2.0.1
82 silly decomposeActions finalize es6-symbol@2.0.1
83 silly decomposeActions refresh-package-json es6-symbol@2.0.1
84 silly decomposeActions fetch es6-iterator@0.1.3
85 silly decomposeActions extract es6-iterator@0.1.3
86 silly decomposeActions preinstall es6-iterator@0.1.3
87 silly decomposeActions build es6-iterator@0.1.3
88 silly decomposeActions install es6-iterator@0.1.3
89 silly decomposeActions postinstall es6-iterator@0.1.3
90 silly decomposeActions finalize es6-iterator@0.1.3
91 silly decomposeActions refresh-package-json es6-iterator@0.1.3
92 silly decomposeActions fetch es6-weak-map@0.1.4
93 silly decomposeActions extract es6-weak-map@0.1.4
94 silly decomposeActions preinstall es6-weak-map@0.1.4
95 silly decomposeActions build es6-weak-map@0.1.4
96 silly decomposeActions install es6-weak-map@0.1.4
97 silly decomposeActions postinstall es6-weak-map@0.1.4
98 silly decomposeActions finalize es6-weak-map@0.1.4
99 silly decomposeActions refresh-package-json es6-weak-map@0.1.4
100 silly decomposeActions fetch mixto@1.0.0
101 silly decomposeActions extract mixto@1.0.0
102 silly decomposeActions preinstall mixto@1.0.0
103 silly decomposeActions build mixto@1.0.0
104 silly decomposeActions install mixto@1.0.0
105 silly decomposeActions postinstall mixto@1.0.0
106 silly decomposeActions finalize mixto@1.0.0
107 silly decomposeActions refresh-package-json mixto@1.0.0
108 silly decomposeActions fetch property-accessors@1.1.3
109 silly decomposeActions extract property-accessors@1.1.3
110 silly decomposeActions preinstall property-accessors@1.1.3
111 silly decomposeActions build property-accessors@1.1.3
112 silly decomposeActions install property-accessors@1.1.3
113 silly decomposeActions postinstall property-accessors@1.1.3
114 silly decomposeActions finalize property-accessors@1.1.3
115 silly decomposeActions refresh-package-json property-accessors@1.1.3
116 silly decomposeActions fetch underscore@1.8.3
117 silly decomposeActions extract underscore@1.8.3
118 silly decomposeActions preinstall underscore@1.8.3
119 silly decomposeActions build underscore@1.8.3
120 silly decomposeActions install underscore@1.8.3
121 silly decomposeActions postinstall underscore@1.8.3
122 silly decomposeActions finalize underscore@1.8.3
123 silly decomposeActions refresh-package-json underscore@1.8.3
124 silly decomposeActions fetch underscore-plus@1.6.8
125 silly decomposeActions extract underscore-plus@1.6.8
126 silly decomposeActions preinstall underscore-plus@1.6.8
127 silly decomposeActions build underscore-plus@1.6.8
128 silly decomposeActions install underscore-plus@1.6.8
129 silly decomposeActions postinstall underscore-plus@1.6.8
130 silly decomposeActions finalize underscore-plus@1.6.8
131 silly decomposeActions refresh-package-json underscore-plus@1.6.8
132 silly decomposeActions fetch emissary@1.3.3
133 silly decomposeActions extract emissary@1.3.3
134 silly decomposeActions preinstall emissary@1.3.3
135 silly decomposeActions build emissary@1.3.3
136 silly decomposeActions install emissary@1.3.3
137 silly decomposeActions postinstall emissary@1.3.3
138 silly decomposeActions finalize emissary@1.3.3
139 silly decomposeActions refresh-package-json emissary@1.3.3
140 silly decomposeActions fetch grim@1.5.0
141 silly decomposeActions extract grim@1.5.0
142 silly decomposeActions preinstall grim@1.5.0
143 silly decomposeActions build grim@1.5.0
144 silly decomposeActions install grim@1.5.0
145 silly decomposeActions postinstall grim@1.5.0
146 silly decomposeActions finalize grim@1.5.0
147 silly decomposeActions refresh-package-json grim@1.5.0
148 silly decomposeActions fetch event-kit@1.5.0
149 silly decomposeActions extract event-kit@1.5.0
150 silly decomposeActions preinstall event-kit@1.5.0
151 silly decomposeActions build event-kit@1.5.0
152 silly decomposeActions install event-kit@1.5.0
153 silly decomposeActions postinstall event-kit@1.5.0
154 silly decomposeActions finalize event-kit@1.5.0
155 silly decomposeActions refresh-package-json event-kit@1.5.0
156 silly decomposeActions fetch nan@2.10.0
157 silly decomposeActions extract nan@2.10.0
158 silly decomposeActions preinstall nan@2.10.0
159 silly decomposeActions build nan@2.10.0
160 silly decomposeActions install nan@2.10.0
161 silly decomposeActions postinstall nan@2.10.0
162 silly decomposeActions finalize nan@2.10.0
163 silly decomposeActions refresh-package-json nan@2.10.0
164 silly decomposeActions fetch keyboard-layout@2.0.12
165 silly decomposeActions extract keyboard-layout@2.0.12
166 silly decomposeActions preinstall keyboard-layout@2.0.12
167 silly decomposeActions build keyboard-layout@2.0.12
168 silly decomposeActions install keyboard-layout@2.0.12
169 silly decomposeActions postinstall keyboard-layout@2.0.12
170 silly decomposeActions finalize keyboard-layout@2.0.12
171 silly decomposeActions refresh-package-json keyboard-layout@2.0.12
172 silly install executeActions
173 silly doSerial global-install 104
174 verbose correctMkdir /Users/adam/.npm/_locks correctMkdir not in flight; initializing
175 verbose lock using /Users/adam/.npm/_locks/staging-9b558a35c3408069.lock for /private/tmp/dummy/node_modules/.staging
176 silly doParallel extract 104
177 silly extract d@0.1.1
178 silly extract es6-symbol@2.0.1
179 silly extract es6-iterator@0.1.3
180 silly extract es6-weak-map@0.1.4
181 silly extract mixto@1.0.0
182 silly extract property-accessors@1.1.3
183 silly extract underscore@1.8.3
184 silly extract underscore-plus@1.6.8
185 silly extract emissary@1.3.3
186 silly extract grim@1.5.0
187 silly extract event-kit@1.5.0
188 silly extract nan@2.10.0
189 silly extract keyboard-layout@2.0.12
190 silly doReverseSerial unbuild 104
191 silly doSerial remove 104
192 silly doSerial move 104
193 silly doSerial finalize 104
194 silly finalize /private/tmp/dummy/node_modules/d
195 silly finalize /private/tmp/dummy/node_modules/es6-symbol
196 silly finalize /private/tmp/dummy/node_modules/es6-iterator
197 silly finalize /private/tmp/dummy/node_modules/es6-weak-map
198 silly finalize /private/tmp/dummy/node_modules/mixto
199 silly finalize /private/tmp/dummy/node_modules/property-accessors
200 silly finalize /private/tmp/dummy/node_modules/underscore
201 silly finalize /private/tmp/dummy/node_modules/underscore-plus
202 silly finalize /private/tmp/dummy/node_modules/emissary
203 silly finalize /private/tmp/dummy/node_modules/grim
204 silly finalize /private/tmp/dummy/node_modules/event-kit
205 silly finalize /private/tmp/dummy/node_modules/nan
206 silly finalize /private/tmp/dummy/node_modules/keyboard-layout
207 silly doParallel refresh-package-json 104
208 silly refresh-package-json /private/tmp/dummy/node_modules/d
209 silly refresh-package-json /private/tmp/dummy/node_modules/es6-symbol
210 silly refresh-package-json /private/tmp/dummy/node_modules/es6-iterator
211 silly refresh-package-json /private/tmp/dummy/node_modules/es6-weak-map
212 silly refresh-package-json /private/tmp/dummy/node_modules/mixto
213 silly refresh-package-json /private/tmp/dummy/node_modules/property-accessors
214 silly refresh-package-json /private/tmp/dummy/node_modules/underscore
215 silly refresh-package-json /private/tmp/dummy/node_modules/underscore-plus
216 silly refresh-package-json /private/tmp/dummy/node_modules/emissary
217 silly refresh-package-json /private/tmp/dummy/node_modules/grim
218 silly refresh-package-json /private/tmp/dummy/node_modules/event-kit
219 silly refresh-package-json /private/tmp/dummy/node_modules/nan
220 silly refresh-package-json /private/tmp/dummy/node_modules/keyboard-layout
221 silly doParallel preinstall 104
222 silly preinstall d@0.1.1
223 info lifecycle d@0.1.1~preinstall: d@0.1.1
224 silly preinstall es6-symbol@2.0.1
225 info lifecycle es6-symbol@2.0.1~preinstall: es6-symbol@2.0.1
226 silly preinstall es6-iterator@0.1.3
227 info lifecycle es6-iterator@0.1.3~preinstall: es6-iterator@0.1.3
228 silly preinstall es6-weak-map@0.1.4
229 info lifecycle es6-weak-map@0.1.4~preinstall: es6-weak-map@0.1.4
230 silly preinstall mixto@1.0.0
231 info lifecycle mixto@1.0.0~preinstall: mixto@1.0.0
232 silly preinstall property-accessors@1.1.3
233 info lifecycle property-accessors@1.1.3~preinstall: property-accessors@1.1.3
234 silly preinstall underscore@1.8.3
235 info lifecycle underscore@1.8.3~preinstall: underscore@1.8.3
236 silly preinstall underscore-plus@1.6.8
237 info lifecycle underscore-plus@1.6.8~preinstall: underscore-plus@1.6.8
238 silly preinstall emissary@1.3.3
239 info lifecycle emissary@1.3.3~preinstall: emissary@1.3.3
240 silly preinstall grim@1.5.0
241 info lifecycle grim@1.5.0~preinstall: grim@1.5.0
242 silly preinstall event-kit@1.5.0
243 info lifecycle event-kit@1.5.0~preinstall: event-kit@1.5.0
244 silly preinstall nan@2.10.0
245 info lifecycle nan@2.10.0~preinstall: nan@2.10.0
246 silly preinstall keyboard-layout@2.0.12
247 info lifecycle keyboard-layout@2.0.12~preinstall: keyboard-layout@2.0.12
248 silly doSerial build 104
249 silly build d@0.1.1
250 info linkStuff d@0.1.1
251 silly linkStuff d@0.1.1 has /private/tmp/dummy/node_modules as its parent node_modules
252 verbose linkBins d@0.1.1
253 verbose linkMans d@0.1.1
254 silly build es6-symbol@2.0.1
255 info linkStuff es6-symbol@2.0.1
256 silly linkStuff es6-symbol@2.0.1 has /private/tmp/dummy/node_modules as its parent node_modules
257 verbose linkBins es6-symbol@2.0.1
258 verbose linkMans es6-symbol@2.0.1
259 silly build es6-iterator@0.1.3
260 info linkStuff es6-iterator@0.1.3
261 silly linkStuff es6-iterator@0.1.3 has /private/tmp/dummy/node_modules as its parent node_modules
262 verbose linkBins es6-iterator@0.1.3
263 verbose linkMans es6-iterator@0.1.3
264 silly build es6-weak-map@0.1.4
265 info linkStuff es6-weak-map@0.1.4
266 silly linkStuff es6-weak-map@0.1.4 has /private/tmp/dummy/node_modules as its parent node_modules
267 verbose linkBins es6-weak-map@0.1.4
268 verbose linkMans es6-weak-map@0.1.4
269 silly build mixto@1.0.0
270 info linkStuff mixto@1.0.0
271 silly linkStuff mixto@1.0.0 has /private/tmp/dummy/node_modules as its parent node_modules
272 verbose linkBins mixto@1.0.0
273 verbose linkMans mixto@1.0.0
274 silly build property-accessors@1.1.3
275 info linkStuff property-accessors@1.1.3
276 silly linkStuff property-accessors@1.1.3 has /private/tmp/dummy/node_modules as its parent node_modules
277 verbose linkBins property-accessors@1.1.3
278 verbose linkMans property-accessors@1.1.3
279 silly build underscore@1.8.3
280 info linkStuff underscore@1.8.3
281 silly linkStuff underscore@1.8.3 has /private/tmp/dummy/node_modules as its parent node_modules
282 verbose linkBins underscore@1.8.3
283 verbose linkMans underscore@1.8.3
284 silly build underscore-plus@1.6.8
285 info linkStuff underscore-plus@1.6.8
286 silly linkStuff underscore-plus@1.6.8 has /private/tmp/dummy/node_modules as its parent node_modules
287 verbose linkBins underscore-plus@1.6.8
288 verbose linkMans underscore-plus@1.6.8
289 silly build emissary@1.3.3
290 info linkStuff emissary@1.3.3
291 silly linkStuff emissary@1.3.3 has /private/tmp/dummy/node_modules as its parent node_modules
292 verbose linkBins emissary@1.3.3
293 verbose linkMans emissary@1.3.3
294 silly build grim@1.5.0
295 info linkStuff grim@1.5.0
296 silly linkStuff grim@1.5.0 has /private/tmp/dummy/node_modules as its parent node_modules
297 verbose linkBins grim@1.5.0
298 verbose linkMans grim@1.5.0
299 silly build event-kit@1.5.0
300 info linkStuff event-kit@1.5.0
301 silly linkStuff event-kit@1.5.0 has /private/tmp/dummy/node_modules as its parent node_modules
302 verbose linkBins event-kit@1.5.0
303 verbose linkMans event-kit@1.5.0
304 silly build nan@2.10.0
305 info linkStuff nan@2.10.0
306 silly linkStuff nan@2.10.0 has /private/tmp/dummy/node_modules as its parent node_modules
307 verbose linkBins nan@2.10.0
308 verbose linkMans nan@2.10.0
309 silly build keyboard-layout@2.0.12
310 info linkStuff keyboard-layout@2.0.12
311 silly linkStuff keyboard-layout@2.0.12 has /private/tmp/dummy/node_modules as its parent node_modules
312 verbose linkBins keyboard-layout@2.0.12
313 verbose linkMans keyboard-layout@2.0.12
314 silly doSerial global-link 104
315 silly doParallel update-linked 104
316 silly doSerial install 104
317 silly install d@0.1.1
318 info lifecycle d@0.1.1~install: d@0.1.1
319 silly install es6-symbol@2.0.1
320 info lifecycle es6-symbol@2.0.1~install: es6-symbol@2.0.1
321 silly install es6-iterator@0.1.3
322 info lifecycle es6-iterator@0.1.3~install: es6-iterator@0.1.3
323 silly install es6-weak-map@0.1.4
324 info lifecycle es6-weak-map@0.1.4~install: es6-weak-map@0.1.4
325 silly install mixto@1.0.0
326 info lifecycle mixto@1.0.0~install: mixto@1.0.0
327 silly install property-accessors@1.1.3
328 info lifecycle property-accessors@1.1.3~install: property-accessors@1.1.3
329 silly install underscore@1.8.3
330 info lifecycle underscore@1.8.3~install: underscore@1.8.3
331 silly install underscore-plus@1.6.8
332 info lifecycle underscore-plus@1.6.8~install: underscore-plus@1.6.8
333 silly install emissary@1.3.3
334 info lifecycle emissary@1.3.3~install: emissary@1.3.3
335 silly install grim@1.5.0
336 info lifecycle grim@1.5.0~install: grim@1.5.0
337 silly install event-kit@1.5.0
338 info lifecycle event-kit@1.5.0~install: event-kit@1.5.0
339 silly install nan@2.10.0
340 info lifecycle nan@2.10.0~install: nan@2.10.0
341 silly install keyboard-layout@2.0.12
342 info lifecycle keyboard-layout@2.0.12~install: keyboard-layout@2.0.12
343 warn lifecycle The node binary used for scripts is /Users/adam/.asdf/shims/node but npm is using /Users/adam/.asdf/installs/nodejs/8.9.4/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
344 verbose lifecycle keyboard-layout@2.0.12~install: unsafe-perm in lifecycle true
345 verbose lifecycle keyboard-layout@2.0.12~install: PATH: /Users/adam/.asdf/installs/nodejs/8.9.4/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/private/tmp/dummy/node_modules/keyboard-layout/node_modules/.bin:/private/tmp/dummy/node_modules/.bin:/Users/adam/.asdf/shims:/Users/adam/.asdf/bin:.git/safe/../../scripts:/Users/adam/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/Users/adam/.fzf/bin:/Users/adam/Code/go/bin:/usr/local/heroku/bin:/Users/adamyonk/.cargo/bin
346 verbose lifecycle keyboard-layout@2.0.12~install: CWD: /private/tmp/dummy/node_modules/keyboard-layout
347 silly lifecycle keyboard-layout@2.0.12~install: Args: [ '-c', 'node-gyp rebuild' ]
348 info lifecycle keyboard-layout@2.0.12~install: Failed to exec install script
349 verbose unlock done using /Users/adam/.npm/_locks/staging-9b558a35c3408069.lock for /private/tmp/dummy/node_modules/.staging
350 silly saveTree dummy@1.0.0
350 silly saveTree └─┬ keyboard-layout@2.0.12
350 silly saveTree   ├─┬ event-kit@1.5.0
350 silly saveTree   │ └─┬ grim@1.5.0
350 silly saveTree   │   └─┬ emissary@1.3.3
350 silly saveTree   │     ├─┬ es6-weak-map@0.1.4
350 silly saveTree   │     │ ├─┬ d@0.1.1
350 silly saveTree   │     │ │ └─┬ es5-ext@0.10.45
350 silly saveTree   │     │ │   ├─┬ es6-iterator@2.0.3
350 silly saveTree   │     │ │   │ ├── d@1.0.0
350 silly saveTree   │     │ │   │ └── es6-symbol@3.1.1
350 silly saveTree   │     │ │   ├── es6-symbol@3.1.1
350 silly saveTree   │     │ │   └── next-tick@1.0.0
350 silly saveTree   │     │ ├── es5-ext@0.10.45
350 silly saveTree   │     │ ├─┬ es6-iterator@0.1.3
350 silly saveTree   │     │ │ └── es6-symbol@2.0.1
350 silly saveTree   │     │ └── es6-symbol@2.0.1
350 silly saveTree   │     ├── mixto@1.0.0
350 silly saveTree   │     ├── property-accessors@1.1.3
350 silly saveTree   │     └─┬ underscore-plus@1.6.8
350 silly saveTree   │       └── underscore@1.8.3
350 silly saveTree   └── nan@2.10.0
351 warn dummy@1.0.0 No description
352 warn dummy@1.0.0 No repository field.
353 verbose stack Error: keyboard-layout@2.0.12 install: `node-gyp rebuild`
353 verbose stack spawn ENOENT
353 verbose stack     at ChildProcess.<anonymous> (/Users/adam/.asdf/installs/nodejs/8.9.4/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
353 verbose stack     at emitTwo (events.js:126:13)
353 verbose stack     at ChildProcess.emit (events.js:214:7)
353 verbose stack     at maybeClose (internal/child_process.js:925:16)
353 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
354 verbose pkgid keyboard-layout@2.0.12
355 verbose cwd /private/tmp/dummy
356 verbose Darwin 17.6.0
357 verbose argv "/Users/adam/.asdf/installs/nodejs/8.9.4/bin/node" "/Users/adam/.asdf/installs/nodejs/8.9.4/bin/npm" "i" "keyboard-layout@2.0.12"
358 verbose node v8.9.4
359 verbose npm  v5.6.0
360 error file sh
361 error code ELIFECYCLE
362 error errno ENOENT
363 error syscall spawn
364 error keyboard-layout@2.0.12 install: `node-gyp rebuild`
364 error spawn ENOENT
365 error Failed at the keyboard-layout@2.0.12 install script.
365 error This is probably not a problem with npm. There is likely additional logging output above.
366 verbose exit [ 1, true ]</pre></code>
</details>

**Comment by amejiarosario** [comment]
I have a similar issue trying to install `x509`

```sh
$ npm install x509

npm WARN lifecycle The node binary used for scripts is /Users/admejiar/.asdf/shims/node but npm is using /Users/admejiar/.asdf/installs/nodejs/6.11.1/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> x509@0.2.6 install /Users/admejiar/Code/lockhart/lar/node_modules/x509
> node-gyp rebuild

  CXX(target) Release/obj.target/x509/src/addon.o
warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead
      [-Wstdlibcxx-not-found]
../src/addon.cc:1:10: fatal error: 'cstdlib' file not found
#include <cstdlib>
         ^~~~~~~~~
1 warning and 1 error generated.
make: *** [Release/obj.target/x509/src/addon.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/admejiar/.asdf/installs/nodejs/6.11.1/.npm/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 18.0.0
gyp ERR! command "/Users/admejiar/.asdf/installs/nodejs/6.11.1/bin/node" "/Users/admejiar/.asdf/installs/nodejs/6.11.1/.npm/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/admejiar/Code/lockhart/lar/node_modules/x509
gyp ERR! node -v v6.11.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! x509@0.2.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the x509@0.2.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/admejiar/.npm/_logs/2018-11-01T01_31_45_824Z-debug.log
```

**Comment by Stratus3D** [comment]
@amejiarosario it looks like your install failed because it couldn't find `stdlibc++ headers`, have you confirmed they are present on your system? This is not an issue with asdf-nodejs since it is not responsible for installing package dependencies.

@adamyonk can see if upgrading to the latest version of asdf and asdf-nodejs fixes your issue?

**Comment by amejiarosario** [comment]
@Stratus3D yes, after installing XCode 10 I got it working. It included the `stdlibc` libs

**Comment by adamyonk** [comment]
Got the latest, still seeing that output. Here is the output from `npm i -d`:
```
npm info it worked if it ends with ok
npm info using npm@6.4.1
npm info using node@v8.15.0
npm info lifecycle -----@0.0.0~preinstall: -----@0.0.0
npm timing stage:loadCurrentTree Completed in 1068ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 7ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 3104ms
npm timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 6400ms
npm timing stage:loadIdealTree Completed in 12327ms
npm timing stage:generateActionsToTake Completed in 131ms
npm timing audit compress Completed in 36ms
npm info audit Submitting payload of 33458bytes
npm timing action:extract Completed in 542ms
npm timing action:finalize Completed in 11ms
npm timing action:refresh-package-json Completed in 11ms
npm info lifecycle event-kit@2.5.3~preinstall: event-kit@2.5.3
npm info lifecycle keyboard-layout@2.0.14~preinstall: keyboard-layout@2.0.14
npm info lifecycle atom-keymap@8.2.12~preinstall: atom-keymap@8.2.12
npm timing action:preinstall Completed in 1ms
npm info linkStuff event-kit@2.5.3
npm info linkStuff keyboard-layout@2.0.14
npm info linkStuff atom-keymap@8.2.12
npm timing action:build Completed in 3ms
npm info lifecycle event-kit@2.5.3~install: event-kit@2.5.3
npm info lifecycle keyboard-layout@2.0.14~install: keyboard-layout@2.0.14
npm WARN lifecycle The node binary used for scripts is /Users/adam/.asdf/shims/node but npm is using /Users/adam/.asdf/installs/nodejs/8.15.0/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> keyboard-layout@2.0.14 install /Users/adam/Code/trapezoid-app/dist/node_modules/keyboard-layout
> node-gyp rebuild

nodejs 0.11.13 not installed
npm timing audit submit Completed in 618ms
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 504ms
npm timing audit body Completed in 1ms
npm info lifecycle keyboard-layout@2.0.14~install: Failed to exec install script
npm timing action:install Completed in 131ms
npm timing stage:rollbackFailedOptional Completed in 28ms
npm timing stage:runTopLevelLifecycles Completed in 14470ms
npm WARN react-electron-web-view@2.0.1 requires a peer of react@^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-electron-web-view@2.0.1 requires a peer of react-dom@^15.0.0 but none is installed. You must install peer dependencies yourself.

npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! keyboard-layout@2.0.14 install: `node-gyp rebuild`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the keyboard-layout@2.0.14 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm timing npm Completed in 15631ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/adam/.npm/_logs/2019-02-14T15_47_42_612Z-debug.log
```

This is from the debug.log:
```
120 verbose stack Error: keyboard-layout@2.0.14 install: `node-gyp rebuild`
120 verbose stack spawn ENOENT
120 verbose stack     at ChildProcess.<anonymous> (/Users/adam/.asdf/installs/nodejs/8.15.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
120 verbose stack     at emitTwo (events.js:126:13)
120 verbose stack     at ChildProcess.emit (events.js:214:7)
120 verbose stack     at maybeClose (internal/child_process.js:915:16)
120 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
```

**Comment by rodolfoleal** [comment]
Try

npm i keyboard-layout@2.0.12 --ignore-scripts

Looks like it is caused by a post script execution, the --ignore-script flags prevent it to run.

**Comment by adamyonk** [comment]
At some point this just stopped happening, sorry to not have a better solution. 🤷‍♂️
