### ISSUE TITLE
npm global uninstall doesn't remove shims

### ISSUE THREAD

**Issue by torywheelwright** [asdf-vm/asdf-nodejs#89]
Installing another global package seems to call the postinstall script, which does remove the old and add the new. I'm not sure if NPM can be made to hook that script on uninstall as well?

**Comment by andys8** [comment]
Noticed it, too

**Comment by vic** [comment]
On asdf master 0.6.4-dev there is now support for [pre-post command hooks](https://github.com/asdf-vm/asdf/pull/434). Currently they are only read from the user's `.asdfrc` file (so, right now they are user specific and not shared code in the plugin's repo). 

Here's an example for [reshim after rust's `cargo install`](https://github.com/asdf-vm/asdf/issues/409#issuecomment-455812508), so I guess something similar could be made for `npm uninstall -g` ?

**Comment by lucascaton** [comment]
I can confirm this issue is still happening.

**Comment by augustobmoura** [comment]
Should be fixed with #197

**Comment by augustobmoura** [comment]
It should be fixed in master now, as we are not using post-install hooks anymore
